; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27026.1 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	??_C@_0BM@ONKLCLPJ@Palmtree?4Math?4Core?4Uint?4dll@ ; `string'
PUBLIC	??_C@_0BE@LMKJAMNH@PMC_UINT_Initialize@		; `string'
EXTRN	__imp_FreeLibrary:PROC
EXTRN	__imp_GetProcAddress:PROC
EXTRN	__imp_LoadLibraryA:PROC
COMM	ep_uint:BYTE:0230H
_DATA	ENDS
;	COMDAT ??_C@_0BE@LMKJAMNH@PMC_UINT_Initialize@
CONST	SEGMENT
??_C@_0BE@LMKJAMNH@PMC_UINT_Initialize@ DB 'PMC_UINT_Initialize', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BM@ONKLCLPJ@Palmtree?4Math?4Core?4Uint?4dll@
CONST	SEGMENT
??_C@_0BM@ONKLCLPJ@Palmtree?4Math?4Core?4Uint?4dll@ DB 'Palmtree.Math.Cor'
	DB	'e.Uint.dll', 00H				; `string'
CONST	ENDS
PUBLIC	PMC_SINT_Initialize
entry_points DB	0300H DUP (?)
initialized DD	01H DUP (?)
	ALIGN	8

hLib_UINT DQ	01H DUP (?)
fp_PMC_UINT_Initialize DQ 01H DUP (?)
_BSS	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$PMC_SINT_Initialize DD imagerel $LN85@PMC_SINT_I
	DD	imagerel $LN85@PMC_SINT_I+146
	DD	imagerel $unwind$PMC_SINT_Initialize
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$0$PMC_SINT_Initialize DD imagerel $LN85@PMC_SINT_I+146
	DD	imagerel $LN85@PMC_SINT_I+232
	DD	imagerel $chain$0$PMC_SINT_Initialize
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$1$PMC_SINT_Initialize DD imagerel $LN85@PMC_SINT_I+232
	DD	imagerel $LN85@PMC_SINT_I+811
	DD	imagerel $chain$1$PMC_SINT_Initialize
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$LoadUINTLIbrary DD imagerel LoadUINTLIbrary
	DD	imagerel LoadUINTLIbrary+98
	DD	imagerel $unwind$LoadUINTLIbrary
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$CopyUINTEntryPointStructure DD imagerel CopyUINTEntryPointStructure
	DD	imagerel CopyUINTEntryPointStructure+35
	DD	imagerel $unwind$CopyUINTEntryPointStructure
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$_COPY_MEMORY_64 DD imagerel _COPY_MEMORY_64
	DD	imagerel _COPY_MEMORY_64+35
	DD	imagerel $unwind$_COPY_MEMORY_64
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$_COPY_MEMORY_32 DD imagerel _COPY_MEMORY_32
	DD	imagerel _COPY_MEMORY_32+32
	DD	imagerel $unwind$_COPY_MEMORY_32
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$_COPY_MEMORY_BYTE DD imagerel _COPY_MEMORY_BYTE
	DD	imagerel _COPY_MEMORY_BYTE+32
	DD	imagerel $unwind$_COPY_MEMORY_BYTE
;	COMDAT xdata
xdata	SEGMENT
$unwind$_COPY_MEMORY_BYTE DD 040a01H
	DD	02740aH
	DD	016405H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$_COPY_MEMORY_32 DD 040a01H
	DD	02740aH
	DD	016405H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$_COPY_MEMORY_64 DD 040a01H
	DD	02740aH
	DD	016405H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$CopyUINTEntryPointStructure DD 040a01H
	DD	02740aH
	DD	016405H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$LoadUINTLIbrary DD 010401H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$1$PMC_SINT_Initialize DD 021H
	DD	imagerel $LN85@PMC_SINT_I
	DD	imagerel $LN85@PMC_SINT_I+146
	DD	imagerel $unwind$PMC_SINT_Initialize
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$0$PMC_SINT_Initialize DD 020521H
	DD	066405H
	DD	imagerel $LN85@PMC_SINT_I
	DD	imagerel $LN85@PMC_SINT_I+146
	DD	imagerel $unwind$PMC_SINT_Initialize
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$PMC_SINT_Initialize DD 020601H
	DD	070023206H
END
