; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27026.1 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	PMC_To_X_L
PUBLIC	PMC_To_X_I
;	COMDAT pdata
pdata	SEGMENT
$pdata$PMC_To_X_L DD imagerel $LN21@PMC_To_X_L
	DD	imagerel $LN21@PMC_To_X_L+35
	DD	imagerel $unwind$PMC_To_X_L
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$0$PMC_To_X_L DD imagerel $LN21@PMC_To_X_L+35
	DD	imagerel $LN21@PMC_To_X_L+86
	DD	imagerel $chain$0$PMC_To_X_L
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$2$PMC_To_X_L DD imagerel $LN21@PMC_To_X_L+86
	DD	imagerel $LN21@PMC_To_X_L+124
	DD	imagerel $chain$2$PMC_To_X_L
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$4$PMC_To_X_L DD imagerel $LN21@PMC_To_X_L+124
	DD	imagerel $LN21@PMC_To_X_L+155
	DD	imagerel $chain$4$PMC_To_X_L
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$6$PMC_To_X_L DD imagerel $LN21@PMC_To_X_L+155
	DD	imagerel $LN21@PMC_To_X_L+174
	DD	imagerel $chain$6$PMC_To_X_L
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$7$PMC_To_X_L DD imagerel $LN21@PMC_To_X_L+174
	DD	imagerel $LN21@PMC_To_X_L+185
	DD	imagerel $chain$7$PMC_To_X_L
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$PMC_To_X_I DD imagerel $LN21@PMC_To_X_I
	DD	imagerel $LN21@PMC_To_X_I+27
	DD	imagerel $unwind$PMC_To_X_I
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$0$PMC_To_X_I DD imagerel $LN21@PMC_To_X_I+27
	DD	imagerel $LN21@PMC_To_X_I+73
	DD	imagerel $chain$0$PMC_To_X_I
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$2$PMC_To_X_I DD imagerel $LN21@PMC_To_X_I+73
	DD	imagerel $LN21@PMC_To_X_I+101
	DD	imagerel $chain$2$PMC_To_X_I
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$4$PMC_To_X_I DD imagerel $LN21@PMC_To_X_I+101
	DD	imagerel $LN21@PMC_To_X_I+124
	DD	imagerel $chain$4$PMC_To_X_I
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$6$PMC_To_X_I DD imagerel $LN21@PMC_To_X_I+124
	DD	imagerel $LN21@PMC_To_X_I+141
	DD	imagerel $chain$6$PMC_To_X_I
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$7$PMC_To_X_I DD imagerel $LN21@PMC_To_X_I+141
	DD	imagerel $LN21@PMC_To_X_I+152
	DD	imagerel $chain$7$PMC_To_X_I
pdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$7$PMC_To_X_I DD 021H
	DD	imagerel $LN21@PMC_To_X_I
	DD	imagerel $LN21@PMC_To_X_I+27
	DD	imagerel $unwind$PMC_To_X_I
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$6$PMC_To_X_I DD 020021H
	DD	077400H
	DD	imagerel $LN21@PMC_To_X_I
	DD	imagerel $LN21@PMC_To_X_I+27
	DD	imagerel $unwind$PMC_To_X_I
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$4$PMC_To_X_I DD 020021H
	DD	077400H
	DD	imagerel $LN21@PMC_To_X_I
	DD	imagerel $LN21@PMC_To_X_I+27
	DD	imagerel $unwind$PMC_To_X_I
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$2$PMC_To_X_I DD 020021H
	DD	077400H
	DD	imagerel $LN21@PMC_To_X_I
	DD	imagerel $LN21@PMC_To_X_I+27
	DD	imagerel $unwind$PMC_To_X_I
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$0$PMC_To_X_I DD 020521H
	DD	077405H
	DD	imagerel $LN21@PMC_To_X_I
	DD	imagerel $LN21@PMC_To_X_I+27
	DD	imagerel $unwind$PMC_To_X_I
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$PMC_To_X_I DD 020601H
	DD	030023206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$7$PMC_To_X_L DD 021H
	DD	imagerel $LN21@PMC_To_X_L
	DD	imagerel $LN21@PMC_To_X_L+35
	DD	imagerel $unwind$PMC_To_X_L
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$6$PMC_To_X_L DD 020021H
	DD	077400H
	DD	imagerel $LN21@PMC_To_X_L
	DD	imagerel $LN21@PMC_To_X_L+35
	DD	imagerel $unwind$PMC_To_X_L
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$4$PMC_To_X_L DD 020021H
	DD	077400H
	DD	imagerel $LN21@PMC_To_X_L
	DD	imagerel $LN21@PMC_To_X_L+35
	DD	imagerel $unwind$PMC_To_X_L
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$2$PMC_To_X_L DD 020021H
	DD	077400H
	DD	imagerel $LN21@PMC_To_X_L
	DD	imagerel $LN21@PMC_To_X_L+35
	DD	imagerel $unwind$PMC_To_X_L
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$0$PMC_To_X_L DD 020521H
	DD	077405H
	DD	imagerel $LN21@PMC_To_X_L
	DD	imagerel $LN21@PMC_To_X_L+35
	DD	imagerel $unwind$PMC_To_X_L
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$PMC_To_X_L DD 020601H
	DD	030023206H
END
