; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27026.1 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	PMC_ToByteArray
PUBLIC	PMC_FromByteArray
;	COMDAT pdata
pdata	SEGMENT
$pdata$PMC_ToByteArray DD imagerel $LN12@PMC_ToByte
	DD	imagerel $LN12@PMC_ToByte+74
	DD	imagerel $unwind$PMC_ToByteArray
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$PMC_FromByteArray DD imagerel $LN18@PMC_FromBy
	DD	imagerel $LN18@PMC_FromBy+67
	DD	imagerel $unwind$PMC_FromByteArray
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$2$PMC_FromByteArray DD imagerel $LN18@PMC_FromBy+67
	DD	imagerel $LN18@PMC_FromBy+164
	DD	imagerel $chain$2$PMC_FromByteArray
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$3$PMC_FromByteArray DD imagerel $LN18@PMC_FromBy+164
	DD	imagerel $LN18@PMC_FromBy+170
	DD	imagerel $chain$3$PMC_FromByteArray
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$4$PMC_FromByteArray DD imagerel $LN18@PMC_FromBy+170
	DD	imagerel $LN18@PMC_FromBy+181
	DD	imagerel $chain$4$PMC_FromByteArray
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$5$PMC_FromByteArray DD imagerel $LN18@PMC_FromBy+181
	DD	imagerel $LN18@PMC_FromBy+192
	DD	imagerel $chain$5$PMC_FromByteArray
;	COMDAT xdata
xdata	SEGMENT
$chain$5$PMC_FromByteArray DD 021H
	DD	imagerel $LN18@PMC_FromBy
	DD	imagerel $LN18@PMC_FromBy+67
	DD	imagerel $unwind$PMC_FromByteArray
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$4$PMC_FromByteArray DD 060021H
	DD	047400H
	DD	055400H
	DD	093400H
	DD	imagerel $LN18@PMC_FromBy
	DD	imagerel $LN18@PMC_FromBy+67
	DD	imagerel $unwind$PMC_FromByteArray
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$3$PMC_FromByteArray DD 021H
	DD	imagerel $LN18@PMC_FromBy
	DD	imagerel $LN18@PMC_FromBy+67
	DD	imagerel $unwind$PMC_FromByteArray
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$2$PMC_FromByteArray DD 061821H
	DD	047418H
	DD	05540eH
	DD	093405H
	DD	imagerel $LN18@PMC_FromBy
	DD	imagerel $LN18@PMC_FromBy+67
	DD	imagerel $unwind$PMC_FromByteArray
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$PMC_FromByteArray DD 020601H
	DD	060025206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$PMC_ToByteArray DD 010401H
	DD	06204H
END
