; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27026.1 

	TITLE	z:\sources\lunor\repos\rougemeilland\palmtree.math.core.sint\palmtree.math.core.sint\pmc_to.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

PUBLIC	_PMC_To_X_L@8
PUBLIC	_PMC_To_X_I@8
END
