; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27026.1 

	TITLE	z:\sources\lunor\repos\rougemeilland\palmtree.math.core.sint\palmtree.math.core.sint\pmc_greatestcommondivisor.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

PUBLIC	_PMC_GreatestCommonDivisor_X_X@12
PUBLIC	_PMC_GreatestCommonDivisor_X_UX@12
PUBLIC	_PMC_GreatestCommonDivisor_X_L@16
PUBLIC	_PMC_GreatestCommonDivisor_X_I@12
PUBLIC	_PMC_GreatestCommonDivisor_UX_X@12
PUBLIC	_PMC_GreatestCommonDivisor_L_X@16
PUBLIC	_PMC_GreatestCommonDivisor_I_X@12
END
