; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27026.1 

	TITLE	Z:\Sources\Lunor\Repos\rougemeilland\Palmtree.Math.Core.Sint\Palmtree.Math.Core.Sint\pmc_multiply.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

_DATA	SEGMENT
COMM	_uint_number_zero:DWORD
COMM	_uint_number_one:DWORD
_DATA	ENDS
msvcjmc	SEGMENT
__7B7A869E_ctype@h DB 01H
__457DD326_basetsd@h DB 01H
__4384A2D9_corecrt_memcpy_s@h DB 01H
__4E51A221_corecrt_wstring@h DB 01H
__2140C079_string@h DB 01H
__1887E595_winnt@h DB 01H
__9FC7C64B_processthreadsapi@h DB 01H
__FA470AEC_memoryapi@h DB 01H
__F37DAFF1_winerror@h DB 01H
__7A450CCC_winbase@h DB 01H
__B4B40122_winioctl@h DB 01H
__86261D59_stralign@h DB 01H
__8CA3E54E_pmc_inline_func@h DB 01H
__6265BA8B_pmc_multiply@c DB 01H
msvcjmc	ENDS
PUBLIC	_PMC_Multiply_I_X@12
PUBLIC	_PMC_Multiply_L_X@16
PUBLIC	_PMC_Multiply_UX_X@12
PUBLIC	_PMC_Multiply_X_I@12
PUBLIC	_PMC_Multiply_X_L@16
PUBLIC	_PMC_Multiply_X_UX@12
PUBLIC	_PMC_Multiply_X_X@12
PUBLIC	__JustMyCode_Default
EXTRN	_AllocateNumber:PROC
EXTRN	_CheckNumber:PROC
EXTRN	@_RTC_CheckStackVars@8:PROC
EXTRN	@__CheckForDebuggerJustMyCode@4:PROC
EXTRN	@__security_check_cookie@4:PROC
EXTRN	__RTC_CheckEsp:PROC
EXTRN	__RTC_InitBase:PROC
EXTRN	__RTC_Shutdown:PROC
EXTRN	_ep_uint:BYTE
EXTRN	_number_zero:BYTE
EXTRN	___security_cookie:DWORD
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
rtc$IMZ	ENDS
; Function compile flags: /Odt
;	COMDAT __JustMyCode_Default
_TEXT	SEGMENT
__JustMyCode_Default PROC				; COMDAT
	push	ebp
	mov	ebp, esp
	pop	ebp
	ret	0
__JustMyCode_Default ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.sint\palmtree.math.core.sint\pmc_multiply.c
;	COMDAT _MultiplyU_X_X_Imp
_TEXT	SEGMENT
_w_abs$ = -24						; size = 4
_result$ = -12						; size = 4
__$ArrayPad$ = -4					; size = 4
_w_sign$ = 8						; size = 1
_u$ = 12						; size = 4
_v$ = 16						; size = 4
_w$ = 20						; size = 4
_MultiplyU_X_X_Imp PROC					; COMDAT

; 72   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 220				; 000000dcH
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-220]
	mov	ecx, 55					; 00000037H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	mov	DWORD PTR __$ArrayPad$[ebp], eax
	mov	ecx, OFFSET __6265BA8B_pmc_multiply@c
	call	@__CheckForDebuggerJustMyCode@4

; 73   : #ifdef _DEBUG
; 74   :     if (u->FLAGS.IS_ZERO)

	mov	eax, DWORD PTR _u$[ebp]
	mov	ecx, DWORD PTR [eax]
	and	ecx, 1
	je	SHORT $LN2@MultiplyU_

; 75   :         return (PMC_STATUS_INTERNAL_ERROR);

	mov	eax, -256				; ffffff00H
	jmp	SHORT $LN1@MultiplyU_
$LN2@MultiplyU_:

; 76   :     if (v->FLAGS.IS_ZERO)

	mov	eax, DWORD PTR _v$[ebp]
	mov	ecx, DWORD PTR [eax]
	and	ecx, 1
	je	SHORT $LN3@MultiplyU_

; 77   :         return (PMC_STATUS_INTERNAL_ERROR);

	mov	eax, -256				; ffffff00H
	jmp	SHORT $LN1@MultiplyU_
$LN3@MultiplyU_:

; 78   : #endif
; 79   :     PMC_STATUS_CODE result;
; 80   :     PMC_HANDLE_UINT w_abs;
; 81   :     if ((result = ep_uint.Multiply_X_X(u, v, &w_abs)) != PMC_STATUS_OK)

	mov	esi, esp
	lea	eax, DWORD PTR _w_abs$[ebp]
	push	eax
	mov	ecx, DWORD PTR _v$[ebp]
	push	ecx
	mov	edx, DWORD PTR _u$[ebp]
	push	edx
	call	DWORD PTR _ep_uint+112
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _result$[ebp], eax
	cmp	DWORD PTR _result$[ebp], 0
	je	SHORT $LN4@MultiplyU_

; 82   :         return (result);

	mov	eax, DWORD PTR _result$[ebp]
	jmp	SHORT $LN1@MultiplyU_
$LN4@MultiplyU_:

; 83   :     if ((result = AllocateNumber(w, w_sign, w_abs)) != PMC_STATUS_OK)

	mov	eax, DWORD PTR _w_abs$[ebp]
	push	eax
	movzx	ecx, BYTE PTR _w_sign$[ebp]
	push	ecx
	mov	edx, DWORD PTR _w$[ebp]
	push	edx
	call	_AllocateNumber
	add	esp, 12					; 0000000cH
	mov	DWORD PTR _result$[ebp], eax
	cmp	DWORD PTR _result$[ebp], 0
	je	SHORT $LN5@MultiplyU_

; 84   :     {
; 85   :         ep_uint.Dispose(w_abs);

	mov	esi, esp
	mov	eax, DWORD PTR _w_abs$[ebp]
	push	eax
	call	DWORD PTR _ep_uint+16
	cmp	esi, esp
	call	__RTC_CheckEsp

; 86   :         return (result);

	mov	eax, DWORD PTR _result$[ebp]
	jmp	SHORT $LN1@MultiplyU_
$LN5@MultiplyU_:

; 87   :     }
; 88   :     return (PMC_STATUS_OK);

	xor	eax, eax
$LN1@MultiplyU_:

; 89   : }

	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN9@MultiplyU_
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	pop	edi
	pop	esi
	pop	ebx
	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	ecx, ebp
	call	@__security_check_cookie@4
	add	esp, 220				; 000000dcH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
$LN9@MultiplyU_:
	DD	1
	DD	$LN8@MultiplyU_
$LN8@MultiplyU_:
	DD	-24					; ffffffe8H
	DD	4
	DD	$LN7@MultiplyU_
$LN7@MultiplyU_:
	DB	119					; 00000077H
	DB	95					; 0000005fH
	DB	97					; 00000061H
	DB	98					; 00000062H
	DB	115					; 00000073H
	DB	0
_MultiplyU_X_X_Imp ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.sint\palmtree.math.core.sint\pmc_multiply.c
;	COMDAT _MultiplyU_X_L_Imp
_TEXT	SEGMENT
_w_abs$ = -24						; size = 4
_result$ = -12						; size = 4
__$ArrayPad$ = -4					; size = 4
_w_sign$ = 8						; size = 1
_u$ = 12						; size = 4
_v$ = 16						; size = 8
_w$ = 24						; size = 4
_MultiplyU_X_L_Imp PROC					; COMDAT

; 52   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 220				; 000000dcH
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-220]
	mov	ecx, 55					; 00000037H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	mov	DWORD PTR __$ArrayPad$[ebp], eax
	mov	ecx, OFFSET __6265BA8B_pmc_multiply@c
	call	@__CheckForDebuggerJustMyCode@4

; 53   : #ifdef _DEBUG
; 54   :     if (u->FLAGS.IS_ZERO)

	mov	eax, DWORD PTR _u$[ebp]
	mov	ecx, DWORD PTR [eax]
	and	ecx, 1
	je	SHORT $LN2@MultiplyU_

; 55   :         return (PMC_STATUS_INTERNAL_ERROR);

	mov	eax, -256				; ffffff00H
	jmp	SHORT $LN1@MultiplyU_
$LN2@MultiplyU_:

; 56   :     if (v == 0)

	mov	eax, DWORD PTR _v$[ebp]
	or	eax, DWORD PTR _v$[ebp+4]
	jne	SHORT $LN3@MultiplyU_

; 57   :         return (PMC_STATUS_INTERNAL_ERROR);

	mov	eax, -256				; ffffff00H
	jmp	SHORT $LN1@MultiplyU_
$LN3@MultiplyU_:

; 58   : #endif
; 59   :     PMC_STATUS_CODE result;
; 60   :     PMC_HANDLE_UINT w_abs;
; 61   :     if ((result = ep_uint.Multiply_X_L(u, v, &w_abs)) != PMC_STATUS_OK)

	mov	esi, esp
	lea	eax, DWORD PTR _w_abs$[ebp]
	push	eax
	mov	ecx, DWORD PTR _v$[ebp+4]
	push	ecx
	mov	edx, DWORD PTR _v$[ebp]
	push	edx
	mov	eax, DWORD PTR _u$[ebp]
	push	eax
	call	DWORD PTR _ep_uint+108
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _result$[ebp], eax
	cmp	DWORD PTR _result$[ebp], 0
	je	SHORT $LN4@MultiplyU_

; 62   :         return (result);

	mov	eax, DWORD PTR _result$[ebp]
	jmp	SHORT $LN1@MultiplyU_
$LN4@MultiplyU_:

; 63   :     if ((result = AllocateNumber(w, w_sign, w_abs)) != PMC_STATUS_OK)

	mov	eax, DWORD PTR _w_abs$[ebp]
	push	eax
	movzx	ecx, BYTE PTR _w_sign$[ebp]
	push	ecx
	mov	edx, DWORD PTR _w$[ebp]
	push	edx
	call	_AllocateNumber
	add	esp, 12					; 0000000cH
	mov	DWORD PTR _result$[ebp], eax
	cmp	DWORD PTR _result$[ebp], 0
	je	SHORT $LN5@MultiplyU_

; 64   :     {
; 65   :         ep_uint.Dispose(w_abs);

	mov	esi, esp
	mov	eax, DWORD PTR _w_abs$[ebp]
	push	eax
	call	DWORD PTR _ep_uint+16
	cmp	esi, esp
	call	__RTC_CheckEsp

; 66   :         return (result);

	mov	eax, DWORD PTR _result$[ebp]
	jmp	SHORT $LN1@MultiplyU_
$LN5@MultiplyU_:

; 67   :     }
; 68   :     return (PMC_STATUS_OK);

	xor	eax, eax
$LN1@MultiplyU_:

; 69   : }

	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN9@MultiplyU_
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	pop	edi
	pop	esi
	pop	ebx
	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	ecx, ebp
	call	@__security_check_cookie@4
	add	esp, 220				; 000000dcH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
	npad	2
$LN9@MultiplyU_:
	DD	1
	DD	$LN8@MultiplyU_
$LN8@MultiplyU_:
	DD	-24					; ffffffe8H
	DD	4
	DD	$LN7@MultiplyU_
$LN7@MultiplyU_:
	DB	119					; 00000077H
	DB	95					; 0000005fH
	DB	97					; 00000061H
	DB	98					; 00000062H
	DB	115					; 00000073H
	DB	0
_MultiplyU_X_L_Imp ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.sint\palmtree.math.core.sint\pmc_multiply.c
;	COMDAT _MultiplyU_X_I_Imp
_TEXT	SEGMENT
_w_abs$ = -24						; size = 4
_result$ = -12						; size = 4
__$ArrayPad$ = -4					; size = 4
_w_sign$ = 8						; size = 1
_u$ = 12						; size = 4
_v$ = 16						; size = 4
_w$ = 20						; size = 4
_MultiplyU_X_I_Imp PROC					; COMDAT

; 32   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 220				; 000000dcH
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-220]
	mov	ecx, 55					; 00000037H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	mov	DWORD PTR __$ArrayPad$[ebp], eax
	mov	ecx, OFFSET __6265BA8B_pmc_multiply@c
	call	@__CheckForDebuggerJustMyCode@4

; 33   : #ifdef _DEBUG
; 34   :     if (u->FLAGS.IS_ZERO)

	mov	eax, DWORD PTR _u$[ebp]
	mov	ecx, DWORD PTR [eax]
	and	ecx, 1
	je	SHORT $LN2@MultiplyU_

; 35   :         return (PMC_STATUS_INTERNAL_ERROR);

	mov	eax, -256				; ffffff00H
	jmp	SHORT $LN1@MultiplyU_
$LN2@MultiplyU_:

; 36   :     if (v == 0)

	cmp	DWORD PTR _v$[ebp], 0
	jne	SHORT $LN3@MultiplyU_

; 37   :         return (PMC_STATUS_INTERNAL_ERROR);

	mov	eax, -256				; ffffff00H
	jmp	SHORT $LN1@MultiplyU_
$LN3@MultiplyU_:

; 38   : #endif
; 39   :     PMC_STATUS_CODE result;
; 40   :     PMC_HANDLE_UINT w_abs;
; 41   :     if ((result = ep_uint.Multiply_X_I(u, v, &w_abs)) != PMC_STATUS_OK)

	mov	esi, esp
	lea	eax, DWORD PTR _w_abs$[ebp]
	push	eax
	mov	ecx, DWORD PTR _v$[ebp]
	push	ecx
	mov	edx, DWORD PTR _u$[ebp]
	push	edx
	call	DWORD PTR _ep_uint+104
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _result$[ebp], eax
	cmp	DWORD PTR _result$[ebp], 0
	je	SHORT $LN4@MultiplyU_

; 42   :         return (result);

	mov	eax, DWORD PTR _result$[ebp]
	jmp	SHORT $LN1@MultiplyU_
$LN4@MultiplyU_:

; 43   :     if ((result = AllocateNumber(w, w_sign, w_abs)) != PMC_STATUS_OK)

	mov	eax, DWORD PTR _w_abs$[ebp]
	push	eax
	movzx	ecx, BYTE PTR _w_sign$[ebp]
	push	ecx
	mov	edx, DWORD PTR _w$[ebp]
	push	edx
	call	_AllocateNumber
	add	esp, 12					; 0000000cH
	mov	DWORD PTR _result$[ebp], eax
	cmp	DWORD PTR _result$[ebp], 0
	je	SHORT $LN5@MultiplyU_

; 44   :     {
; 45   :         ep_uint.Dispose(w_abs);

	mov	esi, esp
	mov	eax, DWORD PTR _w_abs$[ebp]
	push	eax
	call	DWORD PTR _ep_uint+16
	cmp	esi, esp
	call	__RTC_CheckEsp

; 46   :         return (result);

	mov	eax, DWORD PTR _result$[ebp]
	jmp	SHORT $LN1@MultiplyU_
$LN5@MultiplyU_:

; 47   :     }
; 48   :     return (PMC_STATUS_OK);

	xor	eax, eax
$LN1@MultiplyU_:

; 49   : }

	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN9@MultiplyU_
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	pop	edi
	pop	esi
	pop	ebx
	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	ecx, ebp
	call	@__security_check_cookie@4
	add	esp, 220				; 000000dcH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
$LN9@MultiplyU_:
	DD	1
	DD	$LN8@MultiplyU_
$LN8@MultiplyU_:
	DD	-24					; ffffffe8H
	DD	4
	DD	$LN7@MultiplyU_
$LN7@MultiplyU_:
	DB	119					; 00000077H
	DB	95					; 0000005fH
	DB	97					; 00000061H
	DB	98					; 00000062H
	DB	115					; 00000073H
	DB	0
_MultiplyU_X_I_Imp ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.uint\palmtree.math.core.uint\pmc_inline_func.h
;	COMDAT _GET_ABS_64
_TEXT	SEGMENT
tv68 = -200						; size = 8
_u$ = 8							; size = 8
_sign$ = 16						; size = 4
_GET_ABS_64 PROC					; COMDAT

; 800  :     {

	push	ebp
	mov	ebp, esp
	sub	esp, 200				; 000000c8H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-200]
	mov	ecx, 50					; 00000032H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	ecx, OFFSET __8CA3E54E_pmc_inline_func@h
	call	@__CheckForDebuggerJustMyCode@4

; 801  :         if (u > 0)

	cmp	DWORD PTR _u$[ebp+4], 0
	jl	SHORT $LN2@GET_ABS_64
	jg	SHORT $LN9@GET_ABS_64
	cmp	DWORD PTR _u$[ebp], 0
	jbe	SHORT $LN2@GET_ABS_64
$LN9@GET_ABS_64:

; 802  :         {
; 803  :             *sign = 1;

	mov	eax, DWORD PTR _sign$[ebp]
	mov	BYTE PTR [eax], 1

; 804  :             return ((_UINT64_T)u);

	mov	eax, DWORD PTR _u$[ebp]
	mov	edx, DWORD PTR _u$[ebp+4]
	jmp	SHORT $LN1@GET_ABS_64

; 805  :         }

	jmp	SHORT $LN1@GET_ABS_64
$LN2@GET_ABS_64:

; 806  :         else if (u == 0)

	mov	eax, DWORD PTR _u$[ebp]
	or	eax, DWORD PTR _u$[ebp+4]
	jne	SHORT $LN4@GET_ABS_64

; 807  :         {
; 808  :             *sign = 0;

	mov	eax, DWORD PTR _sign$[ebp]
	mov	BYTE PTR [eax], 0

; 809  :             return (0);

	xor	eax, eax
	xor	edx, edx
	jmp	SHORT $LN1@GET_ABS_64

; 810  :         }

	jmp	SHORT $LN1@GET_ABS_64
$LN4@GET_ABS_64:

; 811  :         else
; 812  :         {
; 813  :             *sign = -1;

	mov	eax, DWORD PTR _sign$[ebp]
	mov	BYTE PTR [eax], -1

; 814  :             return ((_UINT64_T)u == 0x8000000000000000UL ? 0x8000000000000000UL : (_UINT64_T)-u);

	cmp	DWORD PTR _u$[ebp], 0
	jne	SHORT $LN7@GET_ABS_64
	cmp	DWORD PTR _u$[ebp+4], -2147483648	; 80000000H
	jne	SHORT $LN7@GET_ABS_64
	mov	DWORD PTR tv68[ebp], 0
	mov	DWORD PTR tv68[ebp+4], -2147483648	; 80000000H
	jmp	SHORT $LN8@GET_ABS_64
$LN7@GET_ABS_64:
	mov	eax, DWORD PTR _u$[ebp]
	neg	eax
	mov	ecx, DWORD PTR _u$[ebp+4]
	adc	ecx, 0
	neg	ecx
	mov	DWORD PTR tv68[ebp], eax
	mov	DWORD PTR tv68[ebp+4], ecx
$LN8@GET_ABS_64:
	mov	eax, DWORD PTR tv68[ebp]
	mov	edx, DWORD PTR tv68[ebp+4]
$LN1@GET_ABS_64:

; 815  :         }
; 816  :     }

	pop	edi
	pop	esi
	pop	ebx
	add	esp, 200				; 000000c8H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
_GET_ABS_64 ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.uint\palmtree.math.core.uint\pmc_inline_func.h
;	COMDAT _GET_ABS_32
_TEXT	SEGMENT
tv68 = -196						; size = 4
_u$ = 8							; size = 4
_sign$ = 12						; size = 4
_GET_ABS_32 PROC					; COMDAT

; 780  :     {

	push	ebp
	mov	ebp, esp
	sub	esp, 196				; 000000c4H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-196]
	mov	ecx, 49					; 00000031H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	ecx, OFFSET __8CA3E54E_pmc_inline_func@h
	call	@__CheckForDebuggerJustMyCode@4

; 781  :         if (u > 0)

	cmp	DWORD PTR _u$[ebp], 0
	jle	SHORT $LN2@GET_ABS_32

; 782  :         {
; 783  :             *sign = 1;

	mov	eax, DWORD PTR _sign$[ebp]
	mov	BYTE PTR [eax], 1

; 784  :             return ((_UINT32_T)u);

	mov	eax, DWORD PTR _u$[ebp]
	jmp	SHORT $LN1@GET_ABS_32

; 785  :         }

	jmp	SHORT $LN1@GET_ABS_32
$LN2@GET_ABS_32:

; 786  :         else if (u == 0)

	cmp	DWORD PTR _u$[ebp], 0
	jne	SHORT $LN4@GET_ABS_32

; 787  :         {
; 788  :             *sign = 0;

	mov	eax, DWORD PTR _sign$[ebp]
	mov	BYTE PTR [eax], 0

; 789  :             return (0);

	xor	eax, eax
	jmp	SHORT $LN1@GET_ABS_32

; 790  :         }

	jmp	SHORT $LN1@GET_ABS_32
$LN4@GET_ABS_32:

; 791  :         else
; 792  :         {
; 793  :             *sign = -1;

	mov	eax, DWORD PTR _sign$[ebp]
	mov	BYTE PTR [eax], -1

; 794  :             return ((_UINT32_T)u == 0x80000000U ? 0x80000000U : (_UINT32_T)-u);

	cmp	DWORD PTR _u$[ebp], -2147483648		; 80000000H
	jne	SHORT $LN7@GET_ABS_32
	mov	DWORD PTR tv68[ebp], -2147483648	; 80000000H
	jmp	SHORT $LN8@GET_ABS_32
$LN7@GET_ABS_32:
	mov	eax, DWORD PTR _u$[ebp]
	neg	eax
	mov	DWORD PTR tv68[ebp], eax
$LN8@GET_ABS_32:
	mov	eax, DWORD PTR tv68[ebp]
$LN1@GET_ABS_32:

; 795  :         }
; 796  : }

	pop	edi
	pop	esi
	pop	ebx
	add	esp, 196				; 000000c4H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
_GET_ABS_32 ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.sint\palmtree.math.core.sint\pmc_multiply.c
;	COMDAT _PMC_Multiply_X_X@12
_TEXT	SEGMENT
_nw$ = -48						; size = 4
_nv$ = -36						; size = 4
_nu$ = -24						; size = 4
_result$ = -12						; size = 4
__$ArrayPad$ = -4					; size = 4
_u$ = 8							; size = 4
_v$ = 12						; size = 4
_w$ = 16						; size = 4
_PMC_Multiply_X_X@12 PROC				; COMDAT

; 437  : {

	push	ebp
	mov	ebp, esp
	sub	esp, 244				; 000000f4H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-244]
	mov	ecx, 61					; 0000003dH
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	mov	DWORD PTR __$ArrayPad$[ebp], eax
	mov	ecx, OFFSET __6265BA8B_pmc_multiply@c
	call	@__CheckForDebuggerJustMyCode@4

; 438  :     if (u == NULL)

	cmp	DWORD PTR _u$[ebp], 0
	jne	SHORT $LN2@PMC_Multip

; 439  :         return (PMC_STATUS_ARGUMENT_ERROR);

	or	eax, -1
	jmp	$LN1@PMC_Multip
$LN2@PMC_Multip:

; 440  :     if (v == NULL)

	cmp	DWORD PTR _v$[ebp], 0
	jne	SHORT $LN3@PMC_Multip

; 441  :         return (PMC_STATUS_ARGUMENT_ERROR);

	or	eax, -1
	jmp	$LN1@PMC_Multip
$LN3@PMC_Multip:

; 442  :     if (w == NULL)

	cmp	DWORD PTR _w$[ebp], 0
	jne	SHORT $LN4@PMC_Multip

; 443  :         return (PMC_STATUS_ARGUMENT_ERROR);

	or	eax, -1
	jmp	$LN1@PMC_Multip
$LN4@PMC_Multip:

; 444  :     PMC_STATUS_CODE result;
; 445  :     NUMBER_HEADER* nu = (NUMBER_HEADER*)u;

	mov	eax, DWORD PTR _u$[ebp]
	mov	DWORD PTR _nu$[ebp], eax

; 446  :     NUMBER_HEADER* nv = (NUMBER_HEADER*)v;

	mov	eax, DWORD PTR _v$[ebp]
	mov	DWORD PTR _nv$[ebp], eax

; 447  :     NUMBER_HEADER* nw;
; 448  :     if ((result = CheckNumber(nu)) != PMC_STATUS_OK)

	mov	eax, DWORD PTR _nu$[ebp]
	push	eax
	call	_CheckNumber
	add	esp, 4
	mov	DWORD PTR _result$[ebp], eax
	cmp	DWORD PTR _result$[ebp], 0
	je	SHORT $LN5@PMC_Multip

; 449  :         return (result);

	mov	eax, DWORD PTR _result$[ebp]
	jmp	$LN1@PMC_Multip
$LN5@PMC_Multip:

; 450  :     if ((result = CheckNumber(nv)) != PMC_STATUS_OK)

	mov	eax, DWORD PTR _nv$[ebp]
	push	eax
	call	_CheckNumber
	add	esp, 4
	mov	DWORD PTR _result$[ebp], eax
	cmp	DWORD PTR _result$[ebp], 0
	je	SHORT $LN6@PMC_Multip

; 451  :         return (result);

	mov	eax, DWORD PTR _result$[ebp]
	jmp	$LN1@PMC_Multip
$LN6@PMC_Multip:

; 452  :     if (nu->SIGN == 0)

	mov	eax, DWORD PTR _nu$[ebp]
	movsx	ecx, BYTE PTR [eax+16]
	test	ecx, ecx
	jne	SHORT $LN7@PMC_Multip

; 453  :     {
; 454  :         // u == 0 の場合
; 455  : 
; 456  :         // 0 を返す
; 457  :         nw = &number_zero;

	mov	DWORD PTR _nw$[ebp], OFFSET _number_zero

; 458  :     }

	jmp	$LN8@PMC_Multip
$LN7@PMC_Multip:

; 459  :     else if (nu->SIGN > 0)

	mov	eax, DWORD PTR _nu$[ebp]
	movsx	ecx, BYTE PTR [eax+16]
	test	ecx, ecx
	jle	SHORT $LN9@PMC_Multip

; 460  :     {
; 461  :         // u > 0 の場合
; 462  : 
; 463  :         if (nv->SIGN == 0)

	mov	eax, DWORD PTR _nv$[ebp]
	movsx	ecx, BYTE PTR [eax+16]
	test	ecx, ecx
	jne	SHORT $LN11@PMC_Multip

; 464  :         {
; 465  :             // v == 0 の場合
; 466  : 
; 467  :             // 0 を返す
; 468  :             nw = &number_zero;

	mov	DWORD PTR _nw$[ebp], OFFSET _number_zero

; 469  :         }

	jmp	SHORT $LN12@PMC_Multip
$LN11@PMC_Multip:

; 470  :         else
; 471  :         {
; 472  :             // v != 0 の場合
; 473  : 
; 474  :             // abs(u) * v を返す
; 475  :             if ((result = MultiplyU_X_X_Imp(nv->SIGN, nu->ABS, nv->ABS, &nw)) != PMC_STATUS_OK)

	lea	eax, DWORD PTR _nw$[ebp]
	push	eax
	mov	ecx, DWORD PTR _nv$[ebp]
	mov	edx, DWORD PTR [ecx+12]
	push	edx
	mov	eax, DWORD PTR _nu$[ebp]
	mov	ecx, DWORD PTR [eax+12]
	push	ecx
	mov	edx, DWORD PTR _nv$[ebp]
	movzx	eax, BYTE PTR [edx+16]
	push	eax
	call	_MultiplyU_X_X_Imp
	add	esp, 16					; 00000010H
	mov	DWORD PTR _result$[ebp], eax
	cmp	DWORD PTR _result$[ebp], 0
	je	SHORT $LN12@PMC_Multip

; 476  :                 return (result);

	mov	eax, DWORD PTR _result$[ebp]
	jmp	SHORT $LN1@PMC_Multip
$LN12@PMC_Multip:

; 477  :         }
; 478  :     }

	jmp	SHORT $LN8@PMC_Multip
$LN9@PMC_Multip:

; 479  :     else
; 480  :     {
; 481  :         // u < 0 の場合
; 482  : 
; 483  :         if (nv->SIGN == 0)

	mov	eax, DWORD PTR _nv$[ebp]
	movsx	ecx, BYTE PTR [eax+16]
	test	ecx, ecx
	jne	SHORT $LN14@PMC_Multip

; 484  :         {
; 485  :             // v == 0 の場合
; 486  : 
; 487  :             // 0 を返す
; 488  :             nw = &number_zero;

	mov	DWORD PTR _nw$[ebp], OFFSET _number_zero

; 489  :         }

	jmp	SHORT $LN8@PMC_Multip
$LN14@PMC_Multip:

; 490  :         else
; 491  :         {
; 492  :             // v != 0 の場合
; 493  : 
; 494  :             // -abs(u) * v を返す
; 495  :             if ((result = MultiplyU_X_X_Imp(-nv->SIGN, nu->ABS, nv->ABS, &nw)) != PMC_STATUS_OK)

	lea	eax, DWORD PTR _nw$[ebp]
	push	eax
	mov	ecx, DWORD PTR _nv$[ebp]
	mov	edx, DWORD PTR [ecx+12]
	push	edx
	mov	eax, DWORD PTR _nu$[ebp]
	mov	ecx, DWORD PTR [eax+12]
	push	ecx
	mov	edx, DWORD PTR _nv$[ebp]
	movsx	eax, BYTE PTR [edx+16]
	neg	eax
	push	eax
	call	_MultiplyU_X_X_Imp
	add	esp, 16					; 00000010H
	mov	DWORD PTR _result$[ebp], eax
	cmp	DWORD PTR _result$[ebp], 0
	je	SHORT $LN8@PMC_Multip

; 496  :                 return (result);

	mov	eax, DWORD PTR _result$[ebp]
	jmp	SHORT $LN1@PMC_Multip
$LN8@PMC_Multip:

; 497  :         }
; 498  :     }
; 499  :     *w = (PMC_HANDLE_SINT)nw;

	mov	eax, DWORD PTR _w$[ebp]
	mov	ecx, DWORD PTR _nw$[ebp]
	mov	DWORD PTR [eax], ecx

; 500  :     return (PMC_STATUS_OK);

	xor	eax, eax
$LN1@PMC_Multip:

; 501  : }

	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN20@PMC_Multip
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	pop	edi
	pop	esi
	pop	ebx
	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	ecx, ebp
	call	@__security_check_cookie@4
	add	esp, 244				; 000000f4H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
	npad	1
$LN20@PMC_Multip:
	DD	1
	DD	$LN19@PMC_Multip
$LN19@PMC_Multip:
	DD	-48					; ffffffd0H
	DD	4
	DD	$LN18@PMC_Multip
$LN18@PMC_Multip:
	DB	110					; 0000006eH
	DB	119					; 00000077H
	DB	0
_PMC_Multiply_X_X@12 ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.sint\palmtree.math.core.sint\pmc_multiply.c
;	COMDAT _PMC_Multiply_X_UX@12
_TEXT	SEGMENT
_nw$ = -36						; size = 4
_nu$ = -24						; size = 4
_result$ = -12						; size = 4
__$ArrayPad$ = -4					; size = 4
_u$ = 8							; size = 4
_v$ = 12						; size = 4
_w$ = 16						; size = 4
_PMC_Multiply_X_UX@12 PROC				; COMDAT

; 392  : {

	push	ebp
	mov	ebp, esp
	sub	esp, 232				; 000000e8H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-232]
	mov	ecx, 58					; 0000003aH
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	mov	DWORD PTR __$ArrayPad$[ebp], eax
	mov	ecx, OFFSET __6265BA8B_pmc_multiply@c
	call	@__CheckForDebuggerJustMyCode@4

; 393  :     if (u == NULL)

	cmp	DWORD PTR _u$[ebp], 0
	jne	SHORT $LN2@PMC_Multip

; 394  :         return (PMC_STATUS_ARGUMENT_ERROR);

	or	eax, -1
	jmp	$LN1@PMC_Multip
$LN2@PMC_Multip:

; 395  :     if (v == NULL)

	cmp	DWORD PTR _v$[ebp], 0
	jne	SHORT $LN3@PMC_Multip

; 396  :         return (PMC_STATUS_ARGUMENT_ERROR);

	or	eax, -1
	jmp	$LN1@PMC_Multip
$LN3@PMC_Multip:

; 397  :     if (w == NULL)

	cmp	DWORD PTR _w$[ebp], 0
	jne	SHORT $LN4@PMC_Multip

; 398  :         return (PMC_STATUS_ARGUMENT_ERROR);

	or	eax, -1
	jmp	SHORT $LN1@PMC_Multip
$LN4@PMC_Multip:

; 399  :     PMC_STATUS_CODE result;
; 400  :     NUMBER_HEADER* nu = (NUMBER_HEADER*)u;

	mov	eax, DWORD PTR _u$[ebp]
	mov	DWORD PTR _nu$[ebp], eax

; 401  :     NUMBER_HEADER* nw;
; 402  :     if ((result = CheckNumber(nu)) != PMC_STATUS_OK)

	mov	eax, DWORD PTR _nu$[ebp]
	push	eax
	call	_CheckNumber
	add	esp, 4
	mov	DWORD PTR _result$[ebp], eax
	cmp	DWORD PTR _result$[ebp], 0
	je	SHORT $LN5@PMC_Multip

; 403  :         return (result);

	mov	eax, DWORD PTR _result$[ebp]
	jmp	SHORT $LN1@PMC_Multip
$LN5@PMC_Multip:

; 404  :     if (nu->SIGN == 0)

	mov	eax, DWORD PTR _nu$[ebp]
	movsx	ecx, BYTE PTR [eax+16]
	test	ecx, ecx
	jne	SHORT $LN6@PMC_Multip

; 405  :     {
; 406  :         // u == 0 の場合
; 407  : 
; 408  :         // 0 を返す
; 409  :         nw = &number_zero;

	mov	DWORD PTR _nw$[ebp], OFFSET _number_zero

; 410  :     }

	jmp	SHORT $LN7@PMC_Multip
$LN6@PMC_Multip:

; 411  :     else
; 412  :     {
; 413  :         // u != 0 の場合
; 414  : 
; 415  :         if (v->FLAGS.IS_ZERO)

	mov	eax, DWORD PTR _v$[ebp]
	mov	ecx, DWORD PTR [eax]
	and	ecx, 1
	je	SHORT $LN8@PMC_Multip

; 416  :         {
; 417  :             // v == 0 の場合
; 418  : 
; 419  :             // 0 を返す
; 420  :             nw = &number_zero;

	mov	DWORD PTR _nw$[ebp], OFFSET _number_zero

; 421  :         }

	jmp	SHORT $LN7@PMC_Multip
$LN8@PMC_Multip:

; 422  :         else
; 423  :         {
; 424  :             // v > 0 の場合
; 425  : 
; 426  :             // u * v を返す
; 427  :             if ((result = MultiplyU_X_X_Imp(nu->SIGN, nu->ABS, v, &nw)) != PMC_STATUS_OK)

	lea	eax, DWORD PTR _nw$[ebp]
	push	eax
	mov	ecx, DWORD PTR _v$[ebp]
	push	ecx
	mov	edx, DWORD PTR _nu$[ebp]
	mov	eax, DWORD PTR [edx+12]
	push	eax
	mov	ecx, DWORD PTR _nu$[ebp]
	movzx	edx, BYTE PTR [ecx+16]
	push	edx
	call	_MultiplyU_X_X_Imp
	add	esp, 16					; 00000010H
	mov	DWORD PTR _result$[ebp], eax
	cmp	DWORD PTR _result$[ebp], 0
	je	SHORT $LN7@PMC_Multip

; 428  :                 return (result);

	mov	eax, DWORD PTR _result$[ebp]
	jmp	SHORT $LN1@PMC_Multip
$LN7@PMC_Multip:

; 429  :         }
; 430  : 
; 431  :     }
; 432  :     *w = (PMC_HANDLE_SINT)nw;

	mov	eax, DWORD PTR _w$[ebp]
	mov	ecx, DWORD PTR _nw$[ebp]
	mov	DWORD PTR [eax], ecx

; 433  :     return (PMC_STATUS_OK);

	xor	eax, eax
$LN1@PMC_Multip:

; 434  : }

	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN14@PMC_Multip
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	pop	edi
	pop	esi
	pop	ebx
	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	ecx, ebp
	call	@__security_check_cookie@4
	add	esp, 232				; 000000e8H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
$LN14@PMC_Multip:
	DD	1
	DD	$LN13@PMC_Multip
$LN13@PMC_Multip:
	DD	-36					; ffffffdcH
	DD	4
	DD	$LN12@PMC_Multip
$LN12@PMC_Multip:
	DB	110					; 0000006eH
	DB	119					; 00000077H
	DB	0
_PMC_Multiply_X_UX@12 ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.sint\palmtree.math.core.sint\pmc_multiply.c
;	COMDAT _PMC_Multiply_X_L@16
_TEXT	SEGMENT
_v_abs$ = -64						; size = 8
_v_sign$ = -45						; size = 1
_nw$ = -36						; size = 4
_nu$ = -24						; size = 4
_result$ = -12						; size = 4
__$ArrayPad$ = -4					; size = 4
_u$ = 8							; size = 4
_v$ = 12						; size = 8
_w$ = 20						; size = 4
_PMC_Multiply_X_L@16 PROC				; COMDAT

; 328  : {

	push	ebp
	mov	ebp, esp
	sub	esp, 260				; 00000104H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-260]
	mov	ecx, 65					; 00000041H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	mov	DWORD PTR __$ArrayPad$[ebp], eax
	mov	ecx, OFFSET __6265BA8B_pmc_multiply@c
	call	@__CheckForDebuggerJustMyCode@4

; 329  :     if (u == NULL)

	cmp	DWORD PTR _u$[ebp], 0
	jne	SHORT $LN2@PMC_Multip

; 330  :         return (PMC_STATUS_ARGUMENT_ERROR);

	or	eax, -1
	jmp	$LN1@PMC_Multip
$LN2@PMC_Multip:

; 331  :     if (w == NULL)

	cmp	DWORD PTR _w$[ebp], 0
	jne	SHORT $LN3@PMC_Multip

; 332  :         return (PMC_STATUS_ARGUMENT_ERROR);

	or	eax, -1
	jmp	$LN1@PMC_Multip
$LN3@PMC_Multip:

; 333  :     PMC_STATUS_CODE result;
; 334  :     NUMBER_HEADER* nu = (NUMBER_HEADER*)u;

	mov	eax, DWORD PTR _u$[ebp]
	mov	DWORD PTR _nu$[ebp], eax

; 335  :     NUMBER_HEADER* nw;
; 336  :     if ((result = CheckNumber(nu)) != PMC_STATUS_OK)

	mov	eax, DWORD PTR _nu$[ebp]
	push	eax
	call	_CheckNumber
	add	esp, 4
	mov	DWORD PTR _result$[ebp], eax
	cmp	DWORD PTR _result$[ebp], 0
	je	SHORT $LN4@PMC_Multip

; 337  :         return (result);

	mov	eax, DWORD PTR _result$[ebp]
	jmp	$LN1@PMC_Multip
$LN4@PMC_Multip:

; 338  :     char v_sign;
; 339  :     _UINT64_T v_abs = GET_ABS_64(v, &v_sign);

	lea	eax, DWORD PTR _v_sign$[ebp]
	push	eax
	mov	ecx, DWORD PTR _v$[ebp+4]
	push	ecx
	mov	edx, DWORD PTR _v$[ebp]
	push	edx
	call	_GET_ABS_64
	add	esp, 12					; 0000000cH
	mov	DWORD PTR _v_abs$[ebp], eax
	mov	DWORD PTR _v_abs$[ebp+4], edx

; 340  :     if (nu->SIGN == 0)

	mov	eax, DWORD PTR _nu$[ebp]
	movsx	ecx, BYTE PTR [eax+16]
	test	ecx, ecx
	jne	SHORT $LN5@PMC_Multip

; 341  :     {
; 342  :         // u == 0 の場合
; 343  : 
; 344  :         // 0 を返す
; 345  :         nw = &number_zero;

	mov	DWORD PTR _nw$[ebp], OFFSET _number_zero

; 346  :     }

	jmp	$LN6@PMC_Multip
$LN5@PMC_Multip:

; 347  :     else if (nu->SIGN > 0)

	mov	eax, DWORD PTR _nu$[ebp]
	movsx	ecx, BYTE PTR [eax+16]
	test	ecx, ecx
	jle	SHORT $LN7@PMC_Multip

; 348  :     {
; 349  :         // u > 0 の場合
; 350  : 
; 351  :         if (v_sign == 0)

	movsx	eax, BYTE PTR _v_sign$[ebp]
	test	eax, eax
	jne	SHORT $LN9@PMC_Multip

; 352  :         {
; 353  :             // v == 0 の場合
; 354  : 
; 355  :             // 0 を返す
; 356  :             nw = &number_zero;

	mov	DWORD PTR _nw$[ebp], OFFSET _number_zero

; 357  :         }

	jmp	SHORT $LN10@PMC_Multip
$LN9@PMC_Multip:

; 358  :         else
; 359  :         {
; 360  :             // v != 0 の場合
; 361  : 
; 362  :             // abs(u) * abs(v) を返す
; 363  :             if ((result = MultiplyU_X_L_Imp(v_sign, nu->ABS, v_abs, &nw)) != PMC_STATUS_OK)

	lea	eax, DWORD PTR _nw$[ebp]
	push	eax
	mov	ecx, DWORD PTR _v_abs$[ebp+4]
	push	ecx
	mov	edx, DWORD PTR _v_abs$[ebp]
	push	edx
	mov	eax, DWORD PTR _nu$[ebp]
	mov	ecx, DWORD PTR [eax+12]
	push	ecx
	movzx	edx, BYTE PTR _v_sign$[ebp]
	push	edx
	call	_MultiplyU_X_L_Imp
	add	esp, 20					; 00000014H
	mov	DWORD PTR _result$[ebp], eax
	cmp	DWORD PTR _result$[ebp], 0
	je	SHORT $LN10@PMC_Multip

; 364  :                 return (result);

	mov	eax, DWORD PTR _result$[ebp]
	jmp	SHORT $LN1@PMC_Multip
$LN10@PMC_Multip:

; 365  :         }
; 366  :     }

	jmp	SHORT $LN6@PMC_Multip
$LN7@PMC_Multip:

; 367  :     else
; 368  :     {
; 369  :         // u < 0 の場合
; 370  : 
; 371  :         if (v_sign == 0)

	movsx	eax, BYTE PTR _v_sign$[ebp]
	test	eax, eax
	jne	SHORT $LN12@PMC_Multip

; 372  :         {
; 373  :             // v == 0 の場合
; 374  : 
; 375  :             // 0 を返す
; 376  :             nw = &number_zero;

	mov	DWORD PTR _nw$[ebp], OFFSET _number_zero

; 377  :         }

	jmp	SHORT $LN6@PMC_Multip
$LN12@PMC_Multip:

; 378  :         else
; 379  :         {
; 380  :             // v != 0 の場合
; 381  : 
; 382  :             // -abs(u) * abs(v) を返す
; 383  :             if ((result = MultiplyU_X_L_Imp(-v_sign, nu->ABS, v_abs, &nw)) != PMC_STATUS_OK)

	lea	eax, DWORD PTR _nw$[ebp]
	push	eax
	mov	ecx, DWORD PTR _v_abs$[ebp+4]
	push	ecx
	mov	edx, DWORD PTR _v_abs$[ebp]
	push	edx
	mov	eax, DWORD PTR _nu$[ebp]
	mov	ecx, DWORD PTR [eax+12]
	push	ecx
	movsx	edx, BYTE PTR _v_sign$[ebp]
	neg	edx
	push	edx
	call	_MultiplyU_X_L_Imp
	add	esp, 20					; 00000014H
	mov	DWORD PTR _result$[ebp], eax
	cmp	DWORD PTR _result$[ebp], 0
	je	SHORT $LN6@PMC_Multip

; 384  :                 return (result);

	mov	eax, DWORD PTR _result$[ebp]
	jmp	SHORT $LN1@PMC_Multip
$LN6@PMC_Multip:

; 385  :         }
; 386  :     }
; 387  :     *w = (PMC_HANDLE_SINT)nw;

	mov	eax, DWORD PTR _w$[ebp]
	mov	ecx, DWORD PTR _nw$[ebp]
	mov	DWORD PTR [eax], ecx

; 388  :     return (PMC_STATUS_OK);

	xor	eax, eax
$LN1@PMC_Multip:

; 389  : }

	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN19@PMC_Multip
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	pop	edi
	pop	esi
	pop	ebx
	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	ecx, ebp
	call	@__security_check_cookie@4
	add	esp, 260				; 00000104H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	16					; 00000010H
	npad	2
$LN19@PMC_Multip:
	DD	2
	DD	$LN18@PMC_Multip
$LN18@PMC_Multip:
	DD	-36					; ffffffdcH
	DD	4
	DD	$LN16@PMC_Multip
	DD	-45					; ffffffd3H
	DD	1
	DD	$LN17@PMC_Multip
$LN17@PMC_Multip:
	DB	118					; 00000076H
	DB	95					; 0000005fH
	DB	115					; 00000073H
	DB	105					; 00000069H
	DB	103					; 00000067H
	DB	110					; 0000006eH
	DB	0
$LN16@PMC_Multip:
	DB	110					; 0000006eH
	DB	119					; 00000077H
	DB	0
_PMC_Multiply_X_L@16 ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.sint\palmtree.math.core.sint\pmc_multiply.c
;	COMDAT _PMC_Multiply_X_I@12
_TEXT	SEGMENT
_v_abs$ = -60						; size = 4
_v_sign$ = -45						; size = 1
_nw$ = -36						; size = 4
_nu$ = -24						; size = 4
_result$ = -12						; size = 4
__$ArrayPad$ = -4					; size = 4
_u$ = 8							; size = 4
_v$ = 12						; size = 4
_w$ = 16						; size = 4
_PMC_Multiply_X_I@12 PROC				; COMDAT

; 264  : {

	push	ebp
	mov	ebp, esp
	sub	esp, 256				; 00000100H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-256]
	mov	ecx, 64					; 00000040H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	mov	DWORD PTR __$ArrayPad$[ebp], eax
	mov	ecx, OFFSET __6265BA8B_pmc_multiply@c
	call	@__CheckForDebuggerJustMyCode@4

; 265  :     if (u == NULL)

	cmp	DWORD PTR _u$[ebp], 0
	jne	SHORT $LN2@PMC_Multip

; 266  :         return (PMC_STATUS_ARGUMENT_ERROR);

	or	eax, -1
	jmp	$LN1@PMC_Multip
$LN2@PMC_Multip:

; 267  :     if (w == NULL)

	cmp	DWORD PTR _w$[ebp], 0
	jne	SHORT $LN3@PMC_Multip

; 268  :         return (PMC_STATUS_ARGUMENT_ERROR);

	or	eax, -1
	jmp	$LN1@PMC_Multip
$LN3@PMC_Multip:

; 269  :     PMC_STATUS_CODE result;
; 270  :     NUMBER_HEADER* nu = (NUMBER_HEADER*)u;

	mov	eax, DWORD PTR _u$[ebp]
	mov	DWORD PTR _nu$[ebp], eax

; 271  :     NUMBER_HEADER* nw;
; 272  :     if ((result = CheckNumber(nu)) != PMC_STATUS_OK)

	mov	eax, DWORD PTR _nu$[ebp]
	push	eax
	call	_CheckNumber
	add	esp, 4
	mov	DWORD PTR _result$[ebp], eax
	cmp	DWORD PTR _result$[ebp], 0
	je	SHORT $LN4@PMC_Multip

; 273  :         return (result);

	mov	eax, DWORD PTR _result$[ebp]
	jmp	$LN1@PMC_Multip
$LN4@PMC_Multip:

; 274  :     char v_sign;
; 275  :     _UINT32_T v_abs = GET_ABS_32(v, &v_sign);

	lea	eax, DWORD PTR _v_sign$[ebp]
	push	eax
	mov	ecx, DWORD PTR _v$[ebp]
	push	ecx
	call	_GET_ABS_32
	add	esp, 8
	mov	DWORD PTR _v_abs$[ebp], eax

; 276  :     if (nu->SIGN == 0)

	mov	eax, DWORD PTR _nu$[ebp]
	movsx	ecx, BYTE PTR [eax+16]
	test	ecx, ecx
	jne	SHORT $LN5@PMC_Multip

; 277  :     {
; 278  :         // u == 0 の場合
; 279  : 
; 280  :         // 0 を返す
; 281  :         nw = &number_zero;

	mov	DWORD PTR _nw$[ebp], OFFSET _number_zero

; 282  :     }

	jmp	$LN6@PMC_Multip
$LN5@PMC_Multip:

; 283  :     else if (nu->SIGN > 0)

	mov	eax, DWORD PTR _nu$[ebp]
	movsx	ecx, BYTE PTR [eax+16]
	test	ecx, ecx
	jle	SHORT $LN7@PMC_Multip

; 284  :     {
; 285  :         // u > 0 の場合
; 286  : 
; 287  :         if (v_sign == 0)

	movsx	eax, BYTE PTR _v_sign$[ebp]
	test	eax, eax
	jne	SHORT $LN9@PMC_Multip

; 288  :         {
; 289  :             // v == 0 の場合
; 290  : 
; 291  :             // 0 を返す
; 292  :             nw = &number_zero;

	mov	DWORD PTR _nw$[ebp], OFFSET _number_zero

; 293  :         }

	jmp	SHORT $LN10@PMC_Multip
$LN9@PMC_Multip:

; 294  :         else
; 295  :         {
; 296  :             // v != 0 の場合
; 297  : 
; 298  :             // abs(u) * abs(v) を返す
; 299  :             if ((result = MultiplyU_X_I_Imp(v_sign, nu->ABS, v_abs, &nw)) != PMC_STATUS_OK)

	lea	eax, DWORD PTR _nw$[ebp]
	push	eax
	mov	ecx, DWORD PTR _v_abs$[ebp]
	push	ecx
	mov	edx, DWORD PTR _nu$[ebp]
	mov	eax, DWORD PTR [edx+12]
	push	eax
	movzx	ecx, BYTE PTR _v_sign$[ebp]
	push	ecx
	call	_MultiplyU_X_I_Imp
	add	esp, 16					; 00000010H
	mov	DWORD PTR _result$[ebp], eax
	cmp	DWORD PTR _result$[ebp], 0
	je	SHORT $LN10@PMC_Multip

; 300  :                 return (result);

	mov	eax, DWORD PTR _result$[ebp]
	jmp	SHORT $LN1@PMC_Multip
$LN10@PMC_Multip:

; 301  :         }
; 302  :     }

	jmp	SHORT $LN6@PMC_Multip
$LN7@PMC_Multip:

; 303  :     else
; 304  :     {
; 305  :         // u < 0 の場合
; 306  : 
; 307  :         if (v_sign == 0)

	movsx	eax, BYTE PTR _v_sign$[ebp]
	test	eax, eax
	jne	SHORT $LN12@PMC_Multip

; 308  :         {
; 309  :             // v == 0 の場合
; 310  : 
; 311  :             // 0 を返す
; 312  :             nw = &number_zero;

	mov	DWORD PTR _nw$[ebp], OFFSET _number_zero

; 313  :         }

	jmp	SHORT $LN6@PMC_Multip
$LN12@PMC_Multip:

; 314  :         else
; 315  :         {
; 316  :             // v != 0 の場合
; 317  : 
; 318  :             // -abs(u) * abs(v) を返す
; 319  :             if ((result = MultiplyU_X_I_Imp(-v_sign, nu->ABS, v_abs, &nw)) != PMC_STATUS_OK)

	lea	eax, DWORD PTR _nw$[ebp]
	push	eax
	mov	ecx, DWORD PTR _v_abs$[ebp]
	push	ecx
	mov	edx, DWORD PTR _nu$[ebp]
	mov	eax, DWORD PTR [edx+12]
	push	eax
	movsx	ecx, BYTE PTR _v_sign$[ebp]
	neg	ecx
	push	ecx
	call	_MultiplyU_X_I_Imp
	add	esp, 16					; 00000010H
	mov	DWORD PTR _result$[ebp], eax
	cmp	DWORD PTR _result$[ebp], 0
	je	SHORT $LN6@PMC_Multip

; 320  :                 return (result);

	mov	eax, DWORD PTR _result$[ebp]
	jmp	SHORT $LN1@PMC_Multip
$LN6@PMC_Multip:

; 321  :         }
; 322  :     }
; 323  :     *w = (PMC_HANDLE_SINT)nw;

	mov	eax, DWORD PTR _w$[ebp]
	mov	ecx, DWORD PTR _nw$[ebp]
	mov	DWORD PTR [eax], ecx

; 324  :     return (PMC_STATUS_OK);

	xor	eax, eax
$LN1@PMC_Multip:

; 325  : }

	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN19@PMC_Multip
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	pop	edi
	pop	esi
	pop	ebx
	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	ecx, ebp
	call	@__security_check_cookie@4
	add	esp, 256				; 00000100H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
	npad	1
$LN19@PMC_Multip:
	DD	2
	DD	$LN18@PMC_Multip
$LN18@PMC_Multip:
	DD	-36					; ffffffdcH
	DD	4
	DD	$LN16@PMC_Multip
	DD	-45					; ffffffd3H
	DD	1
	DD	$LN17@PMC_Multip
$LN17@PMC_Multip:
	DB	118					; 00000076H
	DB	95					; 0000005fH
	DB	115					; 00000073H
	DB	105					; 00000069H
	DB	103					; 00000067H
	DB	110					; 0000006eH
	DB	0
$LN16@PMC_Multip:
	DB	110					; 0000006eH
	DB	119					; 00000077H
	DB	0
_PMC_Multiply_X_I@12 ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.sint\palmtree.math.core.sint\pmc_multiply.c
;	COMDAT _PMC_Multiply_UX_X@12
_TEXT	SEGMENT
_nw$ = -36						; size = 4
_nv$ = -24						; size = 4
_result$ = -12						; size = 4
__$ArrayPad$ = -4					; size = 4
_u$ = 8							; size = 4
_v$ = 12						; size = 4
_w$ = 16						; size = 4
_PMC_Multiply_UX_X@12 PROC				; COMDAT

; 220  : {

	push	ebp
	mov	ebp, esp
	sub	esp, 232				; 000000e8H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-232]
	mov	ecx, 58					; 0000003aH
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	mov	DWORD PTR __$ArrayPad$[ebp], eax
	mov	ecx, OFFSET __6265BA8B_pmc_multiply@c
	call	@__CheckForDebuggerJustMyCode@4

; 221  :     if (u == NULL)

	cmp	DWORD PTR _u$[ebp], 0
	jne	SHORT $LN2@PMC_Multip

; 222  :         return (PMC_STATUS_ARGUMENT_ERROR);

	or	eax, -1
	jmp	$LN1@PMC_Multip
$LN2@PMC_Multip:

; 223  :     if (v == NULL)

	cmp	DWORD PTR _v$[ebp], 0
	jne	SHORT $LN3@PMC_Multip

; 224  :         return (PMC_STATUS_ARGUMENT_ERROR);

	or	eax, -1
	jmp	$LN1@PMC_Multip
$LN3@PMC_Multip:

; 225  :     if (w == NULL)

	cmp	DWORD PTR _w$[ebp], 0
	jne	SHORT $LN4@PMC_Multip

; 226  :         return (PMC_STATUS_ARGUMENT_ERROR);

	or	eax, -1
	jmp	SHORT $LN1@PMC_Multip
$LN4@PMC_Multip:

; 227  :     PMC_STATUS_CODE result;
; 228  :     NUMBER_HEADER* nv = (NUMBER_HEADER*)v;

	mov	eax, DWORD PTR _v$[ebp]
	mov	DWORD PTR _nv$[ebp], eax

; 229  :     NUMBER_HEADER* nw;
; 230  :     if ((result = CheckNumber(nv)) != PMC_STATUS_OK)

	mov	eax, DWORD PTR _nv$[ebp]
	push	eax
	call	_CheckNumber
	add	esp, 4
	mov	DWORD PTR _result$[ebp], eax
	cmp	DWORD PTR _result$[ebp], 0
	je	SHORT $LN5@PMC_Multip

; 231  :         return (result);

	mov	eax, DWORD PTR _result$[ebp]
	jmp	SHORT $LN1@PMC_Multip
$LN5@PMC_Multip:

; 232  :     if (u->FLAGS.IS_ZERO)

	mov	eax, DWORD PTR _u$[ebp]
	mov	ecx, DWORD PTR [eax]
	and	ecx, 1
	je	SHORT $LN6@PMC_Multip

; 233  :     {
; 234  :         // u == 0 の場合
; 235  : 
; 236  :         // 0 を返す
; 237  :         nw = &number_zero;

	mov	DWORD PTR _nw$[ebp], OFFSET _number_zero

; 238  :     }

	jmp	SHORT $LN7@PMC_Multip
$LN6@PMC_Multip:

; 239  :     else
; 240  :     {
; 241  :         // u > 0 の場合
; 242  : 
; 243  :         if (nv->SIGN == 0)

	mov	eax, DWORD PTR _nv$[ebp]
	movsx	ecx, BYTE PTR [eax+16]
	test	ecx, ecx
	jne	SHORT $LN8@PMC_Multip

; 244  :         {
; 245  :             // v == 0 の場合
; 246  : 
; 247  :             // 0 を返す
; 248  :             nw = &number_zero;

	mov	DWORD PTR _nw$[ebp], OFFSET _number_zero

; 249  :         }

	jmp	SHORT $LN7@PMC_Multip
$LN8@PMC_Multip:

; 250  :         else
; 251  :         {
; 252  :             // u != 0 の場合
; 253  : 
; 254  :             // abs(u) * v を返す
; 255  :             if ((result = MultiplyU_X_X_Imp(nv->SIGN, nv->ABS, u, &nw)) != PMC_STATUS_OK)

	lea	eax, DWORD PTR _nw$[ebp]
	push	eax
	mov	ecx, DWORD PTR _u$[ebp]
	push	ecx
	mov	edx, DWORD PTR _nv$[ebp]
	mov	eax, DWORD PTR [edx+12]
	push	eax
	mov	ecx, DWORD PTR _nv$[ebp]
	movzx	edx, BYTE PTR [ecx+16]
	push	edx
	call	_MultiplyU_X_X_Imp
	add	esp, 16					; 00000010H
	mov	DWORD PTR _result$[ebp], eax
	cmp	DWORD PTR _result$[ebp], 0
	je	SHORT $LN7@PMC_Multip

; 256  :                 return (result);

	mov	eax, DWORD PTR _result$[ebp]
	jmp	SHORT $LN1@PMC_Multip
$LN7@PMC_Multip:

; 257  :         }
; 258  :     }
; 259  :     *w = (PMC_HANDLE_SINT)nw;

	mov	eax, DWORD PTR _w$[ebp]
	mov	ecx, DWORD PTR _nw$[ebp]
	mov	DWORD PTR [eax], ecx

; 260  :     return (PMC_STATUS_OK);

	xor	eax, eax
$LN1@PMC_Multip:

; 261  : }

	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN14@PMC_Multip
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	pop	edi
	pop	esi
	pop	ebx
	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	ecx, ebp
	call	@__security_check_cookie@4
	add	esp, 232				; 000000e8H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
$LN14@PMC_Multip:
	DD	1
	DD	$LN13@PMC_Multip
$LN13@PMC_Multip:
	DD	-36					; ffffffdcH
	DD	4
	DD	$LN12@PMC_Multip
$LN12@PMC_Multip:
	DB	110					; 0000006eH
	DB	119					; 00000077H
	DB	0
_PMC_Multiply_UX_X@12 ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.sint\palmtree.math.core.sint\pmc_multiply.c
;	COMDAT _PMC_Multiply_L_X@16
_TEXT	SEGMENT
_u_abs$ = -64						; size = 8
_u_sign$ = -45						; size = 1
_nw$ = -36						; size = 4
_nv$ = -24						; size = 4
_result$ = -12						; size = 4
__$ArrayPad$ = -4					; size = 4
_u$ = 8							; size = 8
_v$ = 16						; size = 4
_w$ = 20						; size = 4
_PMC_Multiply_L_X@16 PROC				; COMDAT

; 156  : {

	push	ebp
	mov	ebp, esp
	sub	esp, 260				; 00000104H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-260]
	mov	ecx, 65					; 00000041H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	mov	DWORD PTR __$ArrayPad$[ebp], eax
	mov	ecx, OFFSET __6265BA8B_pmc_multiply@c
	call	@__CheckForDebuggerJustMyCode@4

; 157  :     if (v == NULL)

	cmp	DWORD PTR _v$[ebp], 0
	jne	SHORT $LN2@PMC_Multip

; 158  :         return (PMC_STATUS_ARGUMENT_ERROR);

	or	eax, -1
	jmp	$LN1@PMC_Multip
$LN2@PMC_Multip:

; 159  :     if (w == NULL)

	cmp	DWORD PTR _w$[ebp], 0
	jne	SHORT $LN3@PMC_Multip

; 160  :         return (PMC_STATUS_ARGUMENT_ERROR);

	or	eax, -1
	jmp	$LN1@PMC_Multip
$LN3@PMC_Multip:

; 161  :     PMC_STATUS_CODE result;
; 162  :     NUMBER_HEADER* nv = (NUMBER_HEADER*)v;

	mov	eax, DWORD PTR _v$[ebp]
	mov	DWORD PTR _nv$[ebp], eax

; 163  :     NUMBER_HEADER* nw;
; 164  :     if ((result = CheckNumber(nv)) != PMC_STATUS_OK)

	mov	eax, DWORD PTR _nv$[ebp]
	push	eax
	call	_CheckNumber
	add	esp, 4
	mov	DWORD PTR _result$[ebp], eax
	cmp	DWORD PTR _result$[ebp], 0
	je	SHORT $LN4@PMC_Multip

; 165  :         return (result);

	mov	eax, DWORD PTR _result$[ebp]
	jmp	$LN1@PMC_Multip
$LN4@PMC_Multip:

; 166  :     char u_sign;
; 167  :     _UINT64_T u_abs = GET_ABS_64(u, &u_sign);

	lea	eax, DWORD PTR _u_sign$[ebp]
	push	eax
	mov	ecx, DWORD PTR _u$[ebp+4]
	push	ecx
	mov	edx, DWORD PTR _u$[ebp]
	push	edx
	call	_GET_ABS_64
	add	esp, 12					; 0000000cH
	mov	DWORD PTR _u_abs$[ebp], eax
	mov	DWORD PTR _u_abs$[ebp+4], edx

; 168  :     if (u_sign == 0)

	movsx	eax, BYTE PTR _u_sign$[ebp]
	test	eax, eax
	jne	SHORT $LN5@PMC_Multip

; 169  :     {
; 170  :         // u == 0 の場合
; 171  : 
; 172  :         // 0 を返す
; 173  :         nw = &number_zero;

	mov	DWORD PTR _nw$[ebp], OFFSET _number_zero

; 174  :     }

	jmp	$LN6@PMC_Multip
$LN5@PMC_Multip:

; 175  :     else if (u_sign > 0)

	movsx	eax, BYTE PTR _u_sign$[ebp]
	test	eax, eax
	jle	SHORT $LN7@PMC_Multip

; 176  :     {
; 177  :         // u > 0 の場合
; 178  : 
; 179  :         if (nv->SIGN == 0)

	mov	eax, DWORD PTR _nv$[ebp]
	movsx	ecx, BYTE PTR [eax+16]
	test	ecx, ecx
	jne	SHORT $LN9@PMC_Multip

; 180  :         {
; 181  :             // v == 0 の場合
; 182  : 
; 183  :             // 0 を返す
; 184  :             nw = &number_zero;

	mov	DWORD PTR _nw$[ebp], OFFSET _number_zero

; 185  :         }

	jmp	SHORT $LN10@PMC_Multip
$LN9@PMC_Multip:

; 186  :         else
; 187  :         {
; 188  :             // v != 0 の場合
; 189  : 
; 190  :             // abs(u) * v を返す
; 191  :             if ((result = MultiplyU_X_L_Imp(nv->SIGN, nv->ABS, u_abs, &nw)) != PMC_STATUS_OK)

	lea	eax, DWORD PTR _nw$[ebp]
	push	eax
	mov	ecx, DWORD PTR _u_abs$[ebp+4]
	push	ecx
	mov	edx, DWORD PTR _u_abs$[ebp]
	push	edx
	mov	eax, DWORD PTR _nv$[ebp]
	mov	ecx, DWORD PTR [eax+12]
	push	ecx
	mov	edx, DWORD PTR _nv$[ebp]
	movzx	eax, BYTE PTR [edx+16]
	push	eax
	call	_MultiplyU_X_L_Imp
	add	esp, 20					; 00000014H
	mov	DWORD PTR _result$[ebp], eax
	cmp	DWORD PTR _result$[ebp], 0
	je	SHORT $LN10@PMC_Multip

; 192  :                 return (result);

	mov	eax, DWORD PTR _result$[ebp]
	jmp	SHORT $LN1@PMC_Multip
$LN10@PMC_Multip:

; 193  :         }
; 194  :     }

	jmp	SHORT $LN6@PMC_Multip
$LN7@PMC_Multip:

; 195  :     else
; 196  :     {
; 197  :         // u < 0 の場合
; 198  : 
; 199  :         if (nv->SIGN == 0)

	mov	eax, DWORD PTR _nv$[ebp]
	movsx	ecx, BYTE PTR [eax+16]
	test	ecx, ecx
	jne	SHORT $LN12@PMC_Multip

; 200  :         {
; 201  :             // v == 0 の場合
; 202  : 
; 203  :             // 0 を返す
; 204  :             nw = &number_zero;

	mov	DWORD PTR _nw$[ebp], OFFSET _number_zero

; 205  :         }

	jmp	SHORT $LN6@PMC_Multip
$LN12@PMC_Multip:

; 206  :         else
; 207  :         {
; 208  :             // v != 0 の場合
; 209  : 
; 210  :             // -abs(u) * v を返す
; 211  :             if ((result = MultiplyU_X_L_Imp(-nv->SIGN, nv->ABS, u_abs, &nw)) != PMC_STATUS_OK)

	lea	eax, DWORD PTR _nw$[ebp]
	push	eax
	mov	ecx, DWORD PTR _u_abs$[ebp+4]
	push	ecx
	mov	edx, DWORD PTR _u_abs$[ebp]
	push	edx
	mov	eax, DWORD PTR _nv$[ebp]
	mov	ecx, DWORD PTR [eax+12]
	push	ecx
	mov	edx, DWORD PTR _nv$[ebp]
	movsx	eax, BYTE PTR [edx+16]
	neg	eax
	push	eax
	call	_MultiplyU_X_L_Imp
	add	esp, 20					; 00000014H
	mov	DWORD PTR _result$[ebp], eax
	cmp	DWORD PTR _result$[ebp], 0
	je	SHORT $LN6@PMC_Multip

; 212  :                 return (result);

	mov	eax, DWORD PTR _result$[ebp]
	jmp	SHORT $LN1@PMC_Multip
$LN6@PMC_Multip:

; 213  :         }
; 214  :     }
; 215  :     *w = (PMC_HANDLE_SINT)nw;

	mov	eax, DWORD PTR _w$[ebp]
	mov	ecx, DWORD PTR _nw$[ebp]
	mov	DWORD PTR [eax], ecx

; 216  :     return (PMC_STATUS_OK);

	xor	eax, eax
$LN1@PMC_Multip:

; 217  : }

	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN19@PMC_Multip
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	pop	edi
	pop	esi
	pop	ebx
	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	ecx, ebp
	call	@__security_check_cookie@4
	add	esp, 260				; 00000104H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	16					; 00000010H
$LN19@PMC_Multip:
	DD	2
	DD	$LN18@PMC_Multip
$LN18@PMC_Multip:
	DD	-36					; ffffffdcH
	DD	4
	DD	$LN16@PMC_Multip
	DD	-45					; ffffffd3H
	DD	1
	DD	$LN17@PMC_Multip
$LN17@PMC_Multip:
	DB	117					; 00000075H
	DB	95					; 0000005fH
	DB	115					; 00000073H
	DB	105					; 00000069H
	DB	103					; 00000067H
	DB	110					; 0000006eH
	DB	0
$LN16@PMC_Multip:
	DB	110					; 0000006eH
	DB	119					; 00000077H
	DB	0
_PMC_Multiply_L_X@16 ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.sint\palmtree.math.core.sint\pmc_multiply.c
;	COMDAT _PMC_Multiply_I_X@12
_TEXT	SEGMENT
_u_abs$ = -60						; size = 4
_u_sign$ = -45						; size = 1
_nw$ = -36						; size = 4
_nv$ = -24						; size = 4
_result$ = -12						; size = 4
__$ArrayPad$ = -4					; size = 4
_u$ = 8							; size = 4
_v$ = 12						; size = 4
_w$ = 16						; size = 4
_PMC_Multiply_I_X@12 PROC				; COMDAT

; 92   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 256				; 00000100H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-256]
	mov	ecx, 64					; 00000040H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	mov	DWORD PTR __$ArrayPad$[ebp], eax
	mov	ecx, OFFSET __6265BA8B_pmc_multiply@c
	call	@__CheckForDebuggerJustMyCode@4

; 93   :     if (v == NULL)

	cmp	DWORD PTR _v$[ebp], 0
	jne	SHORT $LN2@PMC_Multip

; 94   :         return (PMC_STATUS_ARGUMENT_ERROR);

	or	eax, -1
	jmp	$LN1@PMC_Multip
$LN2@PMC_Multip:

; 95   :     if (w == NULL)

	cmp	DWORD PTR _w$[ebp], 0
	jne	SHORT $LN3@PMC_Multip

; 96   :         return (PMC_STATUS_ARGUMENT_ERROR);

	or	eax, -1
	jmp	$LN1@PMC_Multip
$LN3@PMC_Multip:

; 97   :     PMC_STATUS_CODE result;
; 98   :     NUMBER_HEADER* nv = (NUMBER_HEADER*)v;

	mov	eax, DWORD PTR _v$[ebp]
	mov	DWORD PTR _nv$[ebp], eax

; 99   :     NUMBER_HEADER* nw;
; 100  :     if ((result = CheckNumber(nv)) != PMC_STATUS_OK)

	mov	eax, DWORD PTR _nv$[ebp]
	push	eax
	call	_CheckNumber
	add	esp, 4
	mov	DWORD PTR _result$[ebp], eax
	cmp	DWORD PTR _result$[ebp], 0
	je	SHORT $LN4@PMC_Multip

; 101  :         return (result);

	mov	eax, DWORD PTR _result$[ebp]
	jmp	$LN1@PMC_Multip
$LN4@PMC_Multip:

; 102  :     char u_sign;
; 103  :     _UINT32_T u_abs = GET_ABS_32(u, &u_sign);

	lea	eax, DWORD PTR _u_sign$[ebp]
	push	eax
	mov	ecx, DWORD PTR _u$[ebp]
	push	ecx
	call	_GET_ABS_32
	add	esp, 8
	mov	DWORD PTR _u_abs$[ebp], eax

; 104  :     if (u_sign == 0)

	movsx	eax, BYTE PTR _u_sign$[ebp]
	test	eax, eax
	jne	SHORT $LN5@PMC_Multip

; 105  :     {
; 106  :         // u == 0 の場合
; 107  : 
; 108  :         // 0 を返す
; 109  :         nw = &number_zero;

	mov	DWORD PTR _nw$[ebp], OFFSET _number_zero

; 110  :     }

	jmp	$LN6@PMC_Multip
$LN5@PMC_Multip:

; 111  :     else if (u_sign > 0)

	movsx	eax, BYTE PTR _u_sign$[ebp]
	test	eax, eax
	jle	SHORT $LN7@PMC_Multip

; 112  :     {
; 113  :         // u > 0 の場合
; 114  : 
; 115  :         if (nv->SIGN == 0)

	mov	eax, DWORD PTR _nv$[ebp]
	movsx	ecx, BYTE PTR [eax+16]
	test	ecx, ecx
	jne	SHORT $LN9@PMC_Multip

; 116  :         {
; 117  :             // v == 0 の場合
; 118  : 
; 119  :             // 0 を返す
; 120  :             nw = &number_zero;

	mov	DWORD PTR _nw$[ebp], OFFSET _number_zero

; 121  :         }

	jmp	SHORT $LN10@PMC_Multip
$LN9@PMC_Multip:

; 122  :         else
; 123  :         {
; 124  :             // v != 0 の場合
; 125  : 
; 126  :             // abs(u) * v を返す
; 127  :             if ((result = MultiplyU_X_I_Imp(nv->SIGN, nv->ABS, u_abs, &nw)) != PMC_STATUS_OK)

	lea	eax, DWORD PTR _nw$[ebp]
	push	eax
	mov	ecx, DWORD PTR _u_abs$[ebp]
	push	ecx
	mov	edx, DWORD PTR _nv$[ebp]
	mov	eax, DWORD PTR [edx+12]
	push	eax
	mov	ecx, DWORD PTR _nv$[ebp]
	movzx	edx, BYTE PTR [ecx+16]
	push	edx
	call	_MultiplyU_X_I_Imp
	add	esp, 16					; 00000010H
	mov	DWORD PTR _result$[ebp], eax
	cmp	DWORD PTR _result$[ebp], 0
	je	SHORT $LN10@PMC_Multip

; 128  :                 return (result);

	mov	eax, DWORD PTR _result$[ebp]
	jmp	SHORT $LN1@PMC_Multip
$LN10@PMC_Multip:

; 129  :         }
; 130  :     }

	jmp	SHORT $LN6@PMC_Multip
$LN7@PMC_Multip:

; 131  :     else
; 132  :     {
; 133  :         // u < 0 の場合
; 134  : 
; 135  :         if (nv->SIGN == 0)

	mov	eax, DWORD PTR _nv$[ebp]
	movsx	ecx, BYTE PTR [eax+16]
	test	ecx, ecx
	jne	SHORT $LN12@PMC_Multip

; 136  :         {
; 137  :             // v == 0 の場合
; 138  : 
; 139  :             // 0 を返す
; 140  :             nw = &number_zero;

	mov	DWORD PTR _nw$[ebp], OFFSET _number_zero

; 141  :         }

	jmp	SHORT $LN6@PMC_Multip
$LN12@PMC_Multip:

; 142  :         else
; 143  :         {
; 144  :             // v != 0 の場合
; 145  : 
; 146  :             // -abs(u) * v を返す
; 147  :             if ((result = MultiplyU_X_I_Imp(-nv->SIGN, nv->ABS, u_abs, &nw)) != PMC_STATUS_OK)

	lea	eax, DWORD PTR _nw$[ebp]
	push	eax
	mov	ecx, DWORD PTR _u_abs$[ebp]
	push	ecx
	mov	edx, DWORD PTR _nv$[ebp]
	mov	eax, DWORD PTR [edx+12]
	push	eax
	mov	ecx, DWORD PTR _nv$[ebp]
	movsx	edx, BYTE PTR [ecx+16]
	neg	edx
	push	edx
	call	_MultiplyU_X_I_Imp
	add	esp, 16					; 00000010H
	mov	DWORD PTR _result$[ebp], eax
	cmp	DWORD PTR _result$[ebp], 0
	je	SHORT $LN6@PMC_Multip

; 148  :                 return (result);

	mov	eax, DWORD PTR _result$[ebp]
	jmp	SHORT $LN1@PMC_Multip
$LN6@PMC_Multip:

; 149  :         }
; 150  :     }
; 151  :     *w = (PMC_HANDLE_SINT)nw;

	mov	eax, DWORD PTR _w$[ebp]
	mov	ecx, DWORD PTR _nw$[ebp]
	mov	DWORD PTR [eax], ecx

; 152  :     return (PMC_STATUS_OK);

	xor	eax, eax
$LN1@PMC_Multip:

; 153  : }

	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN19@PMC_Multip
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	pop	edi
	pop	esi
	pop	ebx
	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	ecx, ebp
	call	@__security_check_cookie@4
	add	esp, 256				; 00000100H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
	npad	3
$LN19@PMC_Multip:
	DD	2
	DD	$LN18@PMC_Multip
$LN18@PMC_Multip:
	DD	-36					; ffffffdcH
	DD	4
	DD	$LN16@PMC_Multip
	DD	-45					; ffffffd3H
	DD	1
	DD	$LN17@PMC_Multip
$LN17@PMC_Multip:
	DB	117					; 00000075H
	DB	95					; 0000005fH
	DB	115					; 00000073H
	DB	105					; 00000069H
	DB	103					; 00000067H
	DB	110					; 0000006eH
	DB	0
$LN16@PMC_Multip:
	DB	110					; 0000006eH
	DB	119					; 00000077H
	DB	0
_PMC_Multiply_I_X@12 ENDP
_TEXT	ENDS
END
