; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27026.1 

	TITLE	Z:\Sources\Lunor\Repos\rougemeilland\Palmtree.Math.Core.Sint\Palmtree.Math.Core.Sint\TEST_op_Subtruct.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

_DATA	SEGMENT
COMM	_uint_number_zero:DWORD
COMM	_uint_number_one:DWORD
_DATA	ENDS
msvcjmc	SEGMENT
__7B7A869E_ctype@h DB 01H
__457DD326_basetsd@h DB 01H
__4384A2D9_corecrt_memcpy_s@h DB 01H
__4E51A221_corecrt_wstring@h DB 01H
__2140C079_string@h DB 01H
__1887E595_winnt@h DB 01H
__9FC7C64B_processthreadsapi@h DB 01H
__FA470AEC_memoryapi@h DB 01H
__F37DAFF1_winerror@h DB 01H
__7A450CCC_winbase@h DB 01H
__B4B40122_winioctl@h DB 01H
__86261D59_stralign@h DB 01H
__059414E1_pmc_sint_debug@h DB 01H
__433B2F9A_test_op_subtruct@c DB 01H
msvcjmc	ENDS
PUBLIC	_TEST_Subtruct_I_X
PUBLIC	_TEST_Subtruct_L_X
PUBLIC	_TEST_Subtruct_UX_X
PUBLIC	_TEST_Subtruct_X_I
PUBLIC	_TEST_Subtruct_X_L
PUBLIC	_TEST_Subtruct_X_UX
PUBLIC	_TEST_Subtruct_X_X
PUBLIC	__JustMyCode_Default
PUBLIC	??_C@_1EC@NPMCAPKO@?$AAF?$AAr?$AAo?$AAm?$AAB?$AAy?$AAt?$AAe?$AAA?$AAr?$AAr?$AAa?$AAy?$AAn?$PP?$KJ@ ; `string'
PUBLIC	??_C@_1CK@JEFCPOGB@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAI?$AA_?$AAX?$AA?5?$AA?$CI?$AA?$CF@ ; `string'
PUBLIC	??_C@_1EA@NGKGKFPL@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAI?$AA_?$AAX?$AAn?$PP?$KJ?$AA0@ ; `string'
PUBLIC	??_C@_1DO@DOHJEMND@?$AAT?$AAo?$AAB?$AAy?$AAt?$AAe?$AAA?$AAr?$AAr?$AAa?$AAy?$AAn?$PP?$KJ?$AA0?$PP?$LD@ ; `string'
PUBLIC	??_C@_1BK@CBDJCOBM@?$PP?G?$PP?$PM?$PP?$LP?$AAn?$PP?$IF?$PP?$LJ?$AAL?$AA?$AA?$PP?t?$AAW?$AAj?$AAD@ ; `string'
PUBLIC	??_C@_1CK@HMHBAFBJ@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAL?$AA_?$AAX?$AA?5?$AA?$CI?$AA?$CF@ ; `string'
PUBLIC	??_C@_1EA@INDIFGGF@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAL?$AA_?$AAX?$AAn?$PP?$KJ?$AA0@ ; `string'
PUBLIC	??_C@_1CM@JOAGBAMJ@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAU?$AAX?$AA_?$AAX?$AA?5?$AA?$CI@ ; `string'
PUBLIC	??_C@_1EC@MMAEFCND@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAU?$AAX?$AA_?$AAX?$AAn?$PP?$KJ@ ; `string'
PUBLIC	??_C@_1CK@OPLNHEBI@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAX?$AA_?$AAI?$AA?5?$AA?$CI?$AA?$CF@ ; `string'
PUBLIC	??_C@_1EA@IKDNHDNM@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAX?$AA_?$AAI?$AAn?$PP?$KJ?$AA0@ ; `string'
PUBLIC	??_C@_1CK@MEDHKEAH@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAX?$AA_?$AAL?$AA?5?$AA?$CI?$AA?$CF@ ; `string'
PUBLIC	??_C@_1EA@MCHBOOEJ@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAX?$AA_?$AAL?$AAn?$PP?$KJ?$AA0@ ; `string'
PUBLIC	??_C@_1CM@KAKNNFML@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAX?$AA_?$AAU?$AAX?$AA?5?$AA?$CI@ ; `string'
PUBLIC	??_C@_1EC@ELOBBMPD@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAX?$AA_?$AAU?$AAX?$AAn?$PP?$KJ@ ; `string'
PUBLIC	??_C@_1CK@GKBMOEHL@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAX?$AA_?$AAX?$AA?5?$AA?$CI?$AA?$CF@ ; `string'
PUBLIC	??_C@_1EA@DIDCJOFM@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAX?$AA_?$AAX?$AAn?$PP?$KJ?$AA0@ ; `string'
EXTRN	_TEST_Assert:PROC
EXTRN	_FormatTestLabel:PROC
EXTRN	_FormatTestMesssage:PROC
EXTRN	@_RTC_CheckStackVars@8:PROC
EXTRN	@__CheckForDebuggerJustMyCode@4:PROC
EXTRN	@__security_check_cookie@4:PROC
EXTRN	__RTC_CheckEsp:PROC
EXTRN	__RTC_InitBase:PROC
EXTRN	__RTC_Shutdown:PROC
EXTRN	___security_cookie:DWORD
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
rtc$IMZ	ENDS
;	COMDAT ??_C@_1EA@DIDCJOFM@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAX?$AA_?$AAX?$AAn?$PP?$KJ?$AA0@
CONST	SEGMENT
??_C@_1EA@DIDCJOFM@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAX?$AA_?$AAX?$AAn?$PP?$KJ?$AA0@ DB 'S'
	DB	00H, 'u', 00H, 'b', 00H, 't', 00H, 'r', 00H, 'u', 00H, 'c', 00H
	DB	't', 00H, '_', 00H, 'X', 00H, '_', 00H, 'X', 00H, 'n0', 0a9H, '_'
	DB	'0^', 0b3H, '0', 0fcH, '0', 0c9H, '0L0', 01fH, 'g', 085H, '_', 01aH
	DB	090H, 08aH, '0g0o0j0D0(', 00H, '%', 00H, 'd', 00H, ')', 00H, 00H
	DB	00H						; `string'
CONST	ENDS
;	COMDAT ??_C@_1CK@GKBMOEHL@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAX?$AA_?$AAX?$AA?5?$AA?$CI?$AA?$CF@
CONST	SEGMENT
??_C@_1CK@GKBMOEHL@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAX?$AA_?$AAX?$AA?5?$AA?$CI?$AA?$CF@ DB 'S'
	DB	00H, 'u', 00H, 'b', 00H, 't', 00H, 'r', 00H, 'u', 00H, 'c', 00H
	DB	't', 00H, '_', 00H, 'X', 00H, '_', 00H, 'X', 00H, ' ', 00H, '('
	DB	00H, '%', 00H, 'd', 00H, '.', 00H, '%', 00H, 'd', 00H, ')', 00H
	DB	00H, 00H					; `string'
CONST	ENDS
;	COMDAT ??_C@_1EC@ELOBBMPD@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAX?$AA_?$AAU?$AAX?$AAn?$PP?$KJ@
CONST	SEGMENT
??_C@_1EC@ELOBBMPD@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAX?$AA_?$AAU?$AAX?$AAn?$PP?$KJ@ DB 'S'
	DB	00H, 'u', 00H, 'b', 00H, 't', 00H, 'r', 00H, 'u', 00H, 'c', 00H
	DB	't', 00H, '_', 00H, 'X', 00H, '_', 00H, 'U', 00H, 'X', 00H, 'n'
	DB	'0', 0a9H, '_0^', 0b3H, '0', 0fcH, '0', 0c9H, '0L0', 01fH, 'g', 085H
	DB	'_', 01aH, 090H, 08aH, '0g0o0j0D0(', 00H, '%', 00H, 'd', 00H, ')'
	DB	00H, 00H, 00H				; `string'
CONST	ENDS
;	COMDAT ??_C@_1CM@KAKNNFML@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAX?$AA_?$AAU?$AAX?$AA?5?$AA?$CI@
CONST	SEGMENT
??_C@_1CM@KAKNNFML@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAX?$AA_?$AAU?$AAX?$AA?5?$AA?$CI@ DB 'S'
	DB	00H, 'u', 00H, 'b', 00H, 't', 00H, 'r', 00H, 'u', 00H, 'c', 00H
	DB	't', 00H, '_', 00H, 'X', 00H, '_', 00H, 'U', 00H, 'X', 00H, ' '
	DB	00H, '(', 00H, '%', 00H, 'd', 00H, '.', 00H, '%', 00H, 'd', 00H
	DB	')', 00H, 00H, 00H				; `string'
CONST	ENDS
;	COMDAT ??_C@_1EA@MCHBOOEJ@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAX?$AA_?$AAL?$AAn?$PP?$KJ?$AA0@
CONST	SEGMENT
??_C@_1EA@MCHBOOEJ@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAX?$AA_?$AAL?$AAn?$PP?$KJ?$AA0@ DB 'S'
	DB	00H, 'u', 00H, 'b', 00H, 't', 00H, 'r', 00H, 'u', 00H, 'c', 00H
	DB	't', 00H, '_', 00H, 'X', 00H, '_', 00H, 'L', 00H, 'n0', 0a9H, '_'
	DB	'0^', 0b3H, '0', 0fcH, '0', 0c9H, '0L0', 01fH, 'g', 085H, '_', 01aH
	DB	090H, 08aH, '0g0o0j0D0(', 00H, '%', 00H, 'd', 00H, ')', 00H, 00H
	DB	00H						; `string'
CONST	ENDS
;	COMDAT ??_C@_1CK@MEDHKEAH@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAX?$AA_?$AAL?$AA?5?$AA?$CI?$AA?$CF@
CONST	SEGMENT
??_C@_1CK@MEDHKEAH@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAX?$AA_?$AAL?$AA?5?$AA?$CI?$AA?$CF@ DB 'S'
	DB	00H, 'u', 00H, 'b', 00H, 't', 00H, 'r', 00H, 'u', 00H, 'c', 00H
	DB	't', 00H, '_', 00H, 'X', 00H, '_', 00H, 'L', 00H, ' ', 00H, '('
	DB	00H, '%', 00H, 'd', 00H, '.', 00H, '%', 00H, 'd', 00H, ')', 00H
	DB	00H, 00H					; `string'
CONST	ENDS
;	COMDAT ??_C@_1EA@IKDNHDNM@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAX?$AA_?$AAI?$AAn?$PP?$KJ?$AA0@
CONST	SEGMENT
??_C@_1EA@IKDNHDNM@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAX?$AA_?$AAI?$AAn?$PP?$KJ?$AA0@ DB 'S'
	DB	00H, 'u', 00H, 'b', 00H, 't', 00H, 'r', 00H, 'u', 00H, 'c', 00H
	DB	't', 00H, '_', 00H, 'X', 00H, '_', 00H, 'I', 00H, 'n0', 0a9H, '_'
	DB	'0^', 0b3H, '0', 0fcH, '0', 0c9H, '0L0', 01fH, 'g', 085H, '_', 01aH
	DB	090H, 08aH, '0g0o0j0D0(', 00H, '%', 00H, 'd', 00H, ')', 00H, 00H
	DB	00H						; `string'
CONST	ENDS
;	COMDAT ??_C@_1CK@OPLNHEBI@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAX?$AA_?$AAI?$AA?5?$AA?$CI?$AA?$CF@
CONST	SEGMENT
??_C@_1CK@OPLNHEBI@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAX?$AA_?$AAI?$AA?5?$AA?$CI?$AA?$CF@ DB 'S'
	DB	00H, 'u', 00H, 'b', 00H, 't', 00H, 'r', 00H, 'u', 00H, 'c', 00H
	DB	't', 00H, '_', 00H, 'X', 00H, '_', 00H, 'I', 00H, ' ', 00H, '('
	DB	00H, '%', 00H, 'd', 00H, '.', 00H, '%', 00H, 'd', 00H, ')', 00H
	DB	00H, 00H					; `string'
CONST	ENDS
;	COMDAT ??_C@_1EC@MMAEFCND@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAU?$AAX?$AA_?$AAX?$AAn?$PP?$KJ@
CONST	SEGMENT
??_C@_1EC@MMAEFCND@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAU?$AAX?$AA_?$AAX?$AAn?$PP?$KJ@ DB 'S'
	DB	00H, 'u', 00H, 'b', 00H, 't', 00H, 'r', 00H, 'u', 00H, 'c', 00H
	DB	't', 00H, '_', 00H, 'U', 00H, 'X', 00H, '_', 00H, 'X', 00H, 'n'
	DB	'0', 0a9H, '_0^', 0b3H, '0', 0fcH, '0', 0c9H, '0L0', 01fH, 'g', 085H
	DB	'_', 01aH, 090H, 08aH, '0g0o0j0D0(', 00H, '%', 00H, 'd', 00H, ')'
	DB	00H, 00H, 00H				; `string'
CONST	ENDS
;	COMDAT ??_C@_1CM@JOAGBAMJ@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAU?$AAX?$AA_?$AAX?$AA?5?$AA?$CI@
CONST	SEGMENT
??_C@_1CM@JOAGBAMJ@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAU?$AAX?$AA_?$AAX?$AA?5?$AA?$CI@ DB 'S'
	DB	00H, 'u', 00H, 'b', 00H, 't', 00H, 'r', 00H, 'u', 00H, 'c', 00H
	DB	't', 00H, '_', 00H, 'U', 00H, 'X', 00H, '_', 00H, 'X', 00H, ' '
	DB	00H, '(', 00H, '%', 00H, 'd', 00H, '.', 00H, '%', 00H, 'd', 00H
	DB	')', 00H, 00H, 00H				; `string'
CONST	ENDS
;	COMDAT ??_C@_1EA@INDIFGGF@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAL?$AA_?$AAX?$AAn?$PP?$KJ?$AA0@
CONST	SEGMENT
??_C@_1EA@INDIFGGF@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAL?$AA_?$AAX?$AAn?$PP?$KJ?$AA0@ DB 'S'
	DB	00H, 'u', 00H, 'b', 00H, 't', 00H, 'r', 00H, 'u', 00H, 'c', 00H
	DB	't', 00H, '_', 00H, 'L', 00H, '_', 00H, 'X', 00H, 'n0', 0a9H, '_'
	DB	'0^', 0b3H, '0', 0fcH, '0', 0c9H, '0L0', 01fH, 'g', 085H, '_', 01aH
	DB	090H, 08aH, '0g0o0j0D0(', 00H, '%', 00H, 'd', 00H, ')', 00H, 00H
	DB	00H						; `string'
CONST	ENDS
;	COMDAT ??_C@_1CK@HMHBAFBJ@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAL?$AA_?$AAX?$AA?5?$AA?$CI?$AA?$CF@
CONST	SEGMENT
??_C@_1CK@HMHBAFBJ@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAL?$AA_?$AAX?$AA?5?$AA?$CI?$AA?$CF@ DB 'S'
	DB	00H, 'u', 00H, 'b', 00H, 't', 00H, 'r', 00H, 'u', 00H, 'c', 00H
	DB	't', 00H, '_', 00H, 'L', 00H, '_', 00H, 'X', 00H, ' ', 00H, '('
	DB	00H, '%', 00H, 'd', 00H, '.', 00H, '%', 00H, 'd', 00H, ')', 00H
	DB	00H, 00H					; `string'
CONST	ENDS
;	COMDAT ??_C@_1BK@CBDJCOBM@?$PP?G?$PP?$PM?$PP?$LP?$AAn?$PP?$IF?$PP?$LJ?$AAL?$AA?$AA?$PP?t?$AAW?$AAj?$AAD@
CONST	SEGMENT
??_C@_1BK@CBDJCOBM@?$PP?G?$PP?$PM?$PP?$LP?$AAn?$PP?$IF?$PP?$LJ?$AAL?$AA?$AA?$PP?t?$AAW?$AAj?$AAD@ DB 0c7H
	DB	'0', 0fcH, '0', 0bfH, '0n0', 085H, 'Q', 0b9H, '[L0', 00H, 'N', 0f4H
	DB	081H, 'W0j0D0', 00H, 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_1DO@DOHJEMND@?$AAT?$AAo?$AAB?$AAy?$AAt?$AAe?$AAA?$AAr?$AAr?$AAa?$AAy?$AAn?$PP?$KJ?$AA0?$PP?$LD@
CONST	SEGMENT
??_C@_1DO@DOHJEMND@?$AAT?$AAo?$AAB?$AAy?$AAt?$AAe?$AAA?$AAr?$AAr?$AAa?$AAy?$AAn?$PP?$KJ?$AA0?$PP?$LD@ DB 'T'
	DB	00H, 'o', 00H, 'B', 00H, 'y', 00H, 't', 00H, 'e', 00H, 'A', 00H
	DB	'r', 00H, 'r', 00H, 'a', 00H, 'y', 00H, 'n0', 0a9H, '_0^', 0b3H
	DB	'0', 0fcH, '0', 0c9H, '0L0', 01fH, 'g', 085H, '_', 01aH, 090H, 08aH
	DB	'0g0o0j0D0(', 00H, '%', 00H, 'd', 00H, ')', 00H, 00H, 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_1EA@NGKGKFPL@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAI?$AA_?$AAX?$AAn?$PP?$KJ?$AA0@
CONST	SEGMENT
??_C@_1EA@NGKGKFPL@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAI?$AA_?$AAX?$AAn?$PP?$KJ?$AA0@ DB 'S'
	DB	00H, 'u', 00H, 'b', 00H, 't', 00H, 'r', 00H, 'u', 00H, 'c', 00H
	DB	't', 00H, '_', 00H, 'I', 00H, '_', 00H, 'X', 00H, 'n0', 0a9H, '_'
	DB	'0^', 0b3H, '0', 0fcH, '0', 0c9H, '0L0', 01fH, 'g', 085H, '_', 01aH
	DB	090H, 08aH, '0g0o0j0D0(', 00H, '%', 00H, 'd', 00H, ')', 00H, 00H
	DB	00H						; `string'
CONST	ENDS
;	COMDAT ??_C@_1CK@JEFCPOGB@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAI?$AA_?$AAX?$AA?5?$AA?$CI?$AA?$CF@
CONST	SEGMENT
??_C@_1CK@JEFCPOGB@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAI?$AA_?$AAX?$AA?5?$AA?$CI?$AA?$CF@ DB 'S'
	DB	00H, 'u', 00H, 'b', 00H, 't', 00H, 'r', 00H, 'u', 00H, 'c', 00H
	DB	't', 00H, '_', 00H, 'I', 00H, '_', 00H, 'X', 00H, ' ', 00H, '('
	DB	00H, '%', 00H, 'd', 00H, '.', 00H, '%', 00H, 'd', 00H, ')', 00H
	DB	00H, 00H					; `string'
CONST	ENDS
;	COMDAT ??_C@_1EC@NPMCAPKO@?$AAF?$AAr?$AAo?$AAm?$AAB?$AAy?$AAt?$AAe?$AAA?$AAr?$AAr?$AAa?$AAy?$AAn?$PP?$KJ@
CONST	SEGMENT
??_C@_1EC@NPMCAPKO@?$AAF?$AAr?$AAo?$AAm?$AAB?$AAy?$AAt?$AAe?$AAA?$AAr?$AAr?$AAa?$AAy?$AAn?$PP?$KJ@ DB 'F'
	DB	00H, 'r', 00H, 'o', 00H, 'm', 00H, 'B', 00H, 'y', 00H, 't', 00H
	DB	'e', 00H, 'A', 00H, 'r', 00H, 'r', 00H, 'a', 00H, 'y', 00H, 'n'
	DB	'0', 0a9H, '_0^', 0b3H, '0', 0fcH, '0', 0c9H, '0L0', 01fH, 'g', 085H
	DB	'_', 01aH, 090H, 08aH, '0g0o0j0D0(', 00H, '%', 00H, 'd', 00H, ')'
	DB	00H, 00H, 00H				; `string'
CONST	ENDS
; Function compile flags: /Odt
;	COMDAT __JustMyCode_Default
_TEXT	SEGMENT
__JustMyCode_Default PROC				; COMDAT
	push	ebp
	mov	ebp, esp
	pop	ebp
	ret	0
__JustMyCode_Default ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.sint\palmtree.math.core.sint\pmc_sint_debug.h
;	COMDAT __EQUALS_MEMORY
_TEXT	SEGMENT
_buffer1$ = 8						; size = 4
_count1$ = 12						; size = 4
_buffer2$ = 16						; size = 4
_count2$ = 20						; size = 4
__EQUALS_MEMORY PROC					; COMDAT

; 138  : {

	push	ebp
	mov	ebp, esp
	sub	esp, 192				; 000000c0H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-192]
	mov	ecx, 48					; 00000030H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	ecx, OFFSET __059414E1_pmc_sint_debug@h
	call	@__CheckForDebuggerJustMyCode@4

; 139  :     if (count1 != count2)

	mov	eax, DWORD PTR _count1$[ebp]
	cmp	eax, DWORD PTR _count2$[ebp]
	je	SHORT $LN2@EQUALS_MEM

; 140  :         return (-1);

	or	eax, -1
	jmp	SHORT $LN1@EQUALS_MEM
$LN2@EQUALS_MEM:

; 141  :     while (count1 > 0)

	cmp	DWORD PTR _count1$[ebp], 0
	jbe	SHORT $LN3@EQUALS_MEM

; 142  :     {
; 143  :         if (*buffer1 != *buffer2)

	mov	eax, DWORD PTR _buffer1$[ebp]
	movzx	ecx, BYTE PTR [eax]
	mov	edx, DWORD PTR _buffer2$[ebp]
	movzx	eax, BYTE PTR [edx]
	cmp	ecx, eax
	je	SHORT $LN5@EQUALS_MEM

; 144  :             return (-1);

	or	eax, -1
	jmp	SHORT $LN1@EQUALS_MEM
$LN5@EQUALS_MEM:

; 145  :         ++buffer1;

	mov	eax, DWORD PTR _buffer1$[ebp]
	add	eax, 1
	mov	DWORD PTR _buffer1$[ebp], eax

; 146  :         ++buffer2;

	mov	eax, DWORD PTR _buffer2$[ebp]
	add	eax, 1
	mov	DWORD PTR _buffer2$[ebp], eax

; 147  :         --count1;

	mov	eax, DWORD PTR _count1$[ebp]
	sub	eax, 1
	mov	DWORD PTR _count1$[ebp], eax

; 148  :     }

	jmp	SHORT $LN2@EQUALS_MEM
$LN3@EQUALS_MEM:

; 149  :     return (0);

	xor	eax, eax
$LN1@EQUALS_MEM:

; 150  : }

	pop	edi
	pop	esi
	pop	ebx
	add	esp, 192				; 000000c0H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
__EQUALS_MEMORY ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.sint\palmtree.math.core.sint\test_op_subtruct.c
;	COMDAT _TEST_Subtruct_X_X
_TEXT	SEGMENT
tv176 = -560						; size = 4
tv161 = -560						; size = 4
tv142 = -560						; size = 4
tv92 = -560						; size = 4
tv74 = -560						; size = 4
_w_result$ = -360					; size = 4
_v_result$ = -348					; size = 4
_u_result$ = -336					; size = 4
_result$ = -324						; size = 4
_actual_z_buf_size$ = -312				; size = 4
_actual_z_buf$ = -300					; size = 256
_w$ = -36						; size = 4
_v$ = -24						; size = 4
_u$ = -12						; size = 4
__$ArrayPad$ = -4					; size = 4
_env$ = 8						; size = 4
_ep$ = 12						; size = 4
_no$ = 16						; size = 4
_u_buf$ = 20						; size = 4
_u_buf_size$ = 24					; size = 4
_v_buf$ = 28						; size = 4
_v_buf_size$ = 32					; size = 4
_desired_w_buf$ = 36					; size = 4
_desired_w_buf_size$ = 40				; size = 4
_TEST_Subtruct_X_X PROC					; COMDAT

; 155  : {

	push	ebp
	mov	ebp, esp
	sub	esp, 560				; 00000230H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-560]
	mov	ecx, 140				; 0000008cH
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	mov	DWORD PTR __$ArrayPad$[ebp], eax
	mov	ecx, OFFSET __433B2F9A_test_op_subtruct@c
	call	@__CheckForDebuggerJustMyCode@4

; 156  :     PMC_HANDLE_SINT u;
; 157  :     PMC_HANDLE_SINT v;
; 158  :     PMC_HANDLE_SINT w;
; 159  :     unsigned char actual_z_buf[256];
; 160  :     size_t actual_z_buf_size;
; 161  :     PMC_STATUS_CODE result;
; 162  :     PMC_STATUS_CODE u_result;
; 163  :     PMC_STATUS_CODE v_result;
; 164  :     PMC_STATUS_CODE w_result;
; 165  :     TEST_Assert(env, FormatTestLabel(L"Subtruct_X_X (%d.%d)", no, 1), (u_result = ep->FromByteArray(u_buf, u_buf_size, &u)) == PMC_STATUS_OK, FormatTestMesssage(L"FromByteArrayの復帰コードが期待通りではない(%d)", u_result));

	mov	esi, esp
	lea	eax, DWORD PTR _u$[ebp]
	push	eax
	mov	ecx, DWORD PTR _u_buf_size$[ebp]
	push	ecx
	mov	edx, DWORD PTR _u_buf$[ebp]
	push	edx
	mov	eax, DWORD PTR _ep$[ebp]
	mov	ecx, DWORD PTR [eax+300]
	call	ecx
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _u_result$[ebp], eax
	cmp	DWORD PTR _u_result$[ebp], 0
	jne	SHORT $LN6@TEST_Subtr
	mov	DWORD PTR tv74[ebp], 1
	jmp	SHORT $LN7@TEST_Subtr
$LN6@TEST_Subtr:
	mov	DWORD PTR tv74[ebp], 0
$LN7@TEST_Subtr:
	mov	edx, DWORD PTR _u_result$[ebp]
	push	edx
	push	OFFSET ??_C@_1EC@NPMCAPKO@?$AAF?$AAr?$AAo?$AAm?$AAB?$AAy?$AAt?$AAe?$AAA?$AAr?$AAr?$AAa?$AAy?$AAn?$PP?$KJ@
	call	_FormatTestMesssage
	add	esp, 8
	push	eax
	mov	eax, DWORD PTR tv74[ebp]
	push	eax
	push	1
	mov	ecx, DWORD PTR _no$[ebp]
	push	ecx
	push	OFFSET ??_C@_1CK@GKBMOEHL@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAX?$AA_?$AAX?$AA?5?$AA?$CI?$AA?$CF@
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	edx, DWORD PTR _env$[ebp]
	push	edx
	call	_TEST_Assert
	add	esp, 16					; 00000010H

; 166  :     TEST_Assert(env, FormatTestLabel(L"Subtruct_X_X (%d.%d)", no, 2), (v_result = ep->FromByteArray(v_buf, v_buf_size, &v)) == PMC_STATUS_OK, FormatTestMesssage(L"FromByteArrayの復帰コードが期待通りではない(%d)", v_result));

	mov	esi, esp
	lea	eax, DWORD PTR _v$[ebp]
	push	eax
	mov	ecx, DWORD PTR _v_buf_size$[ebp]
	push	ecx
	mov	edx, DWORD PTR _v_buf$[ebp]
	push	edx
	mov	eax, DWORD PTR _ep$[ebp]
	mov	ecx, DWORD PTR [eax+300]
	call	ecx
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _v_result$[ebp], eax
	cmp	DWORD PTR _v_result$[ebp], 0
	jne	SHORT $LN8@TEST_Subtr
	mov	DWORD PTR tv92[ebp], 1
	jmp	SHORT $LN9@TEST_Subtr
$LN8@TEST_Subtr:
	mov	DWORD PTR tv92[ebp], 0
$LN9@TEST_Subtr:
	mov	edx, DWORD PTR _v_result$[ebp]
	push	edx
	push	OFFSET ??_C@_1EC@NPMCAPKO@?$AAF?$AAr?$AAo?$AAm?$AAB?$AAy?$AAt?$AAe?$AAA?$AAr?$AAr?$AAa?$AAy?$AAn?$PP?$KJ@
	call	_FormatTestMesssage
	add	esp, 8
	push	eax
	mov	eax, DWORD PTR tv92[ebp]
	push	eax
	push	2
	mov	ecx, DWORD PTR _no$[ebp]
	push	ecx
	push	OFFSET ??_C@_1CK@GKBMOEHL@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAX?$AA_?$AAX?$AA?5?$AA?$CI?$AA?$CF@
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	edx, DWORD PTR _env$[ebp]
	push	edx
	call	_TEST_Assert
	add	esp, 16					; 00000010H

; 167  :     TEST_Assert(env, FormatTestLabel(L"Subtruct_X_X (%d.%d)", no, 3), (w_result = ep->Subtruct_X_X(u, v, &w)) == PMC_STATUS_OK, FormatTestMesssage(L"Subtruct_X_Xの復帰コードが期待通りではない(%d)", w_result));

	mov	esi, esp
	lea	eax, DWORD PTR _w$[ebp]
	push	eax
	mov	ecx, DWORD PTR _v$[ebp]
	push	ecx
	mov	edx, DWORD PTR _u$[ebp]
	push	edx
	mov	eax, DWORD PTR _ep$[ebp]
	mov	ecx, DWORD PTR [eax+380]
	call	ecx
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _w_result$[ebp], eax
	cmp	DWORD PTR _w_result$[ebp], 0
	jne	SHORT $LN10@TEST_Subtr
	mov	DWORD PTR tv142[ebp], 1
	jmp	SHORT $LN11@TEST_Subtr
$LN10@TEST_Subtr:
	mov	DWORD PTR tv142[ebp], 0
$LN11@TEST_Subtr:
	mov	edx, DWORD PTR _w_result$[ebp]
	push	edx
	push	OFFSET ??_C@_1EA@DIDCJOFM@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAX?$AA_?$AAX?$AAn?$PP?$KJ?$AA0@
	call	_FormatTestMesssage
	add	esp, 8
	push	eax
	mov	eax, DWORD PTR tv142[ebp]
	push	eax
	push	3
	mov	ecx, DWORD PTR _no$[ebp]
	push	ecx
	push	OFFSET ??_C@_1CK@GKBMOEHL@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAX?$AA_?$AAX?$AA?5?$AA?$CI?$AA?$CF@
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	edx, DWORD PTR _env$[ebp]
	push	edx
	call	_TEST_Assert
	add	esp, 16					; 00000010H

; 168  :     TEST_Assert(env, FormatTestLabel(L"Subtruct_X_X (%d.%d)", no, 4), (result = ep->ToByteArray(w, actual_z_buf, sizeof(actual_z_buf), &actual_z_buf_size)) == PMC_STATUS_OK, FormatTestMesssage(L"ToByteArrayの復帰コードが期待通りではない(%d)", result));

	mov	esi, esp
	lea	eax, DWORD PTR _actual_z_buf_size$[ebp]
	push	eax
	push	256					; 00000100H
	lea	ecx, DWORD PTR _actual_z_buf$[ebp]
	push	ecx
	mov	edx, DWORD PTR _w$[ebp]
	push	edx
	mov	eax, DWORD PTR _ep$[ebp]
	mov	ecx, DWORD PTR [eax+304]
	call	ecx
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _result$[ebp], eax
	cmp	DWORD PTR _result$[ebp], 0
	jne	SHORT $LN12@TEST_Subtr
	mov	DWORD PTR tv161[ebp], 1
	jmp	SHORT $LN13@TEST_Subtr
$LN12@TEST_Subtr:
	mov	DWORD PTR tv161[ebp], 0
$LN13@TEST_Subtr:
	mov	edx, DWORD PTR _result$[ebp]
	push	edx
	push	OFFSET ??_C@_1DO@DOHJEMND@?$AAT?$AAo?$AAB?$AAy?$AAt?$AAe?$AAA?$AAr?$AAr?$AAa?$AAy?$AAn?$PP?$KJ?$AA0?$PP?$LD@
	call	_FormatTestMesssage
	add	esp, 8
	push	eax
	mov	eax, DWORD PTR tv161[ebp]
	push	eax
	push	4
	mov	ecx, DWORD PTR _no$[ebp]
	push	ecx
	push	OFFSET ??_C@_1CK@GKBMOEHL@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAX?$AA_?$AAX?$AA?5?$AA?$CI?$AA?$CF@
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	edx, DWORD PTR _env$[ebp]
	push	edx
	call	_TEST_Assert
	add	esp, 16					; 00000010H

; 169  :     TEST_Assert(env, FormatTestLabel(L"Subtruct_X_X (%d.%d)", no, 5), _EQUALS_MEMORY(actual_z_buf, actual_z_buf_size, desired_w_buf, desired_w_buf_size) == 0, L"データの内容が一致しない");

	mov	eax, DWORD PTR _desired_w_buf_size$[ebp]
	push	eax
	mov	ecx, DWORD PTR _desired_w_buf$[ebp]
	push	ecx
	mov	edx, DWORD PTR _actual_z_buf_size$[ebp]
	push	edx
	lea	eax, DWORD PTR _actual_z_buf$[ebp]
	push	eax
	call	__EQUALS_MEMORY
	add	esp, 16					; 00000010H
	test	eax, eax
	jne	SHORT $LN14@TEST_Subtr
	mov	DWORD PTR tv176[ebp], 1
	jmp	SHORT $LN15@TEST_Subtr
$LN14@TEST_Subtr:
	mov	DWORD PTR tv176[ebp], 0
$LN15@TEST_Subtr:
	push	OFFSET ??_C@_1BK@CBDJCOBM@?$PP?G?$PP?$PM?$PP?$LP?$AAn?$PP?$IF?$PP?$LJ?$AAL?$AA?$AA?$PP?t?$AAW?$AAj?$AAD@
	mov	ecx, DWORD PTR tv176[ebp]
	push	ecx
	push	5
	mov	edx, DWORD PTR _no$[ebp]
	push	edx
	push	OFFSET ??_C@_1CK@GKBMOEHL@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAX?$AA_?$AAX?$AA?5?$AA?$CI?$AA?$CF@
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	eax, DWORD PTR _env$[ebp]
	push	eax
	call	_TEST_Assert
	add	esp, 16					; 00000010H

; 170  :     if (w_result == PMC_STATUS_OK)

	cmp	DWORD PTR _w_result$[ebp], 0
	jne	SHORT $LN2@TEST_Subtr

; 171  :         ep->Dispose(w);

	mov	esi, esp
	mov	eax, DWORD PTR _w$[ebp]
	push	eax
	mov	ecx, DWORD PTR _ep$[ebp]
	mov	edx, DWORD PTR [ecx+292]
	call	edx
	cmp	esi, esp
	call	__RTC_CheckEsp
$LN2@TEST_Subtr:

; 172  :     if (v_result == PMC_STATUS_OK)

	cmp	DWORD PTR _v_result$[ebp], 0
	jne	SHORT $LN3@TEST_Subtr

; 173  :         ep->Dispose(v);

	mov	esi, esp
	mov	eax, DWORD PTR _v$[ebp]
	push	eax
	mov	ecx, DWORD PTR _ep$[ebp]
	mov	edx, DWORD PTR [ecx+292]
	call	edx
	cmp	esi, esp
	call	__RTC_CheckEsp
$LN3@TEST_Subtr:

; 174  :     if (u_result == PMC_STATUS_OK)

	cmp	DWORD PTR _u_result$[ebp], 0
	jne	SHORT $LN1@TEST_Subtr

; 175  :         ep->Dispose(u);

	mov	esi, esp
	mov	eax, DWORD PTR _u$[ebp]
	push	eax
	mov	ecx, DWORD PTR _ep$[ebp]
	mov	edx, DWORD PTR [ecx+292]
	call	edx
	cmp	esi, esp
	call	__RTC_CheckEsp
$LN1@TEST_Subtr:

; 176  : }

	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN22@TEST_Subtr
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	pop	edi
	pop	esi
	pop	ebx
	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	ecx, ebp
	call	@__security_check_cookie@4
	add	esp, 560				; 00000230H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
	npad	1
$LN22@TEST_Subtr:
	DD	5
	DD	$LN21@TEST_Subtr
$LN21@TEST_Subtr:
	DD	-12					; fffffff4H
	DD	4
	DD	$LN16@TEST_Subtr
	DD	-24					; ffffffe8H
	DD	4
	DD	$LN17@TEST_Subtr
	DD	-36					; ffffffdcH
	DD	4
	DD	$LN18@TEST_Subtr
	DD	-300					; fffffed4H
	DD	256					; 00000100H
	DD	$LN19@TEST_Subtr
	DD	-312					; fffffec8H
	DD	4
	DD	$LN20@TEST_Subtr
$LN20@TEST_Subtr:
	DB	97					; 00000061H
	DB	99					; 00000063H
	DB	116					; 00000074H
	DB	117					; 00000075H
	DB	97					; 00000061H
	DB	108					; 0000006cH
	DB	95					; 0000005fH
	DB	122					; 0000007aH
	DB	95					; 0000005fH
	DB	98					; 00000062H
	DB	117					; 00000075H
	DB	102					; 00000066H
	DB	95					; 0000005fH
	DB	115					; 00000073H
	DB	105					; 00000069H
	DB	122					; 0000007aH
	DB	101					; 00000065H
	DB	0
$LN19@TEST_Subtr:
	DB	97					; 00000061H
	DB	99					; 00000063H
	DB	116					; 00000074H
	DB	117					; 00000075H
	DB	97					; 00000061H
	DB	108					; 0000006cH
	DB	95					; 0000005fH
	DB	122					; 0000007aH
	DB	95					; 0000005fH
	DB	98					; 00000062H
	DB	117					; 00000075H
	DB	102					; 00000066H
	DB	0
$LN18@TEST_Subtr:
	DB	119					; 00000077H
	DB	0
$LN17@TEST_Subtr:
	DB	118					; 00000076H
	DB	0
$LN16@TEST_Subtr:
	DB	117					; 00000075H
	DB	0
_TEST_Subtruct_X_X ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.sint\palmtree.math.core.sint\test_op_subtruct.c
;	COMDAT _TEST_Subtruct_X_UX
_TEXT	SEGMENT
tv176 = -560						; size = 4
tv161 = -560						; size = 4
tv142 = -560						; size = 4
tv92 = -560						; size = 4
tv74 = -560						; size = 4
_w_result$ = -360					; size = 4
_v_result$ = -348					; size = 4
_u_result$ = -336					; size = 4
_result$ = -324						; size = 4
_actual_z_buf_size$ = -312				; size = 4
_actual_z_buf$ = -300					; size = 256
_w$ = -36						; size = 4
_v$ = -24						; size = 4
_u$ = -12						; size = 4
__$ArrayPad$ = -4					; size = 4
_env$ = 8						; size = 4
_ep$ = 12						; size = 4
_no$ = 16						; size = 4
_u_buf$ = 20						; size = 4
_u_buf_size$ = 24					; size = 4
_v_buf$ = 28						; size = 4
_v_buf_size$ = 32					; size = 4
_desired_w_buf$ = 36					; size = 4
_desired_w_buf_size$ = 40				; size = 4
_TEST_Subtruct_X_UX PROC				; COMDAT

; 132  : {

	push	ebp
	mov	ebp, esp
	sub	esp, 560				; 00000230H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-560]
	mov	ecx, 140				; 0000008cH
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	mov	DWORD PTR __$ArrayPad$[ebp], eax
	mov	ecx, OFFSET __433B2F9A_test_op_subtruct@c
	call	@__CheckForDebuggerJustMyCode@4

; 133  :     PMC_HANDLE_SINT u;
; 134  :     PMC_HANDLE_UINT v;
; 135  :     PMC_HANDLE_SINT w;
; 136  :     unsigned char actual_z_buf[256];
; 137  :     size_t actual_z_buf_size;
; 138  :     PMC_STATUS_CODE result;
; 139  :     PMC_STATUS_CODE u_result;
; 140  :     PMC_STATUS_CODE v_result;
; 141  :     PMC_STATUS_CODE w_result;
; 142  :     TEST_Assert(env, FormatTestLabel(L"Subtruct_X_UX (%d.%d)", no, 1), (u_result = ep->FromByteArray(u_buf, u_buf_size, &u)) == PMC_STATUS_OK, FormatTestMesssage(L"FromByteArrayの復帰コードが期待通りではない(%d)", u_result));

	mov	esi, esp
	lea	eax, DWORD PTR _u$[ebp]
	push	eax
	mov	ecx, DWORD PTR _u_buf_size$[ebp]
	push	ecx
	mov	edx, DWORD PTR _u_buf$[ebp]
	push	edx
	mov	eax, DWORD PTR _ep$[ebp]
	mov	ecx, DWORD PTR [eax+300]
	call	ecx
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _u_result$[ebp], eax
	cmp	DWORD PTR _u_result$[ebp], 0
	jne	SHORT $LN6@TEST_Subtr
	mov	DWORD PTR tv74[ebp], 1
	jmp	SHORT $LN7@TEST_Subtr
$LN6@TEST_Subtr:
	mov	DWORD PTR tv74[ebp], 0
$LN7@TEST_Subtr:
	mov	edx, DWORD PTR _u_result$[ebp]
	push	edx
	push	OFFSET ??_C@_1EC@NPMCAPKO@?$AAF?$AAr?$AAo?$AAm?$AAB?$AAy?$AAt?$AAe?$AAA?$AAr?$AAr?$AAa?$AAy?$AAn?$PP?$KJ@
	call	_FormatTestMesssage
	add	esp, 8
	push	eax
	mov	eax, DWORD PTR tv74[ebp]
	push	eax
	push	1
	mov	ecx, DWORD PTR _no$[ebp]
	push	ecx
	push	OFFSET ??_C@_1CM@KAKNNFML@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAX?$AA_?$AAU?$AAX?$AA?5?$AA?$CI@
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	edx, DWORD PTR _env$[ebp]
	push	edx
	call	_TEST_Assert
	add	esp, 16					; 00000010H

; 143  :     TEST_Assert(env, FormatTestLabel(L"Subtruct_X_UX (%d.%d)", no, 2), (v_result = ep->UINT_ENTRY_POINTS.FromByteArray(v_buf, v_buf_size, &v)) == PMC_STATUS_OK, FormatTestMesssage(L"FromByteArrayの復帰コードが期待通りではない(%d)", v_result));

	mov	esi, esp
	lea	eax, DWORD PTR _v$[ebp]
	push	eax
	mov	ecx, DWORD PTR _v_buf_size$[ebp]
	push	ecx
	mov	edx, DWORD PTR _v_buf$[ebp]
	push	edx
	mov	eax, DWORD PTR _ep$[ebp]
	mov	ecx, DWORD PTR [eax+24]
	call	ecx
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _v_result$[ebp], eax
	cmp	DWORD PTR _v_result$[ebp], 0
	jne	SHORT $LN8@TEST_Subtr
	mov	DWORD PTR tv92[ebp], 1
	jmp	SHORT $LN9@TEST_Subtr
$LN8@TEST_Subtr:
	mov	DWORD PTR tv92[ebp], 0
$LN9@TEST_Subtr:
	mov	edx, DWORD PTR _v_result$[ebp]
	push	edx
	push	OFFSET ??_C@_1EC@NPMCAPKO@?$AAF?$AAr?$AAo?$AAm?$AAB?$AAy?$AAt?$AAe?$AAA?$AAr?$AAr?$AAa?$AAy?$AAn?$PP?$KJ@
	call	_FormatTestMesssage
	add	esp, 8
	push	eax
	mov	eax, DWORD PTR tv92[ebp]
	push	eax
	push	2
	mov	ecx, DWORD PTR _no$[ebp]
	push	ecx
	push	OFFSET ??_C@_1CM@KAKNNFML@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAX?$AA_?$AAU?$AAX?$AA?5?$AA?$CI@
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	edx, DWORD PTR _env$[ebp]
	push	edx
	call	_TEST_Assert
	add	esp, 16					; 00000010H

; 144  :     TEST_Assert(env, FormatTestLabel(L"Subtruct_X_UX (%d.%d)", no, 3), (w_result = ep->Subtruct_X_UX(u, v, &w)) == PMC_STATUS_OK, FormatTestMesssage(L"Subtruct_X_UXの復帰コードが期待通りではない(%d)", w_result));

	mov	esi, esp
	lea	eax, DWORD PTR _w$[ebp]
	push	eax
	mov	ecx, DWORD PTR _v$[ebp]
	push	ecx
	mov	edx, DWORD PTR _u$[ebp]
	push	edx
	mov	eax, DWORD PTR _ep$[ebp]
	mov	ecx, DWORD PTR [eax+376]
	call	ecx
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _w_result$[ebp], eax
	cmp	DWORD PTR _w_result$[ebp], 0
	jne	SHORT $LN10@TEST_Subtr
	mov	DWORD PTR tv142[ebp], 1
	jmp	SHORT $LN11@TEST_Subtr
$LN10@TEST_Subtr:
	mov	DWORD PTR tv142[ebp], 0
$LN11@TEST_Subtr:
	mov	edx, DWORD PTR _w_result$[ebp]
	push	edx
	push	OFFSET ??_C@_1EC@ELOBBMPD@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAX?$AA_?$AAU?$AAX?$AAn?$PP?$KJ@
	call	_FormatTestMesssage
	add	esp, 8
	push	eax
	mov	eax, DWORD PTR tv142[ebp]
	push	eax
	push	3
	mov	ecx, DWORD PTR _no$[ebp]
	push	ecx
	push	OFFSET ??_C@_1CM@KAKNNFML@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAX?$AA_?$AAU?$AAX?$AA?5?$AA?$CI@
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	edx, DWORD PTR _env$[ebp]
	push	edx
	call	_TEST_Assert
	add	esp, 16					; 00000010H

; 145  :     TEST_Assert(env, FormatTestLabel(L"Subtruct_X_UX (%d.%d)", no, 4), (result = ep->ToByteArray(w, actual_z_buf, sizeof(actual_z_buf), &actual_z_buf_size)) == PMC_STATUS_OK, FormatTestMesssage(L"ToByteArrayの復帰コードが期待通りではない(%d)", result));

	mov	esi, esp
	lea	eax, DWORD PTR _actual_z_buf_size$[ebp]
	push	eax
	push	256					; 00000100H
	lea	ecx, DWORD PTR _actual_z_buf$[ebp]
	push	ecx
	mov	edx, DWORD PTR _w$[ebp]
	push	edx
	mov	eax, DWORD PTR _ep$[ebp]
	mov	ecx, DWORD PTR [eax+304]
	call	ecx
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _result$[ebp], eax
	cmp	DWORD PTR _result$[ebp], 0
	jne	SHORT $LN12@TEST_Subtr
	mov	DWORD PTR tv161[ebp], 1
	jmp	SHORT $LN13@TEST_Subtr
$LN12@TEST_Subtr:
	mov	DWORD PTR tv161[ebp], 0
$LN13@TEST_Subtr:
	mov	edx, DWORD PTR _result$[ebp]
	push	edx
	push	OFFSET ??_C@_1DO@DOHJEMND@?$AAT?$AAo?$AAB?$AAy?$AAt?$AAe?$AAA?$AAr?$AAr?$AAa?$AAy?$AAn?$PP?$KJ?$AA0?$PP?$LD@
	call	_FormatTestMesssage
	add	esp, 8
	push	eax
	mov	eax, DWORD PTR tv161[ebp]
	push	eax
	push	4
	mov	ecx, DWORD PTR _no$[ebp]
	push	ecx
	push	OFFSET ??_C@_1CM@KAKNNFML@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAX?$AA_?$AAU?$AAX?$AA?5?$AA?$CI@
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	edx, DWORD PTR _env$[ebp]
	push	edx
	call	_TEST_Assert
	add	esp, 16					; 00000010H

; 146  :     TEST_Assert(env, FormatTestLabel(L"Subtruct_X_UX (%d.%d)", no, 5), _EQUALS_MEMORY(actual_z_buf, actual_z_buf_size, desired_w_buf, desired_w_buf_size) == 0, L"データの内容が一致しない");

	mov	eax, DWORD PTR _desired_w_buf_size$[ebp]
	push	eax
	mov	ecx, DWORD PTR _desired_w_buf$[ebp]
	push	ecx
	mov	edx, DWORD PTR _actual_z_buf_size$[ebp]
	push	edx
	lea	eax, DWORD PTR _actual_z_buf$[ebp]
	push	eax
	call	__EQUALS_MEMORY
	add	esp, 16					; 00000010H
	test	eax, eax
	jne	SHORT $LN14@TEST_Subtr
	mov	DWORD PTR tv176[ebp], 1
	jmp	SHORT $LN15@TEST_Subtr
$LN14@TEST_Subtr:
	mov	DWORD PTR tv176[ebp], 0
$LN15@TEST_Subtr:
	push	OFFSET ??_C@_1BK@CBDJCOBM@?$PP?G?$PP?$PM?$PP?$LP?$AAn?$PP?$IF?$PP?$LJ?$AAL?$AA?$AA?$PP?t?$AAW?$AAj?$AAD@
	mov	ecx, DWORD PTR tv176[ebp]
	push	ecx
	push	5
	mov	edx, DWORD PTR _no$[ebp]
	push	edx
	push	OFFSET ??_C@_1CM@KAKNNFML@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAX?$AA_?$AAU?$AAX?$AA?5?$AA?$CI@
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	eax, DWORD PTR _env$[ebp]
	push	eax
	call	_TEST_Assert
	add	esp, 16					; 00000010H

; 147  :     if (w_result == PMC_STATUS_OK)

	cmp	DWORD PTR _w_result$[ebp], 0
	jne	SHORT $LN2@TEST_Subtr

; 148  :         ep->Dispose(w);

	mov	esi, esp
	mov	eax, DWORD PTR _w$[ebp]
	push	eax
	mov	ecx, DWORD PTR _ep$[ebp]
	mov	edx, DWORD PTR [ecx+292]
	call	edx
	cmp	esi, esp
	call	__RTC_CheckEsp
$LN2@TEST_Subtr:

; 149  :     if (v_result == PMC_STATUS_OK)

	cmp	DWORD PTR _v_result$[ebp], 0
	jne	SHORT $LN3@TEST_Subtr

; 150  :         ep->UINT_ENTRY_POINTS.Dispose(v);

	mov	esi, esp
	mov	eax, DWORD PTR _v$[ebp]
	push	eax
	mov	ecx, DWORD PTR _ep$[ebp]
	mov	edx, DWORD PTR [ecx+16]
	call	edx
	cmp	esi, esp
	call	__RTC_CheckEsp
$LN3@TEST_Subtr:

; 151  :     if (u_result == PMC_STATUS_OK)

	cmp	DWORD PTR _u_result$[ebp], 0
	jne	SHORT $LN1@TEST_Subtr

; 152  :         ep->Dispose(u);

	mov	esi, esp
	mov	eax, DWORD PTR _u$[ebp]
	push	eax
	mov	ecx, DWORD PTR _ep$[ebp]
	mov	edx, DWORD PTR [ecx+292]
	call	edx
	cmp	esi, esp
	call	__RTC_CheckEsp
$LN1@TEST_Subtr:

; 153  : }

	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN22@TEST_Subtr
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	pop	edi
	pop	esi
	pop	ebx
	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	ecx, ebp
	call	@__security_check_cookie@4
	add	esp, 560				; 00000230H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
	npad	3
$LN22@TEST_Subtr:
	DD	5
	DD	$LN21@TEST_Subtr
$LN21@TEST_Subtr:
	DD	-12					; fffffff4H
	DD	4
	DD	$LN16@TEST_Subtr
	DD	-24					; ffffffe8H
	DD	4
	DD	$LN17@TEST_Subtr
	DD	-36					; ffffffdcH
	DD	4
	DD	$LN18@TEST_Subtr
	DD	-300					; fffffed4H
	DD	256					; 00000100H
	DD	$LN19@TEST_Subtr
	DD	-312					; fffffec8H
	DD	4
	DD	$LN20@TEST_Subtr
$LN20@TEST_Subtr:
	DB	97					; 00000061H
	DB	99					; 00000063H
	DB	116					; 00000074H
	DB	117					; 00000075H
	DB	97					; 00000061H
	DB	108					; 0000006cH
	DB	95					; 0000005fH
	DB	122					; 0000007aH
	DB	95					; 0000005fH
	DB	98					; 00000062H
	DB	117					; 00000075H
	DB	102					; 00000066H
	DB	95					; 0000005fH
	DB	115					; 00000073H
	DB	105					; 00000069H
	DB	122					; 0000007aH
	DB	101					; 00000065H
	DB	0
$LN19@TEST_Subtr:
	DB	97					; 00000061H
	DB	99					; 00000063H
	DB	116					; 00000074H
	DB	117					; 00000075H
	DB	97					; 00000061H
	DB	108					; 0000006cH
	DB	95					; 0000005fH
	DB	122					; 0000007aH
	DB	95					; 0000005fH
	DB	98					; 00000062H
	DB	117					; 00000075H
	DB	102					; 00000066H
	DB	0
$LN18@TEST_Subtr:
	DB	119					; 00000077H
	DB	0
$LN17@TEST_Subtr:
	DB	118					; 00000076H
	DB	0
$LN16@TEST_Subtr:
	DB	117					; 00000075H
	DB	0
_TEST_Subtruct_X_UX ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.sint\palmtree.math.core.sint\test_op_subtruct.c
;	COMDAT _TEST_Subtruct_X_L
_TEXT	SEGMENT
tv158 = -536						; size = 4
tv143 = -536						; size = 4
tv92 = -536						; size = 4
tv74 = -536						; size = 4
_w_result$ = -336					; size = 4
_u_result$ = -324					; size = 4
_result$ = -312						; size = 4
_actual_w_buf_size$ = -300				; size = 4
_actual_w_buf$ = -288					; size = 256
_w$ = -24						; size = 4
_u$ = -12						; size = 4
__$ArrayPad$ = -4					; size = 4
_env$ = 8						; size = 4
_ep$ = 12						; size = 4
_no$ = 16						; size = 4
_u_buf$ = 20						; size = 4
_u_buf_size$ = 24					; size = 4
_v$ = 28						; size = 8
_desired_w_buf$ = 36					; size = 4
_desired_w_buf_size$ = 40				; size = 4
_TEST_Subtruct_X_L PROC					; COMDAT

; 113  : {

	push	ebp
	mov	ebp, esp
	sub	esp, 536				; 00000218H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-536]
	mov	ecx, 134				; 00000086H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	mov	DWORD PTR __$ArrayPad$[ebp], eax
	mov	ecx, OFFSET __433B2F9A_test_op_subtruct@c
	call	@__CheckForDebuggerJustMyCode@4

; 114  :     PMC_HANDLE_SINT u;
; 115  :     PMC_HANDLE_SINT w;
; 116  :     unsigned char actual_w_buf[256];
; 117  :     size_t actual_w_buf_size;
; 118  :     PMC_STATUS_CODE result;
; 119  :     PMC_STATUS_CODE u_result;
; 120  :     PMC_STATUS_CODE w_result;
; 121  :     TEST_Assert(env, FormatTestLabel(L"Subtruct_X_L (%d.%d)", no, 1), (u_result = ep->FromByteArray(u_buf, u_buf_size, &u)) == PMC_STATUS_OK, FormatTestMesssage(L"FromByteArrayの復帰コードが期待通りではない(%d)", u_result));

	mov	esi, esp
	lea	eax, DWORD PTR _u$[ebp]
	push	eax
	mov	ecx, DWORD PTR _u_buf_size$[ebp]
	push	ecx
	mov	edx, DWORD PTR _u_buf$[ebp]
	push	edx
	mov	eax, DWORD PTR _ep$[ebp]
	mov	ecx, DWORD PTR [eax+300]
	call	ecx
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _u_result$[ebp], eax
	cmp	DWORD PTR _u_result$[ebp], 0
	jne	SHORT $LN5@TEST_Subtr
	mov	DWORD PTR tv74[ebp], 1
	jmp	SHORT $LN6@TEST_Subtr
$LN5@TEST_Subtr:
	mov	DWORD PTR tv74[ebp], 0
$LN6@TEST_Subtr:
	mov	edx, DWORD PTR _u_result$[ebp]
	push	edx
	push	OFFSET ??_C@_1EC@NPMCAPKO@?$AAF?$AAr?$AAo?$AAm?$AAB?$AAy?$AAt?$AAe?$AAA?$AAr?$AAr?$AAa?$AAy?$AAn?$PP?$KJ@
	call	_FormatTestMesssage
	add	esp, 8
	push	eax
	mov	eax, DWORD PTR tv74[ebp]
	push	eax
	push	1
	mov	ecx, DWORD PTR _no$[ebp]
	push	ecx
	push	OFFSET ??_C@_1CK@MEDHKEAH@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAX?$AA_?$AAL?$AA?5?$AA?$CI?$AA?$CF@
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	edx, DWORD PTR _env$[ebp]
	push	edx
	call	_TEST_Assert
	add	esp, 16					; 00000010H

; 122  :     TEST_Assert(env, FormatTestLabel(L"Subtruct_X_L (%d.%d)", no, 2), (w_result = ep->Subtruct_X_L(u, v, &w)) == PMC_STATUS_OK, FormatTestMesssage(L"Subtruct_X_Lの復帰コードが期待通りではない(%d)", w_result));

	mov	esi, esp
	lea	eax, DWORD PTR _w$[ebp]
	push	eax
	mov	ecx, DWORD PTR _v$[ebp+4]
	push	ecx
	mov	edx, DWORD PTR _v$[ebp]
	push	edx
	mov	eax, DWORD PTR _u$[ebp]
	push	eax
	mov	ecx, DWORD PTR _ep$[ebp]
	mov	edx, DWORD PTR [ecx+372]
	call	edx
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _w_result$[ebp], eax
	cmp	DWORD PTR _w_result$[ebp], 0
	jne	SHORT $LN7@TEST_Subtr
	mov	DWORD PTR tv92[ebp], 1
	jmp	SHORT $LN8@TEST_Subtr
$LN7@TEST_Subtr:
	mov	DWORD PTR tv92[ebp], 0
$LN8@TEST_Subtr:
	mov	eax, DWORD PTR _w_result$[ebp]
	push	eax
	push	OFFSET ??_C@_1EA@MCHBOOEJ@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAX?$AA_?$AAL?$AAn?$PP?$KJ?$AA0@
	call	_FormatTestMesssage
	add	esp, 8
	push	eax
	mov	ecx, DWORD PTR tv92[ebp]
	push	ecx
	push	2
	mov	edx, DWORD PTR _no$[ebp]
	push	edx
	push	OFFSET ??_C@_1CK@MEDHKEAH@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAX?$AA_?$AAL?$AA?5?$AA?$CI?$AA?$CF@
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	eax, DWORD PTR _env$[ebp]
	push	eax
	call	_TEST_Assert
	add	esp, 16					; 00000010H

; 123  :     TEST_Assert(env, FormatTestLabel(L"Subtruct_X_L (%d.%d)", no, 3), (result = ep->ToByteArray(w, actual_w_buf, sizeof(actual_w_buf), &actual_w_buf_size)) == PMC_STATUS_OK, FormatTestMesssage(L"ToByteArrayの復帰コードが期待通りではない(%d)", result));

	mov	esi, esp
	lea	eax, DWORD PTR _actual_w_buf_size$[ebp]
	push	eax
	push	256					; 00000100H
	lea	ecx, DWORD PTR _actual_w_buf$[ebp]
	push	ecx
	mov	edx, DWORD PTR _w$[ebp]
	push	edx
	mov	eax, DWORD PTR _ep$[ebp]
	mov	ecx, DWORD PTR [eax+304]
	call	ecx
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _result$[ebp], eax
	cmp	DWORD PTR _result$[ebp], 0
	jne	SHORT $LN9@TEST_Subtr
	mov	DWORD PTR tv143[ebp], 1
	jmp	SHORT $LN10@TEST_Subtr
$LN9@TEST_Subtr:
	mov	DWORD PTR tv143[ebp], 0
$LN10@TEST_Subtr:
	mov	edx, DWORD PTR _result$[ebp]
	push	edx
	push	OFFSET ??_C@_1DO@DOHJEMND@?$AAT?$AAo?$AAB?$AAy?$AAt?$AAe?$AAA?$AAr?$AAr?$AAa?$AAy?$AAn?$PP?$KJ?$AA0?$PP?$LD@
	call	_FormatTestMesssage
	add	esp, 8
	push	eax
	mov	eax, DWORD PTR tv143[ebp]
	push	eax
	push	3
	mov	ecx, DWORD PTR _no$[ebp]
	push	ecx
	push	OFFSET ??_C@_1CK@MEDHKEAH@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAX?$AA_?$AAL?$AA?5?$AA?$CI?$AA?$CF@
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	edx, DWORD PTR _env$[ebp]
	push	edx
	call	_TEST_Assert
	add	esp, 16					; 00000010H

; 124  :     TEST_Assert(env, FormatTestLabel(L"Subtruct_X_L (%d.%d)", no, 4), _EQUALS_MEMORY(actual_w_buf, actual_w_buf_size, desired_w_buf, desired_w_buf_size) == 0, L"データの内容が一致しない");

	mov	eax, DWORD PTR _desired_w_buf_size$[ebp]
	push	eax
	mov	ecx, DWORD PTR _desired_w_buf$[ebp]
	push	ecx
	mov	edx, DWORD PTR _actual_w_buf_size$[ebp]
	push	edx
	lea	eax, DWORD PTR _actual_w_buf$[ebp]
	push	eax
	call	__EQUALS_MEMORY
	add	esp, 16					; 00000010H
	test	eax, eax
	jne	SHORT $LN11@TEST_Subtr
	mov	DWORD PTR tv158[ebp], 1
	jmp	SHORT $LN12@TEST_Subtr
$LN11@TEST_Subtr:
	mov	DWORD PTR tv158[ebp], 0
$LN12@TEST_Subtr:
	push	OFFSET ??_C@_1BK@CBDJCOBM@?$PP?G?$PP?$PM?$PP?$LP?$AAn?$PP?$IF?$PP?$LJ?$AAL?$AA?$AA?$PP?t?$AAW?$AAj?$AAD@
	mov	ecx, DWORD PTR tv158[ebp]
	push	ecx
	push	4
	mov	edx, DWORD PTR _no$[ebp]
	push	edx
	push	OFFSET ??_C@_1CK@MEDHKEAH@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAX?$AA_?$AAL?$AA?5?$AA?$CI?$AA?$CF@
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	eax, DWORD PTR _env$[ebp]
	push	eax
	call	_TEST_Assert
	add	esp, 16					; 00000010H

; 125  :     if (w_result == PMC_STATUS_OK)

	cmp	DWORD PTR _w_result$[ebp], 0
	jne	SHORT $LN2@TEST_Subtr

; 126  :         ep->Dispose(w);

	mov	esi, esp
	mov	eax, DWORD PTR _w$[ebp]
	push	eax
	mov	ecx, DWORD PTR _ep$[ebp]
	mov	edx, DWORD PTR [ecx+292]
	call	edx
	cmp	esi, esp
	call	__RTC_CheckEsp
$LN2@TEST_Subtr:

; 127  :     if (u_result == PMC_STATUS_OK)

	cmp	DWORD PTR _u_result$[ebp], 0
	jne	SHORT $LN1@TEST_Subtr

; 128  :         ep->Dispose(u);

	mov	esi, esp
	mov	eax, DWORD PTR _u$[ebp]
	push	eax
	mov	ecx, DWORD PTR _ep$[ebp]
	mov	edx, DWORD PTR [ecx+292]
	call	edx
	cmp	esi, esp
	call	__RTC_CheckEsp
$LN1@TEST_Subtr:

; 129  : }

	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN18@TEST_Subtr
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	pop	edi
	pop	esi
	pop	ebx
	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	ecx, ebp
	call	@__security_check_cookie@4
	add	esp, 536				; 00000218H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
	npad	3
$LN18@TEST_Subtr:
	DD	4
	DD	$LN17@TEST_Subtr
$LN17@TEST_Subtr:
	DD	-12					; fffffff4H
	DD	4
	DD	$LN13@TEST_Subtr
	DD	-24					; ffffffe8H
	DD	4
	DD	$LN14@TEST_Subtr
	DD	-288					; fffffee0H
	DD	256					; 00000100H
	DD	$LN15@TEST_Subtr
	DD	-300					; fffffed4H
	DD	4
	DD	$LN16@TEST_Subtr
$LN16@TEST_Subtr:
	DB	97					; 00000061H
	DB	99					; 00000063H
	DB	116					; 00000074H
	DB	117					; 00000075H
	DB	97					; 00000061H
	DB	108					; 0000006cH
	DB	95					; 0000005fH
	DB	119					; 00000077H
	DB	95					; 0000005fH
	DB	98					; 00000062H
	DB	117					; 00000075H
	DB	102					; 00000066H
	DB	95					; 0000005fH
	DB	115					; 00000073H
	DB	105					; 00000069H
	DB	122					; 0000007aH
	DB	101					; 00000065H
	DB	0
$LN15@TEST_Subtr:
	DB	97					; 00000061H
	DB	99					; 00000063H
	DB	116					; 00000074H
	DB	117					; 00000075H
	DB	97					; 00000061H
	DB	108					; 0000006cH
	DB	95					; 0000005fH
	DB	119					; 00000077H
	DB	95					; 0000005fH
	DB	98					; 00000062H
	DB	117					; 00000075H
	DB	102					; 00000066H
	DB	0
$LN14@TEST_Subtr:
	DB	119					; 00000077H
	DB	0
$LN13@TEST_Subtr:
	DB	117					; 00000075H
	DB	0
_TEST_Subtruct_X_L ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.sint\palmtree.math.core.sint\test_op_subtruct.c
;	COMDAT _TEST_Subtruct_X_I
_TEXT	SEGMENT
tv158 = -536						; size = 4
tv143 = -536						; size = 4
tv92 = -536						; size = 4
tv74 = -536						; size = 4
_w_result$ = -336					; size = 4
_u_result$ = -324					; size = 4
_result$ = -312						; size = 4
_actual_w_buf_size$ = -300				; size = 4
_actual_w_buf$ = -288					; size = 256
_w$ = -24						; size = 4
_u$ = -12						; size = 4
__$ArrayPad$ = -4					; size = 4
_env$ = 8						; size = 4
_ep$ = 12						; size = 4
_no$ = 16						; size = 4
_u_buf$ = 20						; size = 4
_u_buf_size$ = 24					; size = 4
_v$ = 28						; size = 4
_desired_w_buf$ = 32					; size = 4
_desired_w_buf_size$ = 36				; size = 4
_TEST_Subtruct_X_I PROC					; COMDAT

; 94   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 536				; 00000218H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-536]
	mov	ecx, 134				; 00000086H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	mov	DWORD PTR __$ArrayPad$[ebp], eax
	mov	ecx, OFFSET __433B2F9A_test_op_subtruct@c
	call	@__CheckForDebuggerJustMyCode@4

; 95   :     PMC_HANDLE_SINT u;
; 96   :     PMC_HANDLE_SINT w;
; 97   :     unsigned char actual_w_buf[256];
; 98   :     size_t actual_w_buf_size;
; 99   :     PMC_STATUS_CODE result;
; 100  :     PMC_STATUS_CODE u_result;
; 101  :     PMC_STATUS_CODE w_result;
; 102  :     TEST_Assert(env, FormatTestLabel(L"Subtruct_X_I (%d.%d)", no, 1), (u_result = ep->FromByteArray(u_buf, u_buf_size, &u)) == PMC_STATUS_OK, FormatTestMesssage(L"FromByteArrayの復帰コードが期待通りではない(%d)", u_result));

	mov	esi, esp
	lea	eax, DWORD PTR _u$[ebp]
	push	eax
	mov	ecx, DWORD PTR _u_buf_size$[ebp]
	push	ecx
	mov	edx, DWORD PTR _u_buf$[ebp]
	push	edx
	mov	eax, DWORD PTR _ep$[ebp]
	mov	ecx, DWORD PTR [eax+300]
	call	ecx
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _u_result$[ebp], eax
	cmp	DWORD PTR _u_result$[ebp], 0
	jne	SHORT $LN5@TEST_Subtr
	mov	DWORD PTR tv74[ebp], 1
	jmp	SHORT $LN6@TEST_Subtr
$LN5@TEST_Subtr:
	mov	DWORD PTR tv74[ebp], 0
$LN6@TEST_Subtr:
	mov	edx, DWORD PTR _u_result$[ebp]
	push	edx
	push	OFFSET ??_C@_1EC@NPMCAPKO@?$AAF?$AAr?$AAo?$AAm?$AAB?$AAy?$AAt?$AAe?$AAA?$AAr?$AAr?$AAa?$AAy?$AAn?$PP?$KJ@
	call	_FormatTestMesssage
	add	esp, 8
	push	eax
	mov	eax, DWORD PTR tv74[ebp]
	push	eax
	push	1
	mov	ecx, DWORD PTR _no$[ebp]
	push	ecx
	push	OFFSET ??_C@_1CK@OPLNHEBI@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAX?$AA_?$AAI?$AA?5?$AA?$CI?$AA?$CF@
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	edx, DWORD PTR _env$[ebp]
	push	edx
	call	_TEST_Assert
	add	esp, 16					; 00000010H

; 103  :     TEST_Assert(env, FormatTestLabel(L"Subtruct_X_I (%d.%d)", no, 2), (w_result = ep->Subtruct_X_I(u, v, &w)) == PMC_STATUS_OK, FormatTestMesssage(L"Subtruct_X_Iの復帰コードが期待通りではない(%d)", w_result));

	mov	esi, esp
	lea	eax, DWORD PTR _w$[ebp]
	push	eax
	mov	ecx, DWORD PTR _v$[ebp]
	push	ecx
	mov	edx, DWORD PTR _u$[ebp]
	push	edx
	mov	eax, DWORD PTR _ep$[ebp]
	mov	ecx, DWORD PTR [eax+368]
	call	ecx
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _w_result$[ebp], eax
	cmp	DWORD PTR _w_result$[ebp], 0
	jne	SHORT $LN7@TEST_Subtr
	mov	DWORD PTR tv92[ebp], 1
	jmp	SHORT $LN8@TEST_Subtr
$LN7@TEST_Subtr:
	mov	DWORD PTR tv92[ebp], 0
$LN8@TEST_Subtr:
	mov	edx, DWORD PTR _w_result$[ebp]
	push	edx
	push	OFFSET ??_C@_1EA@IKDNHDNM@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAX?$AA_?$AAI?$AAn?$PP?$KJ?$AA0@
	call	_FormatTestMesssage
	add	esp, 8
	push	eax
	mov	eax, DWORD PTR tv92[ebp]
	push	eax
	push	2
	mov	ecx, DWORD PTR _no$[ebp]
	push	ecx
	push	OFFSET ??_C@_1CK@OPLNHEBI@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAX?$AA_?$AAI?$AA?5?$AA?$CI?$AA?$CF@
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	edx, DWORD PTR _env$[ebp]
	push	edx
	call	_TEST_Assert
	add	esp, 16					; 00000010H

; 104  :     TEST_Assert(env, FormatTestLabel(L"Subtruct_X_I (%d.%d)", no, 3), (result = ep->ToByteArray(w, actual_w_buf, sizeof(actual_w_buf), &actual_w_buf_size)) == PMC_STATUS_OK, FormatTestMesssage(L"ToByteArrayの復帰コードが期待通りではない(%d)", result));

	mov	esi, esp
	lea	eax, DWORD PTR _actual_w_buf_size$[ebp]
	push	eax
	push	256					; 00000100H
	lea	ecx, DWORD PTR _actual_w_buf$[ebp]
	push	ecx
	mov	edx, DWORD PTR _w$[ebp]
	push	edx
	mov	eax, DWORD PTR _ep$[ebp]
	mov	ecx, DWORD PTR [eax+304]
	call	ecx
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _result$[ebp], eax
	cmp	DWORD PTR _result$[ebp], 0
	jne	SHORT $LN9@TEST_Subtr
	mov	DWORD PTR tv143[ebp], 1
	jmp	SHORT $LN10@TEST_Subtr
$LN9@TEST_Subtr:
	mov	DWORD PTR tv143[ebp], 0
$LN10@TEST_Subtr:
	mov	edx, DWORD PTR _result$[ebp]
	push	edx
	push	OFFSET ??_C@_1DO@DOHJEMND@?$AAT?$AAo?$AAB?$AAy?$AAt?$AAe?$AAA?$AAr?$AAr?$AAa?$AAy?$AAn?$PP?$KJ?$AA0?$PP?$LD@
	call	_FormatTestMesssage
	add	esp, 8
	push	eax
	mov	eax, DWORD PTR tv143[ebp]
	push	eax
	push	3
	mov	ecx, DWORD PTR _no$[ebp]
	push	ecx
	push	OFFSET ??_C@_1CK@OPLNHEBI@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAX?$AA_?$AAI?$AA?5?$AA?$CI?$AA?$CF@
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	edx, DWORD PTR _env$[ebp]
	push	edx
	call	_TEST_Assert
	add	esp, 16					; 00000010H

; 105  :     TEST_Assert(env, FormatTestLabel(L"Subtruct_X_I (%d.%d)", no, 4), _EQUALS_MEMORY(actual_w_buf, actual_w_buf_size, desired_w_buf, desired_w_buf_size) == 0, L"データの内容が一致しない");

	mov	eax, DWORD PTR _desired_w_buf_size$[ebp]
	push	eax
	mov	ecx, DWORD PTR _desired_w_buf$[ebp]
	push	ecx
	mov	edx, DWORD PTR _actual_w_buf_size$[ebp]
	push	edx
	lea	eax, DWORD PTR _actual_w_buf$[ebp]
	push	eax
	call	__EQUALS_MEMORY
	add	esp, 16					; 00000010H
	test	eax, eax
	jne	SHORT $LN11@TEST_Subtr
	mov	DWORD PTR tv158[ebp], 1
	jmp	SHORT $LN12@TEST_Subtr
$LN11@TEST_Subtr:
	mov	DWORD PTR tv158[ebp], 0
$LN12@TEST_Subtr:
	push	OFFSET ??_C@_1BK@CBDJCOBM@?$PP?G?$PP?$PM?$PP?$LP?$AAn?$PP?$IF?$PP?$LJ?$AAL?$AA?$AA?$PP?t?$AAW?$AAj?$AAD@
	mov	ecx, DWORD PTR tv158[ebp]
	push	ecx
	push	4
	mov	edx, DWORD PTR _no$[ebp]
	push	edx
	push	OFFSET ??_C@_1CK@OPLNHEBI@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAX?$AA_?$AAI?$AA?5?$AA?$CI?$AA?$CF@
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	eax, DWORD PTR _env$[ebp]
	push	eax
	call	_TEST_Assert
	add	esp, 16					; 00000010H

; 106  :     if (w_result == PMC_STATUS_OK)

	cmp	DWORD PTR _w_result$[ebp], 0
	jne	SHORT $LN2@TEST_Subtr

; 107  :         ep->Dispose(w);

	mov	esi, esp
	mov	eax, DWORD PTR _w$[ebp]
	push	eax
	mov	ecx, DWORD PTR _ep$[ebp]
	mov	edx, DWORD PTR [ecx+292]
	call	edx
	cmp	esi, esp
	call	__RTC_CheckEsp
$LN2@TEST_Subtr:

; 108  :     if (u_result == PMC_STATUS_OK)

	cmp	DWORD PTR _u_result$[ebp], 0
	jne	SHORT $LN1@TEST_Subtr

; 109  :         ep->Dispose(u);

	mov	esi, esp
	mov	eax, DWORD PTR _u$[ebp]
	push	eax
	mov	ecx, DWORD PTR _ep$[ebp]
	mov	edx, DWORD PTR [ecx+292]
	call	edx
	cmp	esi, esp
	call	__RTC_CheckEsp
$LN1@TEST_Subtr:

; 110  : }

	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN18@TEST_Subtr
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	pop	edi
	pop	esi
	pop	ebx
	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	ecx, ebp
	call	@__security_check_cookie@4
	add	esp, 536				; 00000218H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
	npad	3
$LN18@TEST_Subtr:
	DD	4
	DD	$LN17@TEST_Subtr
$LN17@TEST_Subtr:
	DD	-12					; fffffff4H
	DD	4
	DD	$LN13@TEST_Subtr
	DD	-24					; ffffffe8H
	DD	4
	DD	$LN14@TEST_Subtr
	DD	-288					; fffffee0H
	DD	256					; 00000100H
	DD	$LN15@TEST_Subtr
	DD	-300					; fffffed4H
	DD	4
	DD	$LN16@TEST_Subtr
$LN16@TEST_Subtr:
	DB	97					; 00000061H
	DB	99					; 00000063H
	DB	116					; 00000074H
	DB	117					; 00000075H
	DB	97					; 00000061H
	DB	108					; 0000006cH
	DB	95					; 0000005fH
	DB	119					; 00000077H
	DB	95					; 0000005fH
	DB	98					; 00000062H
	DB	117					; 00000075H
	DB	102					; 00000066H
	DB	95					; 0000005fH
	DB	115					; 00000073H
	DB	105					; 00000069H
	DB	122					; 0000007aH
	DB	101					; 00000065H
	DB	0
$LN15@TEST_Subtr:
	DB	97					; 00000061H
	DB	99					; 00000063H
	DB	116					; 00000074H
	DB	117					; 00000075H
	DB	97					; 00000061H
	DB	108					; 0000006cH
	DB	95					; 0000005fH
	DB	119					; 00000077H
	DB	95					; 0000005fH
	DB	98					; 00000062H
	DB	117					; 00000075H
	DB	102					; 00000066H
	DB	0
$LN14@TEST_Subtr:
	DB	119					; 00000077H
	DB	0
$LN13@TEST_Subtr:
	DB	117					; 00000075H
	DB	0
_TEST_Subtruct_X_I ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.sint\palmtree.math.core.sint\test_op_subtruct.c
;	COMDAT _TEST_Subtruct_UX_X
_TEXT	SEGMENT
tv176 = -560						; size = 4
tv161 = -560						; size = 4
tv142 = -560						; size = 4
tv92 = -560						; size = 4
tv74 = -560						; size = 4
_w_result$ = -360					; size = 4
_v_result$ = -348					; size = 4
_u_result$ = -336					; size = 4
_result$ = -324						; size = 4
_actual_w_buf_size$ = -312				; size = 4
_actual_w_buf$ = -300					; size = 256
_w$ = -36						; size = 4
_v$ = -24						; size = 4
_u$ = -12						; size = 4
__$ArrayPad$ = -4					; size = 4
_env$ = 8						; size = 4
_ep$ = 12						; size = 4
_no$ = 16						; size = 4
_u_buf$ = 20						; size = 4
_u_buf_size$ = 24					; size = 4
_v_buf$ = 28						; size = 4
_v_buf_size$ = 32					; size = 4
_desired_w_buf$ = 36					; size = 4
_desired_w_buf_size$ = 40				; size = 4
_TEST_Subtruct_UX_X PROC				; COMDAT

; 70   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 560				; 00000230H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-560]
	mov	ecx, 140				; 0000008cH
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	mov	DWORD PTR __$ArrayPad$[ebp], eax
	mov	ecx, OFFSET __433B2F9A_test_op_subtruct@c
	call	@__CheckForDebuggerJustMyCode@4

; 71   :     PMC_HANDLE_UINT u;
; 72   :     PMC_HANDLE_SINT v;
; 73   :     PMC_HANDLE_SINT w;
; 74   :     unsigned char actual_w_buf[256];
; 75   :     size_t actual_w_buf_size;
; 76   :     PMC_STATUS_CODE result;
; 77   :     PMC_STATUS_CODE u_result;
; 78   :     PMC_STATUS_CODE v_result;
; 79   :     PMC_STATUS_CODE w_result;
; 80   :     TEST_Assert(env, FormatTestLabel(L"Subtruct_UX_X (%d.%d)", no, 1), (u_result = ep->UINT_ENTRY_POINTS.FromByteArray(u_buf, u_buf_size, &u)) == PMC_STATUS_OK, FormatTestMesssage(L"FromByteArrayの復帰コードが期待通りではない(%d)", u_result));

	mov	esi, esp
	lea	eax, DWORD PTR _u$[ebp]
	push	eax
	mov	ecx, DWORD PTR _u_buf_size$[ebp]
	push	ecx
	mov	edx, DWORD PTR _u_buf$[ebp]
	push	edx
	mov	eax, DWORD PTR _ep$[ebp]
	mov	ecx, DWORD PTR [eax+24]
	call	ecx
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _u_result$[ebp], eax
	cmp	DWORD PTR _u_result$[ebp], 0
	jne	SHORT $LN6@TEST_Subtr
	mov	DWORD PTR tv74[ebp], 1
	jmp	SHORT $LN7@TEST_Subtr
$LN6@TEST_Subtr:
	mov	DWORD PTR tv74[ebp], 0
$LN7@TEST_Subtr:
	mov	edx, DWORD PTR _u_result$[ebp]
	push	edx
	push	OFFSET ??_C@_1EC@NPMCAPKO@?$AAF?$AAr?$AAo?$AAm?$AAB?$AAy?$AAt?$AAe?$AAA?$AAr?$AAr?$AAa?$AAy?$AAn?$PP?$KJ@
	call	_FormatTestMesssage
	add	esp, 8
	push	eax
	mov	eax, DWORD PTR tv74[ebp]
	push	eax
	push	1
	mov	ecx, DWORD PTR _no$[ebp]
	push	ecx
	push	OFFSET ??_C@_1CM@JOAGBAMJ@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAU?$AAX?$AA_?$AAX?$AA?5?$AA?$CI@
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	edx, DWORD PTR _env$[ebp]
	push	edx
	call	_TEST_Assert
	add	esp, 16					; 00000010H

; 81   :     TEST_Assert(env, FormatTestLabel(L"Subtruct_UX_X (%d.%d)", no, 2), (v_result = ep->FromByteArray(v_buf, v_buf_size, &v)) == PMC_STATUS_OK, FormatTestMesssage(L"FromByteArrayの復帰コードが期待通りではない(%d)", v_result));

	mov	esi, esp
	lea	eax, DWORD PTR _v$[ebp]
	push	eax
	mov	ecx, DWORD PTR _v_buf_size$[ebp]
	push	ecx
	mov	edx, DWORD PTR _v_buf$[ebp]
	push	edx
	mov	eax, DWORD PTR _ep$[ebp]
	mov	ecx, DWORD PTR [eax+300]
	call	ecx
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _v_result$[ebp], eax
	cmp	DWORD PTR _v_result$[ebp], 0
	jne	SHORT $LN8@TEST_Subtr
	mov	DWORD PTR tv92[ebp], 1
	jmp	SHORT $LN9@TEST_Subtr
$LN8@TEST_Subtr:
	mov	DWORD PTR tv92[ebp], 0
$LN9@TEST_Subtr:
	mov	edx, DWORD PTR _v_result$[ebp]
	push	edx
	push	OFFSET ??_C@_1EC@NPMCAPKO@?$AAF?$AAr?$AAo?$AAm?$AAB?$AAy?$AAt?$AAe?$AAA?$AAr?$AAr?$AAa?$AAy?$AAn?$PP?$KJ@
	call	_FormatTestMesssage
	add	esp, 8
	push	eax
	mov	eax, DWORD PTR tv92[ebp]
	push	eax
	push	2
	mov	ecx, DWORD PTR _no$[ebp]
	push	ecx
	push	OFFSET ??_C@_1CM@JOAGBAMJ@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAU?$AAX?$AA_?$AAX?$AA?5?$AA?$CI@
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	edx, DWORD PTR _env$[ebp]
	push	edx
	call	_TEST_Assert
	add	esp, 16					; 00000010H

; 82   :     TEST_Assert(env, FormatTestLabel(L"Subtruct_UX_X (%d.%d)", no, 3), (w_result = ep->Subtruct_UX_X(u, v, &w)) == PMC_STATUS_OK, FormatTestMesssage(L"Subtruct_UX_Xの復帰コードが期待通りではない(%d)", w_result));

	mov	esi, esp
	lea	eax, DWORD PTR _w$[ebp]
	push	eax
	mov	ecx, DWORD PTR _v$[ebp]
	push	ecx
	mov	edx, DWORD PTR _u$[ebp]
	push	edx
	mov	eax, DWORD PTR _ep$[ebp]
	mov	ecx, DWORD PTR [eax+364]
	call	ecx
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _w_result$[ebp], eax
	cmp	DWORD PTR _w_result$[ebp], 0
	jne	SHORT $LN10@TEST_Subtr
	mov	DWORD PTR tv142[ebp], 1
	jmp	SHORT $LN11@TEST_Subtr
$LN10@TEST_Subtr:
	mov	DWORD PTR tv142[ebp], 0
$LN11@TEST_Subtr:
	mov	edx, DWORD PTR _w_result$[ebp]
	push	edx
	push	OFFSET ??_C@_1EC@MMAEFCND@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAU?$AAX?$AA_?$AAX?$AAn?$PP?$KJ@
	call	_FormatTestMesssage
	add	esp, 8
	push	eax
	mov	eax, DWORD PTR tv142[ebp]
	push	eax
	push	3
	mov	ecx, DWORD PTR _no$[ebp]
	push	ecx
	push	OFFSET ??_C@_1CM@JOAGBAMJ@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAU?$AAX?$AA_?$AAX?$AA?5?$AA?$CI@
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	edx, DWORD PTR _env$[ebp]
	push	edx
	call	_TEST_Assert
	add	esp, 16					; 00000010H

; 83   :     TEST_Assert(env, FormatTestLabel(L"Subtruct_UX_X (%d.%d)", no, 4), (result = ep->ToByteArray(w, actual_w_buf, sizeof(actual_w_buf), &actual_w_buf_size)) == PMC_STATUS_OK, FormatTestMesssage(L"ToByteArrayの復帰コードが期待通りではない(%d)", result));

	mov	esi, esp
	lea	eax, DWORD PTR _actual_w_buf_size$[ebp]
	push	eax
	push	256					; 00000100H
	lea	ecx, DWORD PTR _actual_w_buf$[ebp]
	push	ecx
	mov	edx, DWORD PTR _w$[ebp]
	push	edx
	mov	eax, DWORD PTR _ep$[ebp]
	mov	ecx, DWORD PTR [eax+304]
	call	ecx
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _result$[ebp], eax
	cmp	DWORD PTR _result$[ebp], 0
	jne	SHORT $LN12@TEST_Subtr
	mov	DWORD PTR tv161[ebp], 1
	jmp	SHORT $LN13@TEST_Subtr
$LN12@TEST_Subtr:
	mov	DWORD PTR tv161[ebp], 0
$LN13@TEST_Subtr:
	mov	edx, DWORD PTR _result$[ebp]
	push	edx
	push	OFFSET ??_C@_1DO@DOHJEMND@?$AAT?$AAo?$AAB?$AAy?$AAt?$AAe?$AAA?$AAr?$AAr?$AAa?$AAy?$AAn?$PP?$KJ?$AA0?$PP?$LD@
	call	_FormatTestMesssage
	add	esp, 8
	push	eax
	mov	eax, DWORD PTR tv161[ebp]
	push	eax
	push	4
	mov	ecx, DWORD PTR _no$[ebp]
	push	ecx
	push	OFFSET ??_C@_1CM@JOAGBAMJ@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAU?$AAX?$AA_?$AAX?$AA?5?$AA?$CI@
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	edx, DWORD PTR _env$[ebp]
	push	edx
	call	_TEST_Assert
	add	esp, 16					; 00000010H

; 84   :     TEST_Assert(env, FormatTestLabel(L"Subtruct_UX_X (%d.%d)", no, 5), _EQUALS_MEMORY(actual_w_buf, actual_w_buf_size, desired_w_buf, desired_w_buf_size) == 0, L"データの内容が一致しない");

	mov	eax, DWORD PTR _desired_w_buf_size$[ebp]
	push	eax
	mov	ecx, DWORD PTR _desired_w_buf$[ebp]
	push	ecx
	mov	edx, DWORD PTR _actual_w_buf_size$[ebp]
	push	edx
	lea	eax, DWORD PTR _actual_w_buf$[ebp]
	push	eax
	call	__EQUALS_MEMORY
	add	esp, 16					; 00000010H
	test	eax, eax
	jne	SHORT $LN14@TEST_Subtr
	mov	DWORD PTR tv176[ebp], 1
	jmp	SHORT $LN15@TEST_Subtr
$LN14@TEST_Subtr:
	mov	DWORD PTR tv176[ebp], 0
$LN15@TEST_Subtr:
	push	OFFSET ??_C@_1BK@CBDJCOBM@?$PP?G?$PP?$PM?$PP?$LP?$AAn?$PP?$IF?$PP?$LJ?$AAL?$AA?$AA?$PP?t?$AAW?$AAj?$AAD@
	mov	ecx, DWORD PTR tv176[ebp]
	push	ecx
	push	5
	mov	edx, DWORD PTR _no$[ebp]
	push	edx
	push	OFFSET ??_C@_1CM@JOAGBAMJ@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAU?$AAX?$AA_?$AAX?$AA?5?$AA?$CI@
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	eax, DWORD PTR _env$[ebp]
	push	eax
	call	_TEST_Assert
	add	esp, 16					; 00000010H

; 85   :     if (w_result == PMC_STATUS_OK)

	cmp	DWORD PTR _w_result$[ebp], 0
	jne	SHORT $LN2@TEST_Subtr

; 86   :         ep->Dispose(w);

	mov	esi, esp
	mov	eax, DWORD PTR _w$[ebp]
	push	eax
	mov	ecx, DWORD PTR _ep$[ebp]
	mov	edx, DWORD PTR [ecx+292]
	call	edx
	cmp	esi, esp
	call	__RTC_CheckEsp
$LN2@TEST_Subtr:

; 87   :     if (v_result == PMC_STATUS_OK)

	cmp	DWORD PTR _v_result$[ebp], 0
	jne	SHORT $LN3@TEST_Subtr

; 88   :         ep->Dispose(v);

	mov	esi, esp
	mov	eax, DWORD PTR _v$[ebp]
	push	eax
	mov	ecx, DWORD PTR _ep$[ebp]
	mov	edx, DWORD PTR [ecx+292]
	call	edx
	cmp	esi, esp
	call	__RTC_CheckEsp
$LN3@TEST_Subtr:

; 89   :     if (u_result == PMC_STATUS_OK)

	cmp	DWORD PTR _u_result$[ebp], 0
	jne	SHORT $LN1@TEST_Subtr

; 90   :         ep->UINT_ENTRY_POINTS.Dispose(u);

	mov	esi, esp
	mov	eax, DWORD PTR _u$[ebp]
	push	eax
	mov	ecx, DWORD PTR _ep$[ebp]
	mov	edx, DWORD PTR [ecx+16]
	call	edx
	cmp	esi, esp
	call	__RTC_CheckEsp
$LN1@TEST_Subtr:

; 91   : }

	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN22@TEST_Subtr
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	pop	edi
	pop	esi
	pop	ebx
	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	ecx, ebp
	call	@__security_check_cookie@4
	add	esp, 560				; 00000230H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
	npad	3
$LN22@TEST_Subtr:
	DD	5
	DD	$LN21@TEST_Subtr
$LN21@TEST_Subtr:
	DD	-12					; fffffff4H
	DD	4
	DD	$LN16@TEST_Subtr
	DD	-24					; ffffffe8H
	DD	4
	DD	$LN17@TEST_Subtr
	DD	-36					; ffffffdcH
	DD	4
	DD	$LN18@TEST_Subtr
	DD	-300					; fffffed4H
	DD	256					; 00000100H
	DD	$LN19@TEST_Subtr
	DD	-312					; fffffec8H
	DD	4
	DD	$LN20@TEST_Subtr
$LN20@TEST_Subtr:
	DB	97					; 00000061H
	DB	99					; 00000063H
	DB	116					; 00000074H
	DB	117					; 00000075H
	DB	97					; 00000061H
	DB	108					; 0000006cH
	DB	95					; 0000005fH
	DB	119					; 00000077H
	DB	95					; 0000005fH
	DB	98					; 00000062H
	DB	117					; 00000075H
	DB	102					; 00000066H
	DB	95					; 0000005fH
	DB	115					; 00000073H
	DB	105					; 00000069H
	DB	122					; 0000007aH
	DB	101					; 00000065H
	DB	0
$LN19@TEST_Subtr:
	DB	97					; 00000061H
	DB	99					; 00000063H
	DB	116					; 00000074H
	DB	117					; 00000075H
	DB	97					; 00000061H
	DB	108					; 0000006cH
	DB	95					; 0000005fH
	DB	119					; 00000077H
	DB	95					; 0000005fH
	DB	98					; 00000062H
	DB	117					; 00000075H
	DB	102					; 00000066H
	DB	0
$LN18@TEST_Subtr:
	DB	119					; 00000077H
	DB	0
$LN17@TEST_Subtr:
	DB	118					; 00000076H
	DB	0
$LN16@TEST_Subtr:
	DB	117					; 00000075H
	DB	0
_TEST_Subtruct_UX_X ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.sint\palmtree.math.core.sint\test_op_subtruct.c
;	COMDAT _TEST_Subtruct_L_X
_TEXT	SEGMENT
tv158 = -536						; size = 4
tv143 = -536						; size = 4
tv92 = -536						; size = 4
tv74 = -536						; size = 4
_w_result$ = -336					; size = 4
_v_result$ = -324					; size = 4
_result$ = -312						; size = 4
_actual_w_buf_size$ = -300				; size = 4
_actual_w_buf$ = -288					; size = 256
_w$ = -24						; size = 4
_v$ = -12						; size = 4
__$ArrayPad$ = -4					; size = 4
_env$ = 8						; size = 4
_ep$ = 12						; size = 4
_no$ = 16						; size = 4
_u$ = 20						; size = 8
_v_buf$ = 28						; size = 4
_v_buf_size$ = 32					; size = 4
_desired_w_buf$ = 36					; size = 4
_desired_w_buf_size$ = 40				; size = 4
_TEST_Subtruct_L_X PROC					; COMDAT

; 51   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 536				; 00000218H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-536]
	mov	ecx, 134				; 00000086H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	mov	DWORD PTR __$ArrayPad$[ebp], eax
	mov	ecx, OFFSET __433B2F9A_test_op_subtruct@c
	call	@__CheckForDebuggerJustMyCode@4

; 52   :     PMC_HANDLE_SINT v;
; 53   :     PMC_HANDLE_SINT w;
; 54   :     unsigned char actual_w_buf[256];
; 55   :     size_t actual_w_buf_size;
; 56   :     PMC_STATUS_CODE result;
; 57   :     PMC_STATUS_CODE v_result;
; 58   :     PMC_STATUS_CODE w_result;
; 59   :     TEST_Assert(env, FormatTestLabel(L"Subtruct_L_X (%d.%d)", no, 1), (v_result = ep->FromByteArray(v_buf, v_buf_size, &v)) == PMC_STATUS_OK, FormatTestMesssage(L"FromByteArrayの復帰コードが期待通りではない(%d)", v_result));

	mov	esi, esp
	lea	eax, DWORD PTR _v$[ebp]
	push	eax
	mov	ecx, DWORD PTR _v_buf_size$[ebp]
	push	ecx
	mov	edx, DWORD PTR _v_buf$[ebp]
	push	edx
	mov	eax, DWORD PTR _ep$[ebp]
	mov	ecx, DWORD PTR [eax+300]
	call	ecx
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _v_result$[ebp], eax
	cmp	DWORD PTR _v_result$[ebp], 0
	jne	SHORT $LN5@TEST_Subtr
	mov	DWORD PTR tv74[ebp], 1
	jmp	SHORT $LN6@TEST_Subtr
$LN5@TEST_Subtr:
	mov	DWORD PTR tv74[ebp], 0
$LN6@TEST_Subtr:
	mov	edx, DWORD PTR _v_result$[ebp]
	push	edx
	push	OFFSET ??_C@_1EC@NPMCAPKO@?$AAF?$AAr?$AAo?$AAm?$AAB?$AAy?$AAt?$AAe?$AAA?$AAr?$AAr?$AAa?$AAy?$AAn?$PP?$KJ@
	call	_FormatTestMesssage
	add	esp, 8
	push	eax
	mov	eax, DWORD PTR tv74[ebp]
	push	eax
	push	1
	mov	ecx, DWORD PTR _no$[ebp]
	push	ecx
	push	OFFSET ??_C@_1CK@HMHBAFBJ@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAL?$AA_?$AAX?$AA?5?$AA?$CI?$AA?$CF@
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	edx, DWORD PTR _env$[ebp]
	push	edx
	call	_TEST_Assert
	add	esp, 16					; 00000010H

; 60   :     TEST_Assert(env, FormatTestLabel(L"Subtruct_L_X (%d.%d)", no, 2), (w_result = ep->Subtruct_L_X(u, v, &w)) == PMC_STATUS_OK, FormatTestMesssage(L"Subtruct_L_Xの復帰コードが期待通りではない(%d)", w_result));

	mov	esi, esp
	lea	eax, DWORD PTR _w$[ebp]
	push	eax
	mov	ecx, DWORD PTR _v$[ebp]
	push	ecx
	mov	edx, DWORD PTR _u$[ebp+4]
	push	edx
	mov	eax, DWORD PTR _u$[ebp]
	push	eax
	mov	ecx, DWORD PTR _ep$[ebp]
	mov	edx, DWORD PTR [ecx+360]
	call	edx
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _w_result$[ebp], eax
	cmp	DWORD PTR _w_result$[ebp], 0
	jne	SHORT $LN7@TEST_Subtr
	mov	DWORD PTR tv92[ebp], 1
	jmp	SHORT $LN8@TEST_Subtr
$LN7@TEST_Subtr:
	mov	DWORD PTR tv92[ebp], 0
$LN8@TEST_Subtr:
	mov	eax, DWORD PTR _w_result$[ebp]
	push	eax
	push	OFFSET ??_C@_1EA@INDIFGGF@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAL?$AA_?$AAX?$AAn?$PP?$KJ?$AA0@
	call	_FormatTestMesssage
	add	esp, 8
	push	eax
	mov	ecx, DWORD PTR tv92[ebp]
	push	ecx
	push	2
	mov	edx, DWORD PTR _no$[ebp]
	push	edx
	push	OFFSET ??_C@_1CK@HMHBAFBJ@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAL?$AA_?$AAX?$AA?5?$AA?$CI?$AA?$CF@
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	eax, DWORD PTR _env$[ebp]
	push	eax
	call	_TEST_Assert
	add	esp, 16					; 00000010H

; 61   :     TEST_Assert(env, FormatTestLabel(L"Subtruct_L_X (%d.%d)", no, 3), (result = ep->ToByteArray(w, actual_w_buf, sizeof(actual_w_buf), &actual_w_buf_size)) == PMC_STATUS_OK, FormatTestMesssage(L"ToByteArrayの復帰コードが期待通りではない(%d)", result));

	mov	esi, esp
	lea	eax, DWORD PTR _actual_w_buf_size$[ebp]
	push	eax
	push	256					; 00000100H
	lea	ecx, DWORD PTR _actual_w_buf$[ebp]
	push	ecx
	mov	edx, DWORD PTR _w$[ebp]
	push	edx
	mov	eax, DWORD PTR _ep$[ebp]
	mov	ecx, DWORD PTR [eax+304]
	call	ecx
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _result$[ebp], eax
	cmp	DWORD PTR _result$[ebp], 0
	jne	SHORT $LN9@TEST_Subtr
	mov	DWORD PTR tv143[ebp], 1
	jmp	SHORT $LN10@TEST_Subtr
$LN9@TEST_Subtr:
	mov	DWORD PTR tv143[ebp], 0
$LN10@TEST_Subtr:
	mov	edx, DWORD PTR _result$[ebp]
	push	edx
	push	OFFSET ??_C@_1DO@DOHJEMND@?$AAT?$AAo?$AAB?$AAy?$AAt?$AAe?$AAA?$AAr?$AAr?$AAa?$AAy?$AAn?$PP?$KJ?$AA0?$PP?$LD@
	call	_FormatTestMesssage
	add	esp, 8
	push	eax
	mov	eax, DWORD PTR tv143[ebp]
	push	eax
	push	3
	mov	ecx, DWORD PTR _no$[ebp]
	push	ecx
	push	OFFSET ??_C@_1CK@HMHBAFBJ@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAL?$AA_?$AAX?$AA?5?$AA?$CI?$AA?$CF@
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	edx, DWORD PTR _env$[ebp]
	push	edx
	call	_TEST_Assert
	add	esp, 16					; 00000010H

; 62   :     TEST_Assert(env, FormatTestLabel(L"Subtruct_L_X (%d.%d)", no, 4), _EQUALS_MEMORY(actual_w_buf, actual_w_buf_size, desired_w_buf, desired_w_buf_size) == 0, L"データの内容が一致しない");

	mov	eax, DWORD PTR _desired_w_buf_size$[ebp]
	push	eax
	mov	ecx, DWORD PTR _desired_w_buf$[ebp]
	push	ecx
	mov	edx, DWORD PTR _actual_w_buf_size$[ebp]
	push	edx
	lea	eax, DWORD PTR _actual_w_buf$[ebp]
	push	eax
	call	__EQUALS_MEMORY
	add	esp, 16					; 00000010H
	test	eax, eax
	jne	SHORT $LN11@TEST_Subtr
	mov	DWORD PTR tv158[ebp], 1
	jmp	SHORT $LN12@TEST_Subtr
$LN11@TEST_Subtr:
	mov	DWORD PTR tv158[ebp], 0
$LN12@TEST_Subtr:
	push	OFFSET ??_C@_1BK@CBDJCOBM@?$PP?G?$PP?$PM?$PP?$LP?$AAn?$PP?$IF?$PP?$LJ?$AAL?$AA?$AA?$PP?t?$AAW?$AAj?$AAD@
	mov	ecx, DWORD PTR tv158[ebp]
	push	ecx
	push	4
	mov	edx, DWORD PTR _no$[ebp]
	push	edx
	push	OFFSET ??_C@_1CK@HMHBAFBJ@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAL?$AA_?$AAX?$AA?5?$AA?$CI?$AA?$CF@
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	eax, DWORD PTR _env$[ebp]
	push	eax
	call	_TEST_Assert
	add	esp, 16					; 00000010H

; 63   :     if (w_result == PMC_STATUS_OK)

	cmp	DWORD PTR _w_result$[ebp], 0
	jne	SHORT $LN2@TEST_Subtr

; 64   :         ep->Dispose(w);

	mov	esi, esp
	mov	eax, DWORD PTR _w$[ebp]
	push	eax
	mov	ecx, DWORD PTR _ep$[ebp]
	mov	edx, DWORD PTR [ecx+292]
	call	edx
	cmp	esi, esp
	call	__RTC_CheckEsp
$LN2@TEST_Subtr:

; 65   :     if (v_result == PMC_STATUS_OK)

	cmp	DWORD PTR _v_result$[ebp], 0
	jne	SHORT $LN1@TEST_Subtr

; 66   :         ep->Dispose(v);

	mov	esi, esp
	mov	eax, DWORD PTR _v$[ebp]
	push	eax
	mov	ecx, DWORD PTR _ep$[ebp]
	mov	edx, DWORD PTR [ecx+292]
	call	edx
	cmp	esi, esp
	call	__RTC_CheckEsp
$LN1@TEST_Subtr:

; 67   : }

	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN18@TEST_Subtr
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	pop	edi
	pop	esi
	pop	ebx
	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	ecx, ebp
	call	@__security_check_cookie@4
	add	esp, 536				; 00000218H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
	npad	3
$LN18@TEST_Subtr:
	DD	4
	DD	$LN17@TEST_Subtr
$LN17@TEST_Subtr:
	DD	-12					; fffffff4H
	DD	4
	DD	$LN13@TEST_Subtr
	DD	-24					; ffffffe8H
	DD	4
	DD	$LN14@TEST_Subtr
	DD	-288					; fffffee0H
	DD	256					; 00000100H
	DD	$LN15@TEST_Subtr
	DD	-300					; fffffed4H
	DD	4
	DD	$LN16@TEST_Subtr
$LN16@TEST_Subtr:
	DB	97					; 00000061H
	DB	99					; 00000063H
	DB	116					; 00000074H
	DB	117					; 00000075H
	DB	97					; 00000061H
	DB	108					; 0000006cH
	DB	95					; 0000005fH
	DB	119					; 00000077H
	DB	95					; 0000005fH
	DB	98					; 00000062H
	DB	117					; 00000075H
	DB	102					; 00000066H
	DB	95					; 0000005fH
	DB	115					; 00000073H
	DB	105					; 00000069H
	DB	122					; 0000007aH
	DB	101					; 00000065H
	DB	0
$LN15@TEST_Subtr:
	DB	97					; 00000061H
	DB	99					; 00000063H
	DB	116					; 00000074H
	DB	117					; 00000075H
	DB	97					; 00000061H
	DB	108					; 0000006cH
	DB	95					; 0000005fH
	DB	119					; 00000077H
	DB	95					; 0000005fH
	DB	98					; 00000062H
	DB	117					; 00000075H
	DB	102					; 00000066H
	DB	0
$LN14@TEST_Subtr:
	DB	119					; 00000077H
	DB	0
$LN13@TEST_Subtr:
	DB	118					; 00000076H
	DB	0
_TEST_Subtruct_L_X ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.sint\palmtree.math.core.sint\test_op_subtruct.c
;	COMDAT _TEST_Subtruct_I_X
_TEXT	SEGMENT
tv158 = -536						; size = 4
tv143 = -536						; size = 4
tv92 = -536						; size = 4
tv74 = -536						; size = 4
_w_result$ = -336					; size = 4
_v_result$ = -324					; size = 4
_result$ = -312						; size = 4
_actual_w_buf_size$ = -300				; size = 4
_actual_w_buf$ = -288					; size = 256
_w$ = -24						; size = 4
_v$ = -12						; size = 4
__$ArrayPad$ = -4					; size = 4
_env$ = 8						; size = 4
_ep$ = 12						; size = 4
_no$ = 16						; size = 4
_u$ = 20						; size = 4
_v_buf$ = 24						; size = 4
_v_buf_size$ = 28					; size = 4
_desired_w_buf$ = 32					; size = 4
_desired_w_buf_size$ = 36				; size = 4
_TEST_Subtruct_I_X PROC					; COMDAT

; 32   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 536				; 00000218H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-536]
	mov	ecx, 134				; 00000086H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	mov	DWORD PTR __$ArrayPad$[ebp], eax
	mov	ecx, OFFSET __433B2F9A_test_op_subtruct@c
	call	@__CheckForDebuggerJustMyCode@4

; 33   :     PMC_HANDLE_SINT v;
; 34   :     PMC_HANDLE_SINT w;
; 35   :     unsigned char actual_w_buf[256];
; 36   :     size_t actual_w_buf_size;
; 37   :     PMC_STATUS_CODE result;
; 38   :     PMC_STATUS_CODE v_result;
; 39   :     PMC_STATUS_CODE w_result;
; 40   :     TEST_Assert(env, FormatTestLabel(L"Subtruct_I_X (%d.%d)", no, 1), (v_result = ep->FromByteArray(v_buf, v_buf_size, &v)) == PMC_STATUS_OK, FormatTestMesssage(L"FromByteArrayの復帰コードが期待通りではない(%d)", v_result));

	mov	esi, esp
	lea	eax, DWORD PTR _v$[ebp]
	push	eax
	mov	ecx, DWORD PTR _v_buf_size$[ebp]
	push	ecx
	mov	edx, DWORD PTR _v_buf$[ebp]
	push	edx
	mov	eax, DWORD PTR _ep$[ebp]
	mov	ecx, DWORD PTR [eax+300]
	call	ecx
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _v_result$[ebp], eax
	cmp	DWORD PTR _v_result$[ebp], 0
	jne	SHORT $LN5@TEST_Subtr
	mov	DWORD PTR tv74[ebp], 1
	jmp	SHORT $LN6@TEST_Subtr
$LN5@TEST_Subtr:
	mov	DWORD PTR tv74[ebp], 0
$LN6@TEST_Subtr:
	mov	edx, DWORD PTR _v_result$[ebp]
	push	edx
	push	OFFSET ??_C@_1EC@NPMCAPKO@?$AAF?$AAr?$AAo?$AAm?$AAB?$AAy?$AAt?$AAe?$AAA?$AAr?$AAr?$AAa?$AAy?$AAn?$PP?$KJ@
	call	_FormatTestMesssage
	add	esp, 8
	push	eax
	mov	eax, DWORD PTR tv74[ebp]
	push	eax
	push	1
	mov	ecx, DWORD PTR _no$[ebp]
	push	ecx
	push	OFFSET ??_C@_1CK@JEFCPOGB@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAI?$AA_?$AAX?$AA?5?$AA?$CI?$AA?$CF@
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	edx, DWORD PTR _env$[ebp]
	push	edx
	call	_TEST_Assert
	add	esp, 16					; 00000010H

; 41   :     TEST_Assert(env, FormatTestLabel(L"Subtruct_I_X (%d.%d)", no, 2), (w_result = ep->Subtruct_I_X(u, v, &w)) == PMC_STATUS_OK, FormatTestMesssage(L"Subtruct_I_Xの復帰コードが期待通りではない(%d)", w_result));

	mov	esi, esp
	lea	eax, DWORD PTR _w$[ebp]
	push	eax
	mov	ecx, DWORD PTR _v$[ebp]
	push	ecx
	mov	edx, DWORD PTR _u$[ebp]
	push	edx
	mov	eax, DWORD PTR _ep$[ebp]
	mov	ecx, DWORD PTR [eax+356]
	call	ecx
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _w_result$[ebp], eax
	cmp	DWORD PTR _w_result$[ebp], 0
	jne	SHORT $LN7@TEST_Subtr
	mov	DWORD PTR tv92[ebp], 1
	jmp	SHORT $LN8@TEST_Subtr
$LN7@TEST_Subtr:
	mov	DWORD PTR tv92[ebp], 0
$LN8@TEST_Subtr:
	mov	edx, DWORD PTR _w_result$[ebp]
	push	edx
	push	OFFSET ??_C@_1EA@NGKGKFPL@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAI?$AA_?$AAX?$AAn?$PP?$KJ?$AA0@
	call	_FormatTestMesssage
	add	esp, 8
	push	eax
	mov	eax, DWORD PTR tv92[ebp]
	push	eax
	push	2
	mov	ecx, DWORD PTR _no$[ebp]
	push	ecx
	push	OFFSET ??_C@_1CK@JEFCPOGB@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAI?$AA_?$AAX?$AA?5?$AA?$CI?$AA?$CF@
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	edx, DWORD PTR _env$[ebp]
	push	edx
	call	_TEST_Assert
	add	esp, 16					; 00000010H

; 42   :     TEST_Assert(env, FormatTestLabel(L"Subtruct_I_X (%d.%d)", no, 3), (result = ep->ToByteArray(w, actual_w_buf, sizeof(actual_w_buf), &actual_w_buf_size)) == PMC_STATUS_OK, FormatTestMesssage(L"ToByteArrayの復帰コードが期待通りではない(%d)", result));

	mov	esi, esp
	lea	eax, DWORD PTR _actual_w_buf_size$[ebp]
	push	eax
	push	256					; 00000100H
	lea	ecx, DWORD PTR _actual_w_buf$[ebp]
	push	ecx
	mov	edx, DWORD PTR _w$[ebp]
	push	edx
	mov	eax, DWORD PTR _ep$[ebp]
	mov	ecx, DWORD PTR [eax+304]
	call	ecx
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _result$[ebp], eax
	cmp	DWORD PTR _result$[ebp], 0
	jne	SHORT $LN9@TEST_Subtr
	mov	DWORD PTR tv143[ebp], 1
	jmp	SHORT $LN10@TEST_Subtr
$LN9@TEST_Subtr:
	mov	DWORD PTR tv143[ebp], 0
$LN10@TEST_Subtr:
	mov	edx, DWORD PTR _result$[ebp]
	push	edx
	push	OFFSET ??_C@_1DO@DOHJEMND@?$AAT?$AAo?$AAB?$AAy?$AAt?$AAe?$AAA?$AAr?$AAr?$AAa?$AAy?$AAn?$PP?$KJ?$AA0?$PP?$LD@
	call	_FormatTestMesssage
	add	esp, 8
	push	eax
	mov	eax, DWORD PTR tv143[ebp]
	push	eax
	push	3
	mov	ecx, DWORD PTR _no$[ebp]
	push	ecx
	push	OFFSET ??_C@_1CK@JEFCPOGB@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAI?$AA_?$AAX?$AA?5?$AA?$CI?$AA?$CF@
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	edx, DWORD PTR _env$[ebp]
	push	edx
	call	_TEST_Assert
	add	esp, 16					; 00000010H

; 43   :     TEST_Assert(env, FormatTestLabel(L"Subtruct_I_X (%d.%d)", no, 4), _EQUALS_MEMORY(actual_w_buf, actual_w_buf_size, desired_w_buf, desired_w_buf_size) == 0, L"データの内容が一致しない");

	mov	eax, DWORD PTR _desired_w_buf_size$[ebp]
	push	eax
	mov	ecx, DWORD PTR _desired_w_buf$[ebp]
	push	ecx
	mov	edx, DWORD PTR _actual_w_buf_size$[ebp]
	push	edx
	lea	eax, DWORD PTR _actual_w_buf$[ebp]
	push	eax
	call	__EQUALS_MEMORY
	add	esp, 16					; 00000010H
	test	eax, eax
	jne	SHORT $LN11@TEST_Subtr
	mov	DWORD PTR tv158[ebp], 1
	jmp	SHORT $LN12@TEST_Subtr
$LN11@TEST_Subtr:
	mov	DWORD PTR tv158[ebp], 0
$LN12@TEST_Subtr:
	push	OFFSET ??_C@_1BK@CBDJCOBM@?$PP?G?$PP?$PM?$PP?$LP?$AAn?$PP?$IF?$PP?$LJ?$AAL?$AA?$AA?$PP?t?$AAW?$AAj?$AAD@
	mov	ecx, DWORD PTR tv158[ebp]
	push	ecx
	push	4
	mov	edx, DWORD PTR _no$[ebp]
	push	edx
	push	OFFSET ??_C@_1CK@JEFCPOGB@?$AAS?$AAu?$AAb?$AAt?$AAr?$AAu?$AAc?$AAt?$AA_?$AAI?$AA_?$AAX?$AA?5?$AA?$CI?$AA?$CF@
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	eax, DWORD PTR _env$[ebp]
	push	eax
	call	_TEST_Assert
	add	esp, 16					; 00000010H

; 44   :     if (w_result == PMC_STATUS_OK)

	cmp	DWORD PTR _w_result$[ebp], 0
	jne	SHORT $LN2@TEST_Subtr

; 45   :         ep->Dispose(w);

	mov	esi, esp
	mov	eax, DWORD PTR _w$[ebp]
	push	eax
	mov	ecx, DWORD PTR _ep$[ebp]
	mov	edx, DWORD PTR [ecx+292]
	call	edx
	cmp	esi, esp
	call	__RTC_CheckEsp
$LN2@TEST_Subtr:

; 46   :     if (v_result == PMC_STATUS_OK)

	cmp	DWORD PTR _v_result$[ebp], 0
	jne	SHORT $LN1@TEST_Subtr

; 47   :         ep->Dispose(v);

	mov	esi, esp
	mov	eax, DWORD PTR _v$[ebp]
	push	eax
	mov	ecx, DWORD PTR _ep$[ebp]
	mov	edx, DWORD PTR [ecx+292]
	call	edx
	cmp	esi, esp
	call	__RTC_CheckEsp
$LN1@TEST_Subtr:

; 48   : }

	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN18@TEST_Subtr
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	pop	edi
	pop	esi
	pop	ebx
	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	ecx, ebp
	call	@__security_check_cookie@4
	add	esp, 536				; 00000218H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
	npad	3
$LN18@TEST_Subtr:
	DD	4
	DD	$LN17@TEST_Subtr
$LN17@TEST_Subtr:
	DD	-12					; fffffff4H
	DD	4
	DD	$LN13@TEST_Subtr
	DD	-24					; ffffffe8H
	DD	4
	DD	$LN14@TEST_Subtr
	DD	-288					; fffffee0H
	DD	256					; 00000100H
	DD	$LN15@TEST_Subtr
	DD	-300					; fffffed4H
	DD	4
	DD	$LN16@TEST_Subtr
$LN16@TEST_Subtr:
	DB	97					; 00000061H
	DB	99					; 00000063H
	DB	116					; 00000074H
	DB	117					; 00000075H
	DB	97					; 00000061H
	DB	108					; 0000006cH
	DB	95					; 0000005fH
	DB	119					; 00000077H
	DB	95					; 0000005fH
	DB	98					; 00000062H
	DB	117					; 00000075H
	DB	102					; 00000066H
	DB	95					; 0000005fH
	DB	115					; 00000073H
	DB	105					; 00000069H
	DB	122					; 0000007aH
	DB	101					; 00000065H
	DB	0
$LN15@TEST_Subtr:
	DB	97					; 00000061H
	DB	99					; 00000063H
	DB	116					; 00000074H
	DB	117					; 00000075H
	DB	97					; 00000061H
	DB	108					; 0000006cH
	DB	95					; 0000005fH
	DB	119					; 00000077H
	DB	95					; 0000005fH
	DB	98					; 00000062H
	DB	117					; 00000075H
	DB	102					; 00000066H
	DB	0
$LN14@TEST_Subtr:
	DB	119					; 00000077H
	DB	0
$LN13@TEST_Subtr:
	DB	118					; 00000076H
	DB	0
_TEST_Subtruct_I_X ENDP
_TEXT	ENDS
END
